import { ROUTE_PATHS, ROUTE_TYPES } from '@platform/config/routes'

export type { RoutePathKey, RoutePathValues } from '@platform/config/routes'
export { ROUTE_PATHS, ROUTE_TYPES }

export const {
  LANDING,
  MAP,
  USER,
  SEARCH,
  REPORT,
  VESSEL,
  WORKSPACES_LIST,
  WORKSPACE,
  WORKSPACE_SEARCH,
  WORKSPACE_VESSEL,
  WORKSPACE_REPORT,
  VESSEL_GROUP_REPORT,
  PORT_REPORT,
  HELP_HUB,
  HELP_HUB_SECTION,
  HELP_HUB_TOPIC,
} = ROUTE_TYPES

export const WORKSPACE_ROUTES: ROUTE_TYPES[] = [MAP, WORKSPACE]
export const HELP_HUB_ROUTES: ROUTE_TYPES[] = [HELP_HUB, HELP_HUB_SECTION, HELP_HUB_TOPIC]
export const REPORT_ROUTES: ROUTE_TYPES[] = [
  REPORT,
  WORKSPACE_REPORT,
  PORT_REPORT,
  VESSEL_GROUP_REPORT,
]
export const VESSEL_ROUTES: ROUTE_TYPES[] = [VESSEL, WORKSPACE_VESSEL]

export const ROUTES_WITH_DEFAULT_WORKSPACE: ROUTE_TYPES[] = [MAP, USER, SEARCH]

export const ALL_WORKSPACE_ROUTES: ROUTE_TYPES[] = [
  ...WORKSPACE_ROUTES,
  ...REPORT_ROUTES,
  WORKSPACE_VESSEL,
  WORKSPACE_SEARCH,
  VESSEL_GROUP_REPORT,
  PORT_REPORT,
]

export const ROUTES_WITH_WORKSPACES: ROUTE_TYPES[] = [
  MAP,
  WORKSPACE,
  WORKSPACE_SEARCH,
  WORKSPACE_VESSEL,
  REPORT,
  WORKSPACE_REPORT,
  VESSEL_GROUP_REPORT,
  PORT_REPORT,
]

export const SAVE_WORKSPACE_BEFORE_LEAVE_KEY = 'SAVE_WORKSPACE_BEFORE_LEAVE'
