import { getUTCDate, stickToClosestInterval } from '@globalfishingwatch/data-transforms'
import {
  getDatasetFilterItem,
  getDatasetFiltersAllowed,
} from '@globalfishingwatch/datasets-client/datasets.filters'
import type { BaseUrlWorkspace } from '@globalfishingwatch/dataviews-client'
import { stringifyWorkspace } from '@globalfishingwatch/dataviews-client'
import {
  EEZ_DATAVIEW_INSTANCE_ID,
  FAO_AREAS_DATAVIEW_INSTANCE_ID,
  FISHING_AIS_DATAVIEW_SLUG,
  LAYER_LIBRARY_ID_SEPARATOR,
  MPA_DATAVIEW_INSTANCE_ID,
  RFMO_DATAVIEW_INSTANCE_ID,
} from '@platform/config'

import datasetFilters from './references/dataset-filters.json'
import { resolveDataviewSlug } from './config'
import { getLayerInfo } from './dictionary'
import type { MapRoute, RouteNavigation } from './routes'
import { buildRoutePath, DEFAULT_BASENAME, getRouteNavigation } from './routes'

// Layer-library instances (id convention `<libraryId>__<unique>`) require a dataviewId;
// fill it from the dictionary when missing so agents don't have to know slugs
const withDataviewId = (instance: any) => {
  if (instance?.dataviewId) {
    return { ...instance, dataviewId: resolveDataviewSlug(String(instance.dataviewId)) }
  }
  if (instance?.id?.includes(LAYER_LIBRARY_ID_SEPARATOR)) {
    const { dataviewId } = getLayerInfo(instance.id)
    if (dataviewId) {
      return { ...instance, dataviewId }
    }
  }
  return instance
}

// Snaps start/end to the fourwings interval resolution the app will render with
// (month boundaries for ~year ranges, day for short ranges) — same functions the map uses
const withSnappedTimeRange = (state: MapState): MapState => {
  const start = typeof state.start === 'string' ? state.start : ''
  const end = typeof state.end === 'string' ? state.end : ''
  if (!Number.isFinite(Date.parse(start)) || !Number.isFinite(Date.parse(end))) {
    return state
  }
  const { start: newStart, end: newEnd } = stickToClosestInterval({ start, end })
  return {
    ...state,
    start: getUTCDate(newStart).toISOString(),
    end: getUTCDate(newEnd).toISOString(),
  }
}

// Area report datasets → the context layer instance that renders the area outline.
// Injected automatically so agents can't forget the boundary layer.
const AREA_DATASET_CONTEXT_LAYER: Record<string, string> = {
  'public-eez-areas': EEZ_DATAVIEW_INSTANCE_ID,
  'public-fao-major': FAO_AREAS_DATAVIEW_INSTANCE_ID,
  'public-rfmo': RFMO_DATAVIEW_INSTANCE_ID,
  'public-mpa-all': MPA_DATAVIEW_INSTANCE_ID,
}

const withReportContextLayers = (state: MapState, route: MapRoute): MapState => {
  if (route.type !== 'report' || !route.datasetId) {
    return state
  }
  const instances = (state.dataviewInstances as any[]) || []
  // Presence is checked by resolved dataview, not instance id: the boundary may already
  // render through a layer-library instance (e.g. `fao-major__<ts>` vs `context-layer-fao-areas`)
  const presentDataviews = new Set(
    instances.map((instance) => getLayerInfo(String(instance?.id ?? '')).dataviewId)
  )
  const missing = [...new Set(route.datasetId.split(','))]
    .map((datasetId) => AREA_DATASET_CONTEXT_LAYER[datasetId.trim()])
    .filter((id) => id && !presentDataviews.has(getLayerInfo(id).dataviewId))
  if (!missing.length) {
    return state
  }
  return {
    ...state,
    dataviewInstances: [...instances, ...missing.map((id) => ({ id, config: { visible: true } }))],
  }
}

// URL filters replace the dataview's own defaults, so an AIS apparent-fishing-effort
// layer that sets any filter must also carry the app default distance_from_port_km=3
// (filters out anchored vessels). Filterless instances keep the server-side default.
const withAisDefaultFilters = (state: MapState): MapState => {
  if (!state.dataviewInstances) {
    return state
  }
  return {
    ...state,
    dataviewInstances: (state.dataviewInstances as any[]).map((instance) => {
      if (!instance?.id) return instance
      const { dataviewId } = getLayerInfo(String(instance.id))
      if (dataviewId !== FISHING_AIS_DATAVIEW_SLUG) return instance
      const filters = instance.config?.filters
      if (!filters || !Object.keys(filters).length || 'distance_from_port_km' in filters) {
        return instance
      }
      return {
        ...instance,
        config: { ...instance.config, filters: { ...filters, distance_from_port_km: '3' } },
      }
    }),
  }
}

type DatasetSchema = Parameters<typeof getDatasetFilterItem>[0]
type FilterId = Parameters<typeof getDatasetFilterItem>[1]

// Generated by `pnpm nx sync-dataset-filters skills` — never edit by hand
const DATASET_FILTERS = datasetFilters as unknown as {
  dataviews: Record<string, string[]>
  datasets: Record<string, DatasetSchema>
}
// Same categories scripts/sync-dataset-filters.mjs fetches
const CHECKED_CATEGORIES = ['activity', 'detections', 'events']

const toValues = (value: unknown): string[] =>
  (Array.isArray(value) ? value : [value]).filter((v) => v !== undefined && v !== '').map(String)

// Filter ids of `filters` the dataset can't apply: filter not enabled, or a value outside its enum
const getUnsupportedFilters = (dataset: DatasetSchema, filters: Record<string, string[]>) => {
  const allowed = getDatasetFiltersAllowed(dataset)
  return Object.keys(filters).filter((id) => {
    if (!allowed.includes(id)) return true
    const item = getDatasetFilterItem(dataset, id as FilterId)
    if (!item?.enum?.length || item.type === 'range') return false
    const values = item.enum.map(String)
    return filters[id].some((value) => !values.includes(value))
  })
}

const describeSupport = (datasetId: string, filters: Record<string, string[]>) => {
  const dataset = DATASET_FILTERS.datasets[datasetId]
  const support = Object.keys(filters).map((id) => {
    if (!getDatasetFiltersAllowed(dataset).includes(id)) return `${id}: not supported`
    const values = getDatasetFilterItem(dataset, id as FilterId)?.enum
    return values?.length ? `${id}: ${values.filter((v) => v !== '').join(' | ')}` : `${id}: any`
  })
  return `  - ${datasetId} → ${support.join('; ')}`
}

// Mirrors the app filter UI (isDataviewFilterSupported / getCommonFiltersInDataview): a filter
// applies to a layer only when EVERY active dataset supports it with the selected values, and
// the app never strips a URL filter that doesn't. So narrow `config.datasets` to the datasets
// that support the filters (what a user does with the source selector), or fail when none do
// or the agent pinned `config.datasets` itself. Datasets missing from dataset-filters.json
// (released after the last sync) are kept unchecked with a warning — a stale file never blocks.
const withCompatibleFilters = (state: MapState, warnings: string[]): MapState => {
  if (!state.dataviewInstances) {
    return state
  }
  return {
    ...state,
    dataviewInstances: (state.dataviewInstances as any[]).map((instance) => {
      if (!instance?.id) return instance
      const filters = Object.fromEntries(
        Object.entries(instance.config?.filters || {})
          .map(([id, value]) => [id, toValues(value)] as const)
          .filter(([, values]) => values.length)
      )
      if (!Object.keys(filters).length) return instance
      const layer = getLayerInfo(String(instance.id))
      const dataviewId = instance.dataviewId
        ? resolveDataviewSlug(String(instance.dataviewId))
        : layer.dataviewId
      const explicitDatasets: string[] | undefined = instance.config?.datasets?.length
        ? instance.config.datasets
        : undefined
      const activeDatasets =
        explicitDatasets || (dataviewId && DATASET_FILTERS.dataviews[dataviewId])
      if (!activeDatasets) {
        if (CHECKED_CATEGORIES.includes(layer.category)) {
          warnings.push(
            `Layer "${instance.id}": dataview ${dataviewId} not in dataset-filters.json, filters not checked`
          )
        }
        return instance
      }
      const unknown = activeDatasets.filter((id) => !DATASET_FILTERS.datasets[id])
      if (unknown.length) {
        warnings.push(
          `Layer "${instance.id}": ${unknown.join(', ')} not in dataset-filters.json, filters not checked for them`
        )
      }
      const unsupportedById = Object.fromEntries(
        activeDatasets
          .filter((id) => DATASET_FILTERS.datasets[id])
          .map((id) => [id, getUnsupportedFilters(DATASET_FILTERS.datasets[id], filters)])
      )
      const supporting = activeDatasets.filter((id) => !unsupportedById[id]?.length)
      if (supporting.length === activeDatasets.length) return instance
      const dropped = activeDatasets.filter((id) => !supporting.includes(id))
      const failing = Object.fromEntries(
        [...new Set(dropped.flatMap((id) => unsupportedById[id]))].map((id) => [id, filters[id]])
      )
      const failingLabel = Object.entries(failing)
        .map(([id, values]) => `${id}=${values.join(',')}`)
        .join(' ')
      if (!supporting.length || explicitDatasets) {
        throw new Error(
          [
            `Layer "${instance.id}": ${failingLabel} is not supported by ${
              supporting.length ? 'every dataset in config.datasets' : 'any of its datasets'
            }. A filter applies only when every active dataset supports it with the selected values.`,
            'Per-dataset support:',
            ...dropped.map((id) => describeSupport(id, failing)),
            'Fix: drop or change the filter, set config.datasets to datasets that support it, or use one instance per dataset.',
          ].join('\n')
        )
      }
      warnings.push(
        `Layer "${instance.id}": ${failingLabel} is only supported by ${supporting.join(', ')}; config.datasets narrowed to them, ${dropped.length} other datasets dropped`
      )
      return { ...instance, config: { ...instance.config, datasets: supporting } }
    }),
  }
}

export type MapState = BaseUrlWorkspace & Record<string, unknown>

export type EncodeMapUrlInput = {
  route: MapRoute
  state?: MapState
  /** App basename prepended to `path`, defaults to '/platform' */
  basename?: string
}

export type EncodeMapUrlResult = {
  /** TanStack Router navigation config to navigate from inside the map app */
  navigation: RouteNavigation & { search: MapState }
  /** Path + encoded query. External navigation = prepend origin (https://globalfishingwatch.org) */
  path: string
  /** Automatic changes the user should hear about (e.g. layer sources narrowed by a filter) */
  warnings?: string[]
}

export const encodeMapUrl = ({
  route,
  state = {},
  basename = DEFAULT_BASENAME,
}: EncodeMapUrlInput): EncodeMapUrlResult => {
  const navigation = getRouteNavigation(route)
  state = withSnappedTimeRange(state)
  state = withReportContextLayers(state, route)
  state = withAisDefaultFilters(state)
  const warnings: string[] = []
  state = withCompatibleFilters(state, warnings)
  if (state.dataviewInstances) {
    state = {
      ...state,
      dataviewInstances: state.dataviewInstances.map(withDataviewId),
    }
  }
  const query = stringifyWorkspace(state)
  const path = `${basename}${buildRoutePath(navigation)}${query ? `?${query}` : ''}`
  return {
    navigation: { ...navigation, search: state },
    path,
    ...(warnings.length && { warnings }),
  }
}
