version: '3.9'
services:
  data-explorer:
    build:
      context: ../../dist/apps/fourwings-explorer
      dockerfile: ../../../apps/fourwings-explorer/Dockerfile
      target: production
    container_name: data-explorer
    ports:
      - 3000:80
    env_file:
      - .env
    environment:
      - PORT=80
      - BASIC_AUTH=off
