steps:
  # Push production image to GCR
  - name: 'gcr.io/kaniko-project/executor:latest'
    id: 'build production image'
    args:
      [
        '--destination=gcr.io/world-fishing-827/github.com/globalfishingwatch/carrier-portal:$COMMIT_SHA',
        '--cache=true',
        '--build-arg',
        'REACT_APP_DEPLOYED_VERSION=${_APP_VERSION}_$SHORT_SHA',
        '--build-arg',
        'REACT_APP_API_GATEWAY=$_REACT_APP_API_GATEWAY',
        '--build-arg',
        'REACT_APP_GEAR_TYPE_READY=$_REACT_APP_GEAR_TYPE_READY',
        '--build-arg',
        'REACT_APP_VESSEL_WIDTH_READY=$_REACT_APP_VESSEL_WIDTH_READY',
        '--build-arg',
        'REACT_APP_TRACK_INSPECTOR_URL=$_REACT_APP_TRACK_INSPECTOR_URL',
        '--build-arg',
        'REACT_APP_DATA_DOWNLOAD_URL=$_REACT_APP_DATA_DOWNLOAD_URL',
        '--build-arg',
        'REACT_APP_DATASET_ID=$_REACT_APP_DATASET_ID',
        '--build-arg',
        'BASIC_AUTH_USER=$_BASIC_AUTH_USER',
        '--build-arg',
        'BASIC_AUTH_PASS=$_BASIC_AUTH_PASS',
        '-c',
        '.',
      ]

  # Deploy to the appropriate environment
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'deploy instance to gcloud'
    entrypoint: 'bash'
    args:
      - '-eEuo'
      - 'pipefail'
      - '-c'
      - |-
        gcloud beta run deploy \
        carrier-portal-`echo $BRANCH_NAME | sed -r 's,/,-,g' | awk '{print tolower($0)}'` \
        --project $_RUN_PROJECT \
        --image gcr.io/world-fishing-827/github.com/globalfishingwatch/carrier-portal:$COMMIT_SHA \
        --region $_RUN_REGION \
        --platform managed \
        --set-env-vars BASIC_AUTH=$_BASIC_AUTH \
        --allow-unauthenticated
substitutions:
  _APP_VERSION: 0.12.0-beta

timeout: 1200s
