steps:
  # Push production image to GCR
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '--build-arg',
        'REACT_APP_DEPLOYED_VERSION=$SHORT_SHA',
        '--build-arg',
        'REACT_APP_API_GATEWAY=$_REACT_APP_API_GATEWAY',
        '--build-arg',
        'REACT_APP_TRACK_INSPECTOR_URL=$_REACT_APP_TRACK_INSPECTOR_URL',
        '--build-arg',
        'REACT_APP_DATASET_ID=$_REACT_APP_DATASET_ID',
        '--target',
        'build',
        '-t',
        'gcr.io/world-fishing-827/github.com/globalfishingwatch/carrier-portal:$COMMIT_SHA',
        '.',
      ]

  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'run',
        'gcr.io/world-fishing-827/github.com/globalfishingwatch/carrier-portal:$COMMIT_SHA',
        'npm',
        'test',
      ]
