import type { DatasetSubCategory, EventType } from '@globalfishingwatch/api-types'
import { DataviewCategory } from '@globalfishingwatch/api-types'

import type {
  REPORT_ACTIVITY_GRAPH_BEFORE_AFTER,
  REPORT_ACTIVITY_GRAPH_DATASET_COMPARISON,
  REPORT_ACTIVITY_GRAPH_EVOLUTION,
  REPORT_ACTIVITY_GRAPH_PERIOD_COMPARISON,
  REPORT_EVENTS_GRAPH_EVOLUTION,
  REPORT_EVENTS_GRAPH_GROUP_BY_EEZ,
  REPORT_EVENTS_GRAPH_GROUP_BY_FAO,
  REPORT_EVENTS_GRAPH_GROUP_BY_FLAG,
  REPORT_EVENTS_GRAPH_GROUP_BY_RFMO,
  REPORT_VESSELS_GRAPH_FLAG,
  REPORT_VESSELS_GRAPH_GEARTYPE,
  REPORT_VESSELS_GRAPH_VESSELTYPE,
} from 'features/_reports/reports.config'
import type { Bbox, BufferOperation, BufferUnit } from 'types'

// REPORT CATEGORY
export enum ReportCategory {
  Activity = DataviewCategory.Activity,
  Detections = DataviewCategory.Detections,
  Environment = DataviewCategory.Environment,
  Events = DataviewCategory.Events,
  Others = 'others',
  VesselGroup = 'vessel-groups',
  VesselGroupInsights = 'vessel-groups-insights',
}
export type ReportCategoryState = {
  /** Top-level report category shown (see ReportCategory for the list of available categories) */
  reportCategory: `${ReportCategory}` | undefined
}

export const categoryToDataviewMap: Partial<Record<ReportCategory, DataviewCategory>> = {
  [ReportCategory.Activity]: DataviewCategory.Activity,
  [ReportCategory.Detections]: DataviewCategory.Detections,
  [ReportCategory.Events]: DataviewCategory.Events,
  [ReportCategory.VesselGroup]: DataviewCategory.VesselGroups,
  [ReportCategory.Others]: DataviewCategory.Context,
  [ReportCategory.Environment]: DataviewCategory.Environment,
}

// REPORT SUBCATEGORIES
export type ReportActivitySubCategory =
  | `${DatasetSubCategory.Fishing}`
  | `${DatasetSubCategory.Presence}`
export type ReportDetectionsSubCategory =
  | `${DatasetSubCategory.Sar}`
  | `${DatasetSubCategory.Viirs}`
  | `${DatasetSubCategory.Sentinel2}`
export type ReportEventsSubCategory = EventType
export type ReportVesselsSubCategory = ReportVesselGraph | 'source' | 'coverage'

export type AnyReportSubCategory =
  | ReportActivitySubCategory
  | ReportDetectionsSubCategory
  | ReportEventsSubCategory
  | ReportVesselsSubCategory

export type ReportSubcategoryState = {
  /** Activity sub-category filter applied within an activity report, see ReportActivitySubCategory */
  reportActivitySubCategory: ReportActivitySubCategory | undefined
  /** Detections sub-category filter applied within a detections report, see ReportDetectionsSubCategory */
  reportDetectionsSubCategory: ReportDetectionsSubCategory | undefined
  /** Event type filter applied within an events report */
  reportEventsSubCategory: ReportEventsSubCategory | undefined
  /** Sub-tab (graph/source/coverage) selected within a vessels report */
  reportVesselsSubCategory: ReportVesselsSubCategory | undefined
}

// AREA REPORT
export type AreaReportState = {
  /** Bounding box of the area a report is generated for automatically generated by the app when loaded
   * just used for better UX to load the page in the report area
   * */
  reportAreaBounds: Bbox | undefined
  /** Distance used to buffer the report area (paired with reportBufferUnit) */
  reportBufferValue: number | undefined
  /** Unit for reportBufferValue (paired with reportBufferValue) */
  reportBufferUnit: BufferUnit
  /** How the buffer is applied to the area geometry (dissolve into it, or subtract/difference) */
  reportBufferOperation: BufferOperation
}

// PORT REPORT
export type PortsReportState = {
  /** Name of the port in its report, used to display the port name in the report before it finishes loading*/
  portsReportName: string | undefined
  /** ISO3 flag code of the port in its report */
  portsReportCountry: string | undefined
  /** Dataset id of the port belongs to, used to resolve the port in a ports report */
  portsReportDatasetId: string | undefined
}

// REPORT VESSELS
export const REPORT_VESSEL_ORDER_PROPERTIES = ['shipname', 'flag', 'shiptype'] as const
export type ReportVesselOrderProperty = (typeof REPORT_VESSEL_ORDER_PROPERTIES)[number]
export const REPORT_VESSEL_ORDER_DIRECTIONS = ['asc', 'desc'] as const
export type ReportVesselOrderDirection = (typeof REPORT_VESSEL_ORDER_DIRECTIONS)[number]
export type ReportVesselGraph =
  | typeof REPORT_VESSELS_GRAPH_GEARTYPE
  | typeof REPORT_VESSELS_GRAPH_VESSELTYPE
  | typeof REPORT_VESSELS_GRAPH_FLAG

/** Vessels tab state: filter, sort and pagination for the vessels list shown in a report.
 * Default values for each field below are set in DEFAULT_REPORT_STATE (features/_reports/reports.config.ts) */
export type ReportVesselsState = {
  /** Free-text filter applied to the vessels list in a report:
   * - Use commas to search by multiple fields
   * - Use '|' to include one query or another
   * - Use '-' before a search term to exclude vessels
   * e.g. \"flag:china, gear:trawlers\", \"-spain\", \"cargo|passenger\"...
   */
  reportVesselFilter: string | undefined
  /** Which vessel graph is used in the report */
  reportVesselGraph: ReportVesselsSubCategory
  /** Current page in the paginated vessels list */
  reportVesselPage: number
  /** Page size for the paginated vessels list
   * @minimum 10
   * @maximum 50
   */
  reportVesselResultsPerPage: number
  /** Column the vessels list is sorted by */
  reportVesselOrderProperty: ReportVesselOrderProperty | undefined
  /** Sort direction for reportVesselOrderProperty */
  reportVesselOrderDirection: ReportVesselOrderDirection | undefined
}
// REPORT ACTIVITY
export type ReportActivityGraph =
  | typeof REPORT_ACTIVITY_GRAPH_EVOLUTION
  | typeof REPORT_ACTIVITY_GRAPH_BEFORE_AFTER
  | typeof REPORT_ACTIVITY_GRAPH_PERIOD_COMPARISON
  | typeof REPORT_ACTIVITY_GRAPH_DATASET_COMPARISON

// REPORT EVENTS
export type ReportEventsGraph =
  | typeof REPORT_EVENTS_GRAPH_EVOLUTION
  | typeof REPORT_EVENTS_GRAPH_GROUP_BY_FLAG
  | typeof REPORT_EVENTS_GRAPH_GROUP_BY_RFMO
  | typeof REPORT_EVENTS_GRAPH_GROUP_BY_FAO
  | typeof REPORT_EVENTS_GRAPH_GROUP_BY_EEZ

export type ReportActivityTimeComparison = {
  start: string
  compareStart: string
  duration: number
  durationType: 'days' | 'months'
}

export type ReportComparisonDataviews = {
  main: string
  compare: string | undefined
}

export type ReportActivityState = {
  /** Which chart is used for the activity report */
  reportActivityGraph: ReportActivityGraph
  /** Date ranges compared when reportActivityGraph is a before/after or period comparison */
  reportTimeComparison: ReportActivityTimeComparison | undefined
  /** Ids of the two dataviews compared when reportActivityGraph is a dataset comparison */
  reportComparisonDataviewIds: ReportComparisonDataviews | undefined
}

export type ReportEventsState = {
  /** Which chart is used for the events report */
  reportEventsGraph: ReportEventsGraph
  /** Free-text filter applied to the ports list in an events report (reportVesselFilter in the vessels tab) */
  reportEventsPortsFilter: string | undefined
  /** Current page in the paginated ports list of an events report (reportVesselPage in the vessels tab) */
  reportEventsPortsPage: number
  /** Page size for the paginated ports list of an events report (reportVesselResultsPerPage in the vessels tab) */
  reportEventsPortsResultsPerPage: number
}

export type ReportState = ReportCategoryState &
  ReportSubcategoryState &
  ReportVesselsState &
  ReportActivityState &
  ReportEventsState &
  AreaReportState &
  PortsReportState

export type ReportStateProperty = keyof ReportState
