api-portal:
  - changed-files:
      - any-glob-to-any-file: apps/api-portal/**/*
platform:
  - changed-files:
      - any-glob-to-any-file: apps/platform/**/*
image-labeler:
  - changed-files:
      - any-glob-to-any-file: apps/image-labeler/**/*
port-labeler:
  - changed-files:
      - any-glob-to-any-file: apps/port-labeler/**/*
track-labeler:
  - changed-files:
      - any-glob-to-any-file: apps/track-labeler/**/*
user-groups-admin:
  - changed-files:
      - any-glob-to-any-file: apps/user-groups-admin/**/*

api-client:
  - changed-files:
      - any-glob-to-any-file: libs/api-client/**/*
api-types:
  - changed-files:
      - any-glob-to-any-file: libs/api-types/**/*
data-transforms:
  - changed-files:
      - any-glob-to-any-file: libs/data-transforms/**/*
datasets-client:
  - changed-files:
      - any-glob-to-any-file: libs/datasets-client/**/*
dataviews-client:
  - changed-files:
      - any-glob-to-any-file: libs/dataviews-client/**/*
deck-layer-composer:
  - changed-files:
      - any-glob-to-any-file: libs/deck-layer-composer/**/*
deck-layers:
  - changed-files:
      - any-glob-to-any-file: libs/deck-layers/**/*
deck-loaders:
  - changed-files:
      - any-glob-to-any-file: libs/deck-loaders/**/*
i18n-labels:
  - changed-files:
      - any-glob-to-any-file: libs/i18n-labels/**/*
ocean-areas:
  - changed-files:
      - any-glob-to-any-file: libs/ocean-areas/**/*
react-hooks:
  - changed-files:
      - any-glob-to-any-file: libs/react-hooks/**/*
responsive-visualizations:
  - changed-files:
      - any-glob-to-any-file: libs/responsive-visualizations/**/*
timebar:
  - changed-files:
      - any-glob-to-any-file: libs/timebar/**/*
ui-components:
  - changed-files:
      - any-glob-to-any-file: ui-components/**/*
