const translations = 'used_to_get_dynamic_translations_autogenerated'

// t('feedback.roles.watch', 'Watch officer')
// t('feedback.roles.analyst', 'Analyst')
// t('feedback.roles.navy', 'Navy or coast guard')
// t('feedback.roles.fisheries', 'Fisheries enforcement or compliance officer')
// t('feedback.roles.ngo', 'Non-governmental organization')
// t('feedback.roles.scientist', 'Scientist')
// t('feedback.roles.journalist', 'Journalist')
// t('feedback.roles.student', 'Student')
// t('feedback.roles.general', 'General public')
// t('feedback.roles.GFW', 'Global Fishing Watch staff')
// t('feedback.roles.other', 'Other')

// t('feedback.features.activityLayers', 'Activity Layers')
// t('feedback.features.vesselTracks', 'Vessel Tracks')
// t('feedback.features.vesselSearch', 'Vessel Search')
// t('feedback.features.environmentLayers', 'Environment Layers')
// t('feedback.features.referenceLayers', 'Reference Layers')
// t('feedback.features.timebar', 'Time bar along the bottom of the map')
// t('feedback.features.analysis', 'Analysis')
// t('feedback.features.other', 'Other')

export default translations
