cacheFolder: .yarn/cache

compressionLevel: mixed

enableGlobalCache: false

nodeLinker: node-modules

supportedArchitectures:
  cpu:
    - x64
    - arm64
  os:
    - darwin
    - linux

yarnPath: .yarn/releases/yarn-4.6.0.cjs
