cacheFolder: .yarn/cache

nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

supportedArchitectures:
  os:
    - current
    - darwin
    - linux

yarnPath: .yarn/releases/yarn-3.6.1.cjs
