steps:
  - name: gcr.io/cloud-builders/git
    args: ['fetch', '--unshallow', '--no-tags']

steps:
  - name: 'gcr.io/$PROJECT_ID/restore_cache'
    id: restore_cache
    waitFor: ['-']
    script: |
      #!/usr/bin/env bash
      restore_cache \
        --bucket=gs://frontend-cache-dependencies \
        --key=node_modules-$( checksum yarn.lock )
      restore_cache \
        --bucket=gs://frontend-cache-dependencies \
        --key=yarn-$( checksum yarn.lock )
      restore_cache \
        --bucket=gs://frontend-cache-dependencies \
        --key=yarn-install-state-$( checksum yarn.lock )

  - id: 'install-yarn'
    waitFor: ['restore_cache']
    name: node:21
    script: |
      yarn set version 4.1.1
      yarn -v
      CYPRESS_CACHE_FOLDER=.cypress-cache yarn install --immutable

  - id: 'generate-cypress-lock'
    waitFor: ['install-yarn']
    name: node:21
    script: |
      yarn info cypress version > cypress.lock

  - id: 'save_cache'
    waitFor: ['install-yarn']
    name: 'gcr.io/$PROJECT_ID/restore_cache'
    script: |
      #!/usr/bin/env bash
      save_cache \
        --bucket=gs://frontend-cache-dependencies \
        --key=node_modules-$( checksum yarn.lock ) \
        --path=./node_modules \
        --no-clobber
      save_cache \
        --bucket=gs://frontend-cache-dependencies \
        --key=yarn-$( checksum yarn.lock ) \
        --path=.yarn/cache \
        --no-clobber
      save_cache \
        --bucket=gs://frontend-cache-dependencies \
        --key=yarn-install-state-$( checksum yarn.lock ) \
        --path=.yarn/install-state.gz \
        --no-clobber
      save_cache \
        --bucket=gs://frontend-cache-dependencies \
        --key=cypress-$( checksum cypress.lock ) \
        --path=.cypress-cache \
        --no-clobber

  - id: get-affected
    name: 'node:21'
    entrypoint: yarn
    args: ['affected']

  # Trigger the affected apps builds
  - name: gcr.io/cloud-builders/gcloud
    waitFor: ['get-affected']
    id: deploy-cloud-run
    entrypoint: bash
    args:
      - '-eEuo'
      - 'pipefail'
      - '-c'
      - |-
        AFFECTED_APPS=(`cat affected-apps.txt`)
        for i in ${AFFECTED_APPS[@]//,/}; do
          [ ! -z "$i" ] && gcloud -q beta builds triggers run --branch=develop ui-${i}-develop
        done
