steps:
  - id: install-nx
    name: node:14
    entrypoint: bash
    args:
      - '-eEuo'
      - 'pipefail'
      - '-c'
      - |-
        yarn global add nx || exit 0
        nx affected:apps --plain > affected-apps.txt || exit 0
        echo affected-apps.txt || exit 0

  # Trigger the affected apps builds
  - name: gcr.io/cloud-builders/gcloud
    waitFor: ['install-nx']
    id: deploy-cloud-run
    entrypoint: bash
    args:
      - '-eEuo'
      - 'pipefail'
      - '-c'
      - |-
        AFFECTED_APPS=(`cat affected-apps.txt`)
        for i in ${AFFECTED_APPS[@]}; do
          if [[$i]]; then
            gcloud -q beta builds triggers run --branch=develop ui-${i}-develop
          fi
        done
