files:
  - source: apps/fishing-map/public/locales/source
    translation: /apps/fishing-map/public/locales/%two_letters_code%/%original_file_name%
  - source: libs/i18n-labels/source
    translation: libs/i18n-labels/source/%two_letters_code%/%original_file_name%
