files:
  - source: apps/fishing-map/public/locales/source
    translation: >-
      /apps/fishing-map/public/locales/%two_letters_code%/%original_file_name%
  - source: apps/vessel-history/public/locales/source
    translation: >-
      /apps/vessel-history/public/locales/%two_letters_code%/%original_file_name%
  - source: libs/ocean-areas/src/data/locales/source.json
    translation: /libs/ocean-areas/src/data/locales/%two_letters_code%.json
  - source: libs/i18n-labels/source
    translation: /libs/i18n-labels/%two_letters_code%/%original_file_name%
