files:
  - source: /applications/amathea/public/locales
    translation: >-
      /applications/amathea/public/locales/%two_letters_code%/%original_file_name%
  - source: applications/fishing-map/public/locales/source
    translation: >-
      /applications/fishing-map/public/locales/%two_letters_code%/%original_file_name%
