services:
  data-download-portal:
    build:
      dockerfile: apps/data-download-portal/Dockerfile
      target: production
      args:
        API_GATEWAY: ${API_GATEWAY:-https://gateway.api.dev.globalfishingwatch.org}
    container_name: data-download-portal
    ports:
      - 3000:80
    environment:
      - PORT=80
      - BASIC_AUTH=off

  user-groups-admin:
    build:
      dockerfile: apps/user-groups-admin/Dockerfile
      target: production
      args:
        API_GATEWAY: ${API_GATEWAY:-https://gateway.api.dev.globalfishingwatch.org}
    container_name: user-groups-admin
    ports:
      - 3001:80
    environment:
      - PORT=80
      - BASIC_AUTH=off

  image-labeler:
    build:
      dockerfile: apps/image-labeler/Dockerfile
      target: production
      args:
        API_GATEWAY: ${API_GATEWAY:-https://gateway.api.dev.globalfishingwatch.org}
    container_name: image-labeler
    ports:
      - 3002:80
    environment:
      - PORT=80
      - BASIC_AUTH=off

  track-labeler:
    build:
      dockerfile: apps/track-labeler/Dockerfile
      target: production
      args:
        API_GATEWAY: ${API_GATEWAY:-https://gateway.api.dev.globalfishingwatch.org}
    container_name: track-labeler
    ports:
      - 3003:80
    environment:
      - PORT=80
      - BASIC_AUTH=off

  map:
    build:
      context: ./dist/apps/fishing-map
      dockerfile: ../../../apps/fishing-map/Dockerfile
    container_name: map
    expose:
      - '80'
    volumes:
      - ./dist/apps/fishing-map/exported:/usr/share/nginx/www
    env_file:
      - apps/fishing-map/.build.env
    environment:
      - NEXT_PUBLIC_WORKSPACE_ENV=development
      - NEXT_PUBLIC_API_GATEWAY=https://gateway.api.dev.globalfishingwatch.org/
      - PORT=80
      - BASIC_AUTH=off

  api-portal:
    build:
      context: ./dist/apps/api-portal
      dockerfile: ../../../apps/api-portal/Dockerfile
    container_name: api-portal
    expose:
      - '80'
    ports:
      - '3004:80'
    volumes:
      - ./dist/apps/api-portal/.next:/app/.next
      - ./dist/apps/api-portal/exported:/app/exported
      - ./dist/apps/api-portal/public:/app/public
    env_file:
      - apps/api-portal/.build.env
    environment:
      - PORT=80
