packages:
  # include packages in subfolders (e.g. apps/ and packages/)
  - "linting"
  - "apps/fishing-map"
  # if required, exclude some directories
  # - '!**/test/**'

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@swc/core'
  - core-js
  - cypress
  - esbuild
  - nx
  - protobufjs
  - sharp
