packages:
  - 'linting'
  - 'apps/fishing-map'

allowBuilds:
  '@parcel/watcher': true
  '@sentry/cli': true
  '@swc/core': true
  core-js: true
  esbuild: true
  less: true
  nx: true
  protobufjs: true
  sharp: true
  unrs-resolver: true

patchedDependencies:
  '@tanstack/start-server-core@1.167.30': patches/@tanstack__start-server-core@1.167.30.patch
