steps:
  - name: 'gcr.io/$PROJECT_ID/restore_cache'
    id: restore_cache
    waitFor: ['-']
    args:
      - '--bucket=gs://frontend-cache-dependencies'
      - '--key=yarn-$( checksum yarn.lock )'

  - id: 'install-yarn'
    waitFor: ['restore_cache']
    name: gcr.io/cloud-builders/yarn:latest
    entrypoint: bash
    args:
      - '-c'
      # if dependencies cache is not found then install all deps
      - |
        if [ ! -d "node_modules" ]; then
          yarn install --immutable
        fi

  - id: 'save_cache'
    waitFor: ['install-yarn']
    name: 'gcr.io/$PROJECT_ID/save_cache'
    args:
      - '--bucket=gs://frontend-cache-dependencies'
      - '--key=yarn-$( checksum yarn.lock )'
      - '--path=./node_modules'
      - '--no-clobber'

  - id: 'build-app'
    waitFor: ['install-yarn']
    name: gcr.io/cloud-builders/yarn:latest
    entrypoint: yarn
    args: ['nx', 'build', 'tile-inspector', '--parallel']
    env:
      - 'NX_BRANCH=$_NX_BRANCH'
      - 'NX_CLOUD_AUTH_TOKEN=$_NX_CLOUD_AUTH_TOKEN'
      - 'NEXT_PUBLIC_API_GATEWAY=$_NEXT_PUBLIC_API_GATEWAY'

  - id: 'docker-prepare'
    waitFor: ['build-app']
    name: node:18-alpine
    entrypoint: yarn
    args: ['nx', 'docker-prepare', 'tile-inspector']

  - name: 'gcr.io/kaniko-project/executor:v1.6.0'
    id: 'build-image'
    waitFor: ['docker-prepare']
    args:
      [
        '--destination=gcr.io/world-fishing-827/github.com/globalfishingwatch/tile-inspector:$COMMIT_SHA',
        '--cache=true',
        '--build-arg',
        'BASIC_AUTH_USER=$_BASIC_AUTH_USER',
        '--build-arg',
        'BASIC_AUTH_PASS=$_BASIC_AUTH_PASS',
        '--target',
        'production',
        '-f',
        './apps/tile-inspector/Dockerfile',
        '-c',
        './dist/apps/tile-inspector',
      ]

  # Deploy to the appropriate environment
  - name: 'gcr.io/cloud-builders/gcloud'
    waitFor: ['build-image']
    id: 'deploy-cloud-run'
    entrypoint: 'bash'
    env:
      - '_RUN_SERVICE_NAME=$_RUN_SERVICE_NAME'
    args:
      - '-eEuo'
      - 'pipefail'
      - '-c'
      - |-
        branch_service_name=`echo tile-inspector-$BRANCH_NAME | sed -r 's,[/\.],-,g' | awk '{print substr(tolower($0),0,62)}'`
        service_name=${_RUN_SERVICE_NAME:-${branch_service_name}}
        gcloud beta run deploy \
        $service_name \
        --project \
        $_RUN_PROJECT \
        --image \
        gcr.io/world-fishing-827/github.com/globalfishingwatch/tile-inspector:$COMMIT_SHA \
        --region \
        $_RUN_REGION \
        --platform managed \
        --set-env-vars \
        BASIC_AUTH=$_BASIC_AUTH \
        --allow-unauthenticated

timeout: 1800s
options:
  machineType: 'E2_HIGHCPU_8'
