steps:
  - name: 'gcr.io/$PROJECT_ID/restore_cache'
    id: restore_cache
    waitFor: ['-']
    script: |
      #!/usr/bin/env bash
      restore_cache \
        --bucket=gs://frontend-cache-dependencies \
        --key=node_modules-$( checksum yarn.lock )
      restore_cache \
        --bucket=gs://frontend-cache-dependencies \
        --key=yarn-$( checksum yarn.lock )
      restore_cache \
        --bucket=gs://frontend-cache-dependencies \
        --key=yarn-install-state-$( checksum yarn.lock )

  - id: 'install-yarn'
    waitFor: ['restore_cache']
    name: node:21
    script: |
      yarn set version 4.6.0
      yarn -v
      yarn install --immutable

  - id: 'save_cache'
    waitFor: ['install-yarn']
    name: 'gcr.io/$PROJECT_ID/restore_cache'
    script: |
      #!/usr/bin/env bash
      save_cache \
        --bucket=gs://frontend-cache-dependencies \
        --key=node_modules-$( checksum yarn.lock ) \
        --path=./node_modules \
        --no-clobber
      save_cache \
        --bucket=gs://frontend-cache-dependencies \
        --key=yarn-$( checksum yarn.lock ) \
        --path=.yarn/cache \
        --no-clobber
      save_cache \
        --bucket=gs://frontend-cache-dependencies \
        --key=yarn-install-state-$( checksum yarn.lock ) \
        --path=.yarn/install-state.gz \
        --no-clobber

  - id: 'build-app'
    waitFor: ['install-yarn']
    name: node:21
    env:
      - 'COMMIT_SHA=$COMMIT_SHA'
      - 'NX_BRANCH=$_NX_BRANCH'
      - 'NX_CLOUD_AUTH_TOKEN=$_NX_CLOUD_AUTH_TOKEN'
      - 'NEXT_PUBLIC_API_GATEWAY=$_NEXT_PUBLIC_API_GATEWAY'
      - 'NEXT_PUBLIC_GOOGLE_MEASUREMENT_ID=$_NEXT_PUBLIC_GOOGLE_MEASUREMENT_ID'
      - 'NEXT_PUBLIC_GOOGLE_TAG_MANAGER_ID=$_NEXT_PUBLIC_GOOGLE_TAG_MANAGER_ID'
      - 'NEXT_PUBLIC_URL=$_NEXT_PUBLIC_URL'
    script: |
      yarn -v
      yarn nx run api-portal:build --parallel

      raw_tag="$COMMIT_SHA;$NEXT_PUBLIC_API_GATEWAY;$NEXT_PUBLIC_GOOGLE_MEASUREMENT_ID;$NEXT_PUBLIC_GOOGLE_TAG_MANAGER_ID;$NEXT_PUBLIC_URL"
      tag=`echo $raw_tag | sha256sum | cut -c1-64`
      echo $tag > image-tag
      echo Docker Image Tag: $tag

  - name: 'gcr.io/kaniko-project/executor:debug'
    id: 'build-image'
    waitFor: ['build-app']
    entrypoint: ''
    env:
      - 'REF_NAME=$REF_NAME'
      - 'SHORT_SHA=$SHORT_SHA'
    script: |
      image_version=`echo $REF_NAME | grep -Eo "(develop)" || echo $REF_NAME | grep -Eo "api-portal@([0-9].*)" | grep -Eo "([0-9].*)" || echo $SHORT_SHA`
      tag=`cat image-tag`
      /kaniko/executor \
        --destination=gcr.io/world-fishing-827/github.com/globalfishingwatch/api-portal:latest \
        --destination=gcr.io/world-fishing-827/github.com/globalfishingwatch/api-portal:$tag \
        --destination=gcr.io/world-fishing-827/github.com/globalfishingwatch/api-portal:$image_version \
        --cache=true \
        --build-arg \
          APP_NAME=api-portal \
        --target \
          production \
        -f \
          ./apps/api-portal/Dockerfile \
        -c \
          ./dist/apps/api-portal

  # Deploy to the appropriate environment
  - name: 'gcr.io/cloud-builders/gcloud'
    waitFor: ['build-image']
    id: 'deploy-cloud-run'
    entrypoint: 'bash'
    env:
      - '_RUN_SERVICE_NAME=$_RUN_SERVICE_NAME'
    args:
      - '-eEuo'
      - 'pipefail'
      - '-c'
      - |-
        tag=`cat image-tag`
        branch_service_name=`echo api-portal-$BRANCH_NAME | sed -r 's,[/\.],-,g' | awk '{print substr(tolower($0),0,62)}'`
        service_name=${_RUN_SERVICE_NAME:-${branch_service_name}}
        gcloud beta run deploy \
        $service_name \
        --project \
        $_RUN_PROJECT \
        --image \
        gcr.io/world-fishing-827/github.com/globalfishingwatch/api-portal:$tag \
        --region \
        $_RUN_REGION \
        --platform managed \
        --set-env-vars \
        BASIC_AUTH=$_BASIC_AUTH \
        --set-env-vars \
        BASIC_AUTH_USER=$_BASIC_AUTH_USER \
        --set-env-vars \
        BASIC_AUTH_PASS=$_BASIC_AUTH_PASS \
        --allow-unauthenticated

timeout: 1800s
options:
  machineType: 'E2_HIGHCPU_8'
