// Taken from gfw_research.psma_signatories_v20210212
// TODO: load it from the API when the endpoint is finished
const psma = [
  {
    country: 'Albania',
    iso3: 'ALB',
    signature: null,
    ratification: null,
    acceptance: null,
    approval: null,
    accession: '2017-04-07',
  },
  {
    country: 'Bahamas',
    iso3: 'BHS',
    signature: null,
    ratification: null,
    acceptance: null,
    approval: null,
    accession: '2016-10-07',
  },
  {
    country: 'Barbados',
    iso3: 'BRB',
    signature: null,
    ratification: null,
    acceptance: null,
    approval: null,
    accession: '2016-02-02',
  },
  {
    country: 'Cabo Verde',
    iso3: 'CPV',
    signature: null,
    ratification: null,
    acceptance: null,
    approval: null,
    accession: '2016-06-23',
  },
  {
    country: 'Cambodia',
    iso3: 'KHM',
    signature: null,
    ratification: null,
    acceptance: null,
    approval: null,
    accession: '2019-12-06',
  },
  {
    country: 'Costa Rica',
    iso3: 'CRI',
    signature: null,
    ratification: null,
    acceptance: null,
    approval: null,
    accession: '2015-12-04',
  },
  {
    country: 'Cuba',
    iso3: 'CUB',
    signature: null,
    ratification: null,
    acceptance: null,
    approval: null,
    accession: '2016-03-25',
  },
  {
    country: 'Denmark',
    iso3: 'DNK',
    signature: null,
    ratification: null,
    acceptance: null,
    approval: null,
    accession: '2017-11-28',
  },
  {
    country: 'Djibouti',
    iso3: 'DJI',
    signature: null,
    ratification: null,
    acceptance: null,
    approval: null,
    accession: '2017-11-27',
  },
  {
    country: 'Dominica',
    iso3: 'DMA',
    signature: null,
    ratification: null,
    acceptance: null,
    approval: null,
    accession: '2016-05-06',
  },
  {
    country: 'Ecuador',
    iso3: 'ECU',
    signature: null,
    ratification: null,
    acceptance: null,
    approval: null,
    accession: '2019-02-05',
  },
  {
    country: 'Faroe Islands',
    iso3: 'FRO',
    signature: null,
    ratification: null,
    acceptance: null,
    approval: null,
    accession: '2017-11-28',
  },
  {
    country: 'Fiji',
    iso3: 'FJI',
    signature: null,
    ratification: null,
    acceptance: null,
    approval: null,
    accession: '2019-02-13',
  },
  {
    country: 'Gambia',
    iso3: 'GMB',
    signature: null,
    ratification: null,
    acceptance: null,
    approval: null,
    accession: '2016-07-29',
  },
  {
    country: 'Greenland',
    iso3: 'GRL',
    signature: null,
    ratification: null,
    acceptance: null,
    approval: null,
    accession: '2017-11-28',
  },
  {
    country: 'Grenada',
    iso3: 'GRD',
    signature: null,
    ratification: null,
    acceptance: null,
    approval: null,
    accession: '2016-06-17',
  },
  {
    country: 'Guinea',
    iso3: 'GIN',
    signature: null,
    ratification: null,
    acceptance: null,
    approval: null,
    accession: '2016-06-03',
  },
  {
    country: 'Guyana',
    iso3: 'GUY',
    signature: null,
    ratification: null,
    acceptance: null,
    approval: null,
    accession: '2016-03-07',
  },
  {
    country: 'Japan',
    iso3: 'JPN',
    signature: null,
    ratification: null,
    acceptance: null,
    approval: null,
    accession: '2017-05-19',
  },
  {
    country: 'Liberia',
    iso3: 'LBR',
    signature: null,
    ratification: null,
    acceptance: null,
    approval: null,
    accession: '2019-05-21',
  },
  {
    country: 'Libya',
    iso3: 'LBY',
    signature: null,
    ratification: null,
    acceptance: null,
    approval: null,
    accession: '2018-11-05',
  },
  {
    country: 'Madagascar',
    iso3: 'MDG',
    signature: null,
    ratification: null,
    acceptance: null,
    approval: null,
    accession: '2017-03-27',
  },
  {
    country: 'Maldives',
    iso3: 'MDV',
    signature: null,
    ratification: null,
    acceptance: null,
    approval: null,
    accession: '2017-03-17',
  },
  {
    country: 'Mauritania',
    iso3: 'MRT',
    signature: null,
    ratification: null,
    acceptance: null,
    approval: null,
    accession: '2017-01-23',
  },
  {
    country: 'Mauritius',
    iso3: 'MUS',
    signature: null,
    ratification: null,
    acceptance: null,
    approval: null,
    accession: '2015-08-31',
  },
  {
    country: 'Montenegro',
    iso3: 'MNE',
    signature: null,
    ratification: null,
    acceptance: null,
    approval: null,
    accession: '2017-05-17',
  },
  {
    country: 'Myanmar',
    iso3: 'MMR',
    signature: null,
    ratification: null,
    acceptance: null,
    approval: null,
    accession: '2010-11-22',
  },
  {
    country: 'Namibia',
    iso3: 'NAM',
    signature: null,
    ratification: null,
    acceptance: null,
    approval: null,
    accession: '2017-07-18',
  },
  {
    country: 'Nicaragua',
    iso3: 'NIC',
    signature: null,
    ratification: null,
    acceptance: null,
    approval: null,
    accession: '2020-08-14',
  },
  {
    country: 'Oman',
    iso3: 'OMN',
    signature: null,
    ratification: null,
    acceptance: null,
    approval: null,
    accession: '2013-08-01',
  },
  {
    country: 'Palau',
    iso3: 'PLW',
    signature: null,
    ratification: null,
    acceptance: null,
    approval: null,
    accession: '2015-11-30',
  },
  {
    country: 'Panama',
    iso3: 'PAN',
    signature: null,
    ratification: null,
    acceptance: null,
    approval: null,
    accession: '2016-11-21',
  },
  {
    country: 'Philippines',
    iso3: 'PHL',
    signature: null,
    ratification: null,
    acceptance: null,
    approval: null,
    accession: '2018-04-26',
  },
  {
    country: 'Republic of Korea',
    iso3: 'KOR',
    signature: null,
    ratification: null,
    acceptance: null,
    approval: null,
    accession: '2016-01-14',
  },
  {
    country: 'Saint Kitts and Nevis',
    iso3: 'KNA',
    signature: null,
    ratification: null,
    acceptance: null,
    approval: null,
    accession: '2015-12-09',
  },
  {
    country: 'Saint Vincent and the Grenadines',
    iso3: 'VCT',
    signature: null,
    ratification: null,
    acceptance: null,
    approval: null,
    accession: '2016-06-23',
  },
  {
    country: 'Sao Tome and Principe',
    iso3: 'STP',
    signature: null,
    ratification: null,
    acceptance: null,
    approval: null,
    accession: '2016-11-22',
  },
  {
    country: 'Senegal',
    iso3: 'SEN',
    signature: null,
    ratification: null,
    acceptance: null,
    approval: null,
    accession: '2017-03-23',
  },
  {
    country: 'Seychelles',
    iso3: 'SYC',
    signature: null,
    ratification: null,
    acceptance: null,
    approval: null,
    accession: '2013-06-19',
  },
  {
    country: 'Somalia',
    iso3: 'SOM',
    signature: null,
    ratification: null,
    acceptance: null,
    approval: null,
    accession: '2015-11-09',
  },
  {
    country: 'South Africa',
    iso3: 'ZAF',
    signature: null,
    ratification: null,
    acceptance: null,
    approval: null,
    accession: '2016-02-16',
  },
  {
    country: 'Sri Lanka',
    iso3: 'LKA',
    signature: null,
    ratification: null,
    acceptance: null,
    approval: null,
    accession: '2011-01-20',
  },
  {
    country: 'Sudan',
    iso3: 'SDN',
    signature: null,
    ratification: null,
    acceptance: null,
    approval: null,
    accession: '2016-05-12',
  },
  {
    country: 'Thailand',
    iso3: 'THA',
    signature: null,
    ratification: null,
    acceptance: null,
    approval: null,
    accession: '2016-05-06',
  },
  {
    country: 'Togo',
    iso3: 'TGO',
    signature: null,
    ratification: null,
    acceptance: null,
    approval: null,
    accession: '2016-12-02',
  },
  {
    country: 'Tonga',
    iso3: 'TON',
    signature: null,
    ratification: null,
    acceptance: null,
    approval: null,
    accession: '2016-05-06',
  },
  {
    country: 'Vanuatu',
    iso3: 'VUT',
    signature: null,
    ratification: null,
    acceptance: null,
    approval: null,
    accession: '2016-05-06',
  },
  {
    country: 'Viet Nam',
    iso3: 'VNM',
    signature: null,
    ratification: null,
    acceptance: null,
    approval: null,
    accession: '2019-01-03',
  },
  {
    country: 'New Zealand',
    iso3: 'NZL',
    signature: '2009-12-15',
    ratification: '2014-02-21',
    acceptance: null,
    approval: null,
    accession: null,
  },
  {
    country: 'Benin',
    iso3: 'BEN',
    signature: '2010-09-28',
    ratification: null,
    acceptance: null,
    approval: null,
    accession: null,
  },
  {
    country: 'Ghana',
    iso3: 'GHA',
    signature: '2010-10-28',
    ratification: '2016-11-29',
    acceptance: null,
    approval: null,
    accession: null,
  },
  {
    country: 'Mozambique',
    iso3: 'MOZ',
    signature: '2010-11-04',
    ratification: '2014-08-19',
    acceptance: null,
    approval: null,
    accession: null,
  },
  {
    country: 'Turkey',
    iso3: 'TUR',
    signature: '2010-11-09',
    ratification: '2018-03-30',
    acceptance: null,
    approval: null,
    accession: null,
  },
  {
    country: 'Peru',
    iso3: 'PER',
    signature: '2010-03-03',
    ratification: '2017-09-27',
    acceptance: null,
    approval: null,
    accession: null,
  },
  {
    country: 'Canada',
    iso3: 'CAN',
    signature: '2010-11-19',
    ratification: '2019-06-20',
    acceptance: null,
    approval: null,
    accession: null,
  },
  {
    country: 'Kenya',
    iso3: 'KEN',
    signature: '2010-11-19',
    ratification: '2017-08-23',
    acceptance: null,
    approval: null,
    accession: null,
  },
  {
    country: 'Gabon',
    iso3: 'GAB',
    signature: '2010-04-26',
    ratification: null,
    acceptance: '2013-11-15',
    approval: null,
    accession: null,
  },
  {
    country: 'Australia',
    iso3: 'AUS',
    signature: '2010-04-27',
    ratification: '2015-07-20',
    acceptance: null,
    approval: null,
    accession: null,
  },
  {
    country: 'Russian Federation',
    iso3: 'RUS',
    signature: '2010-04-29',
    ratification: '2020-12-08',
    acceptance: null,
    approval: null,
    accession: null,
  },
  {
    country: 'Angola',
    iso3: 'AGO',
    signature: '2009-11-22',
    ratification: null,
    acceptance: null,
    approval: null,
    accession: null,
  },
  {
    country: 'Brazil',
    iso3: 'BRA',
    signature: '2009-11-22',
    ratification: null,
    acceptance: null,
    approval: null,
    accession: null,
  },
  {
    country: 'Chile',
    iso3: 'CHL',
    signature: '2009-11-22',
    ratification: '2012-08-28',
    acceptance: null,
    approval: null,
    accession: null,
  },
  {
    country: 'Iceland',
    iso3: 'ISL',
    signature: '2009-11-22',
    ratification: '2015-06-16',
    acceptance: null,
    approval: null,
    accession: null,
  },
  {
    country: 'Indonesia',
    iso3: 'IDN',
    signature: '2009-11-22',
    ratification: '2016-06-23',
    acceptance: null,
    approval: null,
    accession: null,
  },
  {
    country: 'Norway',
    iso3: 'NOR',
    signature: '2009-11-22',
    ratification: '2011-07-20',
    acceptance: null,
    approval: null,
    accession: null,
  },
  {
    country: 'Samoa',
    iso3: 'WSM',
    signature: '2009-11-22',
    ratification: null,
    acceptance: null,
    approval: null,
    accession: null,
  },
  {
    country: 'Uruguay',
    iso3: 'URY',
    signature: '2009-11-22',
    ratification: '2013-02-28',
    acceptance: null,
    approval: null,
    accession: null,
  },
  {
    country: 'USA',
    iso3: 'USA',
    signature: '2009-11-22',
    ratification: '2016-02-26',
    acceptance: null,
    approval: null,
    accession: null,
  },
  {
    country: 'Sierra Leone',
    iso3: 'SLE',
    signature: '2009-11-23',
    ratification: '2018-09-17',
    acceptance: null,
    approval: null,
    accession: null,
  },
  {
    country: 'Austria',
    iso3: 'AUT',
    signature: '2009-11-22',
    ratification: null,
    acceptance: null,
    approval: '2011-07-07',
    accession: null,
  },
  {
    country: 'Belgium',
    iso3: 'BEL',
    signature: '2009-11-22',
    ratification: null,
    acceptance: null,
    approval: '2011-07-07',
    accession: null,
  },
  {
    country: 'Bulgaria',
    iso3: 'BGR',
    signature: '2009-11-22',
    ratification: null,
    acceptance: null,
    approval: '2011-07-07',
    accession: null,
  },
  {
    country: 'Croatia',
    iso3: 'HRV',
    signature: '2009-11-22',
    ratification: null,
    acceptance: null,
    approval: '2011-07-07',
    accession: null,
  },
  {
    country: 'Cyprus',
    iso3: 'CYP',
    signature: '2009-11-22',
    ratification: null,
    acceptance: null,
    approval: '2011-07-07',
    accession: null,
  },
  {
    country: 'Czech Republic',
    iso3: 'CZE',
    signature: '2009-11-22',
    ratification: null,
    acceptance: null,
    approval: '2011-07-07',
    accession: null,
  },
  {
    country: 'Denmark',
    iso3: 'DNK',
    signature: '2009-11-22',
    ratification: null,
    acceptance: null,
    approval: '2011-07-07',
    accession: null,
  },
  {
    country: 'Estonia',
    iso3: 'EST',
    signature: '2009-11-22',
    ratification: null,
    acceptance: null,
    approval: '2011-07-07',
    accession: null,
  },
  {
    country: 'EU',
    iso3: null,
    signature: '2009-11-22',
    ratification: null,
    acceptance: null,
    approval: '2011-07-07',
    accession: null,
  },
  {
    country: 'Finland',
    iso3: 'FIN',
    signature: '2009-11-22',
    ratification: null,
    acceptance: null,
    approval: '2011-07-07',
    accession: null,
  },
  {
    country: 'Germany',
    iso3: 'DEU',
    signature: '2009-11-22',
    ratification: null,
    acceptance: null,
    approval: '2011-07-07',
    accession: null,
  },
  {
    country: 'Greece',
    iso3: 'GRC',
    signature: '2009-11-22',
    ratification: null,
    acceptance: null,
    approval: '2011-07-07',
    accession: null,
  },
  {
    country: 'Hungary',
    iso3: 'HUN',
    signature: '2009-11-22',
    ratification: null,
    acceptance: null,
    approval: '2011-07-07',
    accession: null,
  },
  {
    country: 'Ireland',
    iso3: 'IRL',
    signature: '2009-11-22',
    ratification: null,
    acceptance: null,
    approval: '2011-07-07',
    accession: null,
  },
  {
    country: 'Italy',
    iso3: 'ITA',
    signature: '2009-11-22',
    ratification: null,
    acceptance: null,
    approval: '2011-07-07',
    accession: null,
  },
  {
    country: 'Latvia',
    iso3: 'LVA',
    signature: '2009-11-22',
    ratification: null,
    acceptance: null,
    approval: '2011-07-07',
    accession: null,
  },
  {
    country: 'Lithuania',
    iso3: 'LTU',
    signature: '2009-11-22',
    ratification: null,
    acceptance: null,
    approval: '2011-07-07',
    accession: null,
  },
  {
    country: 'Luxembourg',
    iso3: 'LUX',
    signature: '2009-11-22',
    ratification: null,
    acceptance: null,
    approval: '2011-07-07',
    accession: null,
  },
  {
    country: 'Malta',
    iso3: 'MLT',
    signature: '2009-11-22',
    ratification: null,
    acceptance: null,
    approval: '2011-07-07',
    accession: null,
  },
  {
    country: 'Netherlands',
    iso3: 'NLD',
    signature: '2009-11-22',
    ratification: null,
    acceptance: null,
    approval: '2011-07-07',
    accession: null,
  },
  {
    country: 'Poland',
    iso3: 'POL',
    signature: '2009-11-22',
    ratification: null,
    acceptance: null,
    approval: '2011-07-07',
    accession: null,
  },
  {
    country: 'Portugal',
    iso3: 'PRT',
    signature: '2009-11-22',
    ratification: null,
    acceptance: null,
    approval: '2011-07-07',
    accession: null,
  },
  {
    country: 'Romania',
    iso3: 'ROU',
    signature: '2009-11-22',
    ratification: null,
    acceptance: null,
    approval: '2011-07-07',
    accession: null,
  },
  {
    country: 'Slovakia',
    iso3: 'SVK',
    signature: '2009-11-22',
    ratification: null,
    acceptance: null,
    approval: '2011-07-07',
    accession: null,
  },
  {
    country: 'Slovenia',
    iso3: 'SVN',
    signature: '2009-11-22',
    ratification: null,
    acceptance: null,
    approval: '2011-07-07',
    accession: null,
  },
  {
    country: 'Spain',
    iso3: 'ESP',
    signature: '2009-11-22',
    ratification: null,
    acceptance: null,
    approval: '2011-07-07',
    accession: null,
  },
  {
    country: 'Sweden',
    iso3: 'SWE',
    signature: '2009-11-22',
    ratification: null,
    acceptance: null,
    approval: '2011-07-07',
    accession: null,
  },
  {
    country: 'United Kingdom',
    iso3: 'GBR',
    signature: '2009-11-22',
    ratification: null,
    acceptance: null,
    approval: '2011-07-07',
    accession: '2021-01-31',
  },
  {
    country: 'France',
    iso3: 'FRA',
    signature: '2010-11-19',
    ratification: null,
    acceptance: null,
    approval: '2016-07-11',
    accession: null,
  },
]
export default psma
