steps:
  # Push production image to GCR
  - name: 'gcr.io/kaniko-project/executor:latest'
    args:
      [
        '--destination=gcr.io/world-fishing-827/github.com/globalfishingwatch/tile-inspector:$COMMIT_SHA',
        '--cache=true',
        '--build-arg',
        'REACT_APP_API_GATEWAY=$_REACT_APP_API_GATEWAY',
        '--build-arg',
        'BASIC_AUTH_USER=$_BASIC_AUTH_USER',
        '--build-arg',
        'BASIC_AUTH_PASS=$_BASIC_AUTH_PASS',
        '--target',
        'build',
        '-f',
        './applications/tile-inspector/Dockerfile',
        '-c',
        './applications/tile-inspector',
      ]

  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'run',
        'gcr.io/world-fishing-827/github.com/globalfishingwatch/tile-inspector:$COMMIT_SHA',
        'npm',
        'test',
      ]

  - name: 'gcr.io/kaniko-project/executor:latest'
    args:
      [
        '--destination=gcr.io/world-fishing-827/github.com/globalfishingwatch/tile-inspector:$COMMIT_SHA',
        '--cache=true',
        '--build-arg',
        'REACT_APP_API_GATEWAY=$_REACT_APP_API_GATEWAY',
        '--build-arg',
        'BASIC_AUTH_USER=$_BASIC_AUTH_USER',
        '--build-arg',
        'BASIC_AUTH_PASS=$_BASIC_AUTH_PASS',
        '--target',
        'production',
        '-f',
        './applications/tile-inspector/Dockerfile',
        '-c',
        './applications/tile-inspector',
      ]

  # Deploy to the appropriate environment
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      [
        'beta',
        'run',
        'deploy',
        '$_RUN_SERVICE_NAME',
        '--project',
        '$_RUN_PROJECT',
        '--image',
        'gcr.io/world-fishing-827/github.com/globalfishingwatch/tile-inspector:$COMMIT_SHA',
        '--region',
        '$_RUN_REGION',
        '--platform',
        'managed',
        '--set-env-vars',
        'BASIC_AUTH=$_BASIC_AUTH',
        '--allow-unauthenticated',
      ]

images:
  - 'gcr.io/world-fishing-827/github.com/globalfishingwatch/tile-inspector:$COMMIT_SHA'

timeout: 1800s
