const translations = 'used_to_get_dynamic_translations_autogenerated'

// t('common.detection', 'Detection')
// t(['common.detection'], 'detections', { count: parseInt(value) })

export default translations
