steps:
  - name: 'gcr.io/$PROJECT_ID/restore_cache'
    id: restore_cache
    waitFor: ['-']
    args:
      - '--bucket=gs://frontend-cache-dependencies'
      - '--key=yarn-$( checksum yarn.lock )'

  - id: 'install-yarn'
    waitFor: ['restore_cache']
    name: node:21
    entrypoint: sh
    args:
      - '-c'
      # if dependencies cache is not found then install all deps
      - |
        if [ ! -d "node_modules" ]; then
          apk add git
          yarn install --immutable
        fi

  - id: 'save_cache'
    waitFor: ['install-yarn']
    name: 'gcr.io/$PROJECT_ID/save_cache'
    args:
      - '--bucket=gs://frontend-cache-dependencies'
      - '--key=yarn-$( checksum yarn.lock )'
      - '--path=./node_modules'
      - '--no-clobber'

  - id: 'build-app'
    waitFor: ['install-yarn']
    name: node:21
    entrypoint: yarn
    args: ['nx', 'build', 'port-labeler', '--parallel']
    env:
      - 'NX_BRANCH=$_NX_BRANCH'
      - 'NX_CLOUD_AUTH_TOKEN=$_NX_CLOUD_AUTH_TOKEN'
      - 'NEXT_PUBLIC_URL=$_NEXT_PUBLIC_URL'
      - 'NEXT_PUBLIC_API_GATEWAY=$_NEXT_PUBLIC_API_GATEWAY'
      - 'NEXT_PUBLIC_GOOGLE_MEASUREMENT_ID=$_NEXT_PUBLIC_GOOGLE_MEASUREMENT_ID'
      - 'NEXT_PUBLIC_GOOGLE_TAG_MANAGER_ID=$_NEXT_PUBLIC_GOOGLE_TAG_MANAGER_ID'
      - 'NEXT_PUBLIC_GOOGLE_ANALYTICS_DEBUG_MODE=$_NEXT_PUBLIC_GOOGLE_ANALYTICS_DEBUG_MODE'

  - name: 'gcr.io/kaniko-project/executor:debug'
    id: 'build-image'
    waitFor: ['build-app']
    entrypoint: ''
    env:
      - 'REF_NAME=$REF_NAME'
      - 'SHORT_SHA=$SHORT_SHA'
    script: |
      image_version=`echo $REF_NAME | grep -Eo "(develop)" || echo $REF_NAME | grep -Eo "port-labeler@([0-9].*)" | grep -Eo "([0-9].*)" || echo $SHORT_SHA`
      /kaniko/executor \
        --destination=gcr.io/world-fishing-827/github.com/globalfishingwatch/port-labeler:latest \
        --destination=gcr.io/world-fishing-827/github.com/globalfishingwatch/port-labeler:$SHORT_SHA \
        --destination=gcr.io/world-fishing-827/github.com/globalfishingwatch/port-labeler:$image_version \
        --cache=true \
        --build-arg \
          APP_NAME=port-labeler \
        --target \
          production \
        -f \
          ./apps/port-labeler/Dockerfile \
        -c \
          ./dist/apps/port-labeler

  # Deploy to the appropriate environment
  - name: 'gcr.io/cloud-builders/gcloud'
    waitFor: ['build-image']
    id: 'deploy-cloud-run'
    entrypoint: 'bash'
    env:
      - '_RUN_SERVICE_NAME=$_RUN_SERVICE_NAME'
    args:
      - '-eEuo'
      - 'pipefail'
      - '-c'
      - |-
        branch_service_name=`echo port-labeler-$BRANCH_NAME | sed -r 's,[/\.],-,g' | awk '{print substr(tolower($0),0,62)}'`
        service_name=${_RUN_SERVICE_NAME:-${branch_service_name}}
        gcloud beta run deploy \
        $service_name \
        --project \
        $_RUN_PROJECT \
        --image \
        gcr.io/world-fishing-827/github.com/globalfishingwatch/port-labeler:$SHORT_SHA \
        --region \
        $_RUN_REGION \
        --platform managed \
        --set-env-vars \
        BASIC_AUTH=$_BASIC_AUTH \
        --set-env-vars \
        BASIC_AUTH_USER=$_BASIC_AUTH_USER \
        --set-env-vars \
        BASIC_AUTH_PASS=$_BASIC_AUTH_PASS \
        --allow-unauthenticated

timeout: 1800s
options:
  machineType: 'E2_HIGHCPU_8'
