/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './__root'
import { Route as PlatformRouteImport } from './_platform'
import { Route as LoginRouteImport } from './login'
import { Route as PlatformIndexRouteImport } from './_platform/index'
import { Route as PlatformContentRouteImport } from './_platform/_content'
import { Route as PlatformMapRouteImport } from './_platform/_map'
import { Route as ApiCorrectionsRouteImport } from './api/corrections'
import { Route as ApiDownloadSurveyRouteImport } from './api/downloadSurvey'
import { Route as ApiFeedbackRouteImport } from './api/feedback'
import { Route as PlatformContentUserRouteImport } from './_platform/_content/user'
import { Route as PlatformContentVesselSearchRouteImport } from './_platform/_content/vessel-search'
import { Route as PlatformMapMapRouteImport } from './_platform/_map/map'
import { Route as ApiMigramarAreaIdRouteImport } from './api/migramar/$areaId'
import { Route as ApiMigramarOptionsRouteImport } from './api/migramar/options'
import { Route as ApiOceanAreasIndexRouteImport } from './api/ocean-areas/index'
import { Route as ApiOceanAreasNameRouteImport } from './api/ocean-areas/name'
import { Route as ApiOceanAreasSearchRouteImport } from './api/ocean-areas/search'
import { Route as PlatformContentHelpAndResourcesIndexRouteImport } from './_platform/_content/help-and-resources/index'
import { Route as PlatformMapMapIndexRouteImport } from './_platform/_map/map/index'
import { Route as PlatformMapMapUserRouteImport } from './_platform/_map/map/user'
import { Route as PlatformMapMapVesselSearchRouteImport } from './_platform/_map/map/vessel-search'
import { Route as PlatformMapReportReportIdRouteImport } from './_platform/_map/report.$reportId'
import { Route as PlatformMapVesselVesselIdRouteImport } from './_platform/_map/vessel.$vesselId'
import { Route as ApiTrackCorrectionsWorkspaceIdIndexRouteImport } from './api/track-corrections/$workspaceId/index'
import { Route as ApiTrackCorrectionsWorkspaceIdIssueIdRouteImport } from './api/track-corrections/$workspaceId/$issueId'
import { Route as PlatformContentHelpAndResourcesSectionSlugChar123TopicSlugChar125RouteImport } from './_platform/_content/help-and-resources/$sectionSlug.{-$topicSlug}'
import { Route as PlatformMapMapCategoryIndexRouteImport } from './_platform/_map/map/$category/index'
import { Route as PlatformMapMapCategoryWorkspaceIdRouteImport } from './_platform/_map/map/$category/$workspaceId'
import { Route as PlatformMapMapReportReportIdRouteImport } from './_platform/_map/map/report.$reportId'
import { Route as PlatformMapMapVesselVesselIdRouteImport } from './_platform/_map/map/vessel.$vesselId'
import { Route as PlatformMapMapCategoryWorkspaceIdIndexRouteImport } from './_platform/_map/map/$category/$workspaceId/index'
import { Route as PlatformMapMapCategoryWorkspaceIdVesselSearchRouteImport } from './_platform/_map/map/$category/$workspaceId/vessel-search'
import { Route as PlatformMapMapCategoryWorkspaceIdPortsReportPortIdRouteImport } from './_platform/_map/map/$category/$workspaceId/ports-report.$portId'
import { Route as PlatformMapMapCategoryWorkspaceIdVesselGroupReportVesselGroupIdRouteImport } from './_platform/_map/map/$category/$workspaceId/vessel-group-report.$vesselGroupId'
import { Route as PlatformMapMapCategoryWorkspaceIdVesselVesselIdRouteImport } from './_platform/_map/map/$category/$workspaceId/vessel.$vesselId'
import { Route as PlatformMapMapCategoryWorkspaceIdReportChar123DatasetIdChar125Char123AreaIdChar125RouteImport } from './_platform/_map/map/$category/$workspaceId/report.{-$datasetId}.{-$areaId}'

const PlatformRoute = PlatformRouteImport.update({
  id: '/_platform',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformIndexRoute = PlatformIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PlatformRoute,
} as any)
const PlatformContentRoute = PlatformContentRouteImport.update({
  id: '/_content',
  getParentRoute: () => PlatformRoute,
} as any)
const PlatformMapRoute = PlatformMapRouteImport.update({
  id: '/_map',
  getParentRoute: () => PlatformRoute,
} as any)
const ApiCorrectionsRoute = ApiCorrectionsRouteImport.update({
  id: '/api/corrections',
  path: '/api/corrections',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDownloadSurveyRoute = ApiDownloadSurveyRouteImport.update({
  id: '/api/downloadSurvey',
  path: '/api/downloadSurvey',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFeedbackRoute = ApiFeedbackRouteImport.update({
  id: '/api/feedback',
  path: '/api/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformContentUserRoute = PlatformContentUserRouteImport.update({
  id: '/user',
  path: '/user',
  getParentRoute: () => PlatformContentRoute,
} as any)
const PlatformContentVesselSearchRoute = PlatformContentVesselSearchRouteImport.update({
  id: '/vessel-search',
  path: '/vessel-search',
  getParentRoute: () => PlatformContentRoute,
} as any)
const PlatformMapMapRoute = PlatformMapMapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => PlatformMapRoute,
} as any)
const ApiMigramarAreaIdRoute = ApiMigramarAreaIdRouteImport.update({
  id: '/api/migramar/$areaId',
  path: '/api/migramar/$areaId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMigramarOptionsRoute = ApiMigramarOptionsRouteImport.update({
  id: '/api/migramar/options',
  path: '/api/migramar/options',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOceanAreasIndexRoute = ApiOceanAreasIndexRouteImport.update({
  id: '/api/ocean-areas/',
  path: '/api/ocean-areas/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOceanAreasNameRoute = ApiOceanAreasNameRouteImport.update({
  id: '/api/ocean-areas/name',
  path: '/api/ocean-areas/name',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOceanAreasSearchRoute = ApiOceanAreasSearchRouteImport.update({
  id: '/api/ocean-areas/search',
  path: '/api/ocean-areas/search',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformContentHelpAndResourcesIndexRoute =
  PlatformContentHelpAndResourcesIndexRouteImport.update({
    id: '/help-and-resources/',
    path: '/help-and-resources/',
    getParentRoute: () => PlatformContentRoute,
  } as any)
const PlatformMapMapIndexRoute = PlatformMapMapIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PlatformMapMapRoute,
} as any)
const PlatformMapMapUserRoute = PlatformMapMapUserRouteImport.update({
  id: '/user',
  path: '/user',
  getParentRoute: () => PlatformMapMapRoute,
} as any)
const PlatformMapMapVesselSearchRoute = PlatformMapMapVesselSearchRouteImport.update({
  id: '/vessel-search',
  path: '/vessel-search',
  getParentRoute: () => PlatformMapMapRoute,
} as any)
const PlatformMapReportReportIdRoute = PlatformMapReportReportIdRouteImport.update({
  id: '/report/$reportId',
  path: '/report/$reportId',
  getParentRoute: () => PlatformMapRoute,
} as any)
const PlatformMapVesselVesselIdRoute = PlatformMapVesselVesselIdRouteImport.update({
  id: '/vessel/$vesselId',
  path: '/vessel/$vesselId',
  getParentRoute: () => PlatformMapRoute,
} as any)
const ApiTrackCorrectionsWorkspaceIdIndexRoute =
  ApiTrackCorrectionsWorkspaceIdIndexRouteImport.update({
    id: '/api/track-corrections/$workspaceId/',
    path: '/api/track-corrections/$workspaceId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiTrackCorrectionsWorkspaceIdIssueIdRoute =
  ApiTrackCorrectionsWorkspaceIdIssueIdRouteImport.update({
    id: '/api/track-corrections/$workspaceId/$issueId',
    path: '/api/track-corrections/$workspaceId/$issueId',
    getParentRoute: () => rootRouteImport,
  } as any)
const PlatformContentHelpAndResourcesSectionSlugChar123TopicSlugChar125Route =
  PlatformContentHelpAndResourcesSectionSlugChar123TopicSlugChar125RouteImport.update({
    id: '/help-and-resources/$sectionSlug/{-$topicSlug}',
    path: '/help-and-resources/$sectionSlug/{-$topicSlug}',
    getParentRoute: () => PlatformContentRoute,
  } as any)
const PlatformMapMapCategoryIndexRoute = PlatformMapMapCategoryIndexRouteImport.update({
  id: '/$category/',
  path: '/$category/',
  getParentRoute: () => PlatformMapMapRoute,
} as any)
const PlatformMapMapCategoryWorkspaceIdRoute = PlatformMapMapCategoryWorkspaceIdRouteImport.update({
  id: '/$category/$workspaceId',
  path: '/$category/$workspaceId',
  getParentRoute: () => PlatformMapMapRoute,
} as any)
const PlatformMapMapReportReportIdRoute = PlatformMapMapReportReportIdRouteImport.update({
  id: '/report/$reportId',
  path: '/report/$reportId',
  getParentRoute: () => PlatformMapMapRoute,
} as any)
const PlatformMapMapVesselVesselIdRoute = PlatformMapMapVesselVesselIdRouteImport.update({
  id: '/vessel/$vesselId',
  path: '/vessel/$vesselId',
  getParentRoute: () => PlatformMapMapRoute,
} as any)
const PlatformMapMapCategoryWorkspaceIdIndexRoute =
  PlatformMapMapCategoryWorkspaceIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => PlatformMapMapCategoryWorkspaceIdRoute,
  } as any)
const PlatformMapMapCategoryWorkspaceIdVesselSearchRoute =
  PlatformMapMapCategoryWorkspaceIdVesselSearchRouteImport.update({
    id: '/vessel-search',
    path: '/vessel-search',
    getParentRoute: () => PlatformMapMapCategoryWorkspaceIdRoute,
  } as any)
const PlatformMapMapCategoryWorkspaceIdPortsReportPortIdRoute =
  PlatformMapMapCategoryWorkspaceIdPortsReportPortIdRouteImport.update({
    id: '/ports-report/$portId',
    path: '/ports-report/$portId',
    getParentRoute: () => PlatformMapMapCategoryWorkspaceIdRoute,
  } as any)
const PlatformMapMapCategoryWorkspaceIdVesselGroupReportVesselGroupIdRoute =
  PlatformMapMapCategoryWorkspaceIdVesselGroupReportVesselGroupIdRouteImport.update({
    id: '/vessel-group-report/$vesselGroupId',
    path: '/vessel-group-report/$vesselGroupId',
    getParentRoute: () => PlatformMapMapCategoryWorkspaceIdRoute,
  } as any)
const PlatformMapMapCategoryWorkspaceIdVesselVesselIdRoute =
  PlatformMapMapCategoryWorkspaceIdVesselVesselIdRouteImport.update({
    id: '/vessel/$vesselId',
    path: '/vessel/$vesselId',
    getParentRoute: () => PlatformMapMapCategoryWorkspaceIdRoute,
  } as any)
const PlatformMapMapCategoryWorkspaceIdReportChar123DatasetIdChar125Char123AreaIdChar125Route =
  PlatformMapMapCategoryWorkspaceIdReportChar123DatasetIdChar125Char123AreaIdChar125RouteImport.update(
    {
      id: '/report/{-$datasetId}/{-$areaId}',
      path: '/report/{-$datasetId}/{-$areaId}',
      getParentRoute: () => PlatformMapMapCategoryWorkspaceIdRoute,
    } as any
  )

export interface FileRoutesByFullPath {
  '/': typeof PlatformIndexRoute
  '/login': typeof LoginRoute
  '/api/corrections': typeof ApiCorrectionsRoute
  '/api/downloadSurvey': typeof ApiDownloadSurveyRoute
  '/api/feedback': typeof ApiFeedbackRoute
  '/user': typeof PlatformContentUserRoute
  '/vessel-search': typeof PlatformContentVesselSearchRoute
  '/map': typeof PlatformMapMapRouteWithChildren
  '/api/migramar/$areaId': typeof ApiMigramarAreaIdRoute
  '/api/migramar/options': typeof ApiMigramarOptionsRoute
  '/api/ocean-areas/name': typeof ApiOceanAreasNameRoute
  '/api/ocean-areas/search': typeof ApiOceanAreasSearchRoute
  '/api/ocean-areas/': typeof ApiOceanAreasIndexRoute
  '/map/user': typeof PlatformMapMapUserRoute
  '/map/vessel-search': typeof PlatformMapMapVesselSearchRoute
  '/report/$reportId': typeof PlatformMapReportReportIdRoute
  '/vessel/$vesselId': typeof PlatformMapVesselVesselIdRoute
  '/api/track-corrections/$workspaceId/$issueId': typeof ApiTrackCorrectionsWorkspaceIdIssueIdRoute
  '/help-and-resources/': typeof PlatformContentHelpAndResourcesIndexRoute
  '/map/': typeof PlatformMapMapIndexRoute
  '/api/track-corrections/$workspaceId/': typeof ApiTrackCorrectionsWorkspaceIdIndexRoute
  '/help-and-resources/$sectionSlug/{-$topicSlug}': typeof PlatformContentHelpAndResourcesSectionSlugChar123TopicSlugChar125Route
  '/map/$category/$workspaceId': typeof PlatformMapMapCategoryWorkspaceIdRouteWithChildren
  '/map/report/$reportId': typeof PlatformMapMapReportReportIdRoute
  '/map/vessel/$vesselId': typeof PlatformMapMapVesselVesselIdRoute
  '/map/$category/': typeof PlatformMapMapCategoryIndexRoute
  '/map/$category/$workspaceId/vessel-search': typeof PlatformMapMapCategoryWorkspaceIdVesselSearchRoute
  '/map/$category/$workspaceId/': typeof PlatformMapMapCategoryWorkspaceIdIndexRoute
  '/map/$category/$workspaceId/ports-report/$portId': typeof PlatformMapMapCategoryWorkspaceIdPortsReportPortIdRoute
  '/map/$category/$workspaceId/vessel-group-report/$vesselGroupId': typeof PlatformMapMapCategoryWorkspaceIdVesselGroupReportVesselGroupIdRoute
  '/map/$category/$workspaceId/vessel/$vesselId': typeof PlatformMapMapCategoryWorkspaceIdVesselVesselIdRoute
  '/map/$category/$workspaceId/report/{-$datasetId}/{-$areaId}': typeof PlatformMapMapCategoryWorkspaceIdReportChar123DatasetIdChar125Char123AreaIdChar125Route
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/': typeof PlatformIndexRoute
  '/api/corrections': typeof ApiCorrectionsRoute
  '/api/downloadSurvey': typeof ApiDownloadSurveyRoute
  '/api/feedback': typeof ApiFeedbackRoute
  '/user': typeof PlatformContentUserRoute
  '/vessel-search': typeof PlatformContentVesselSearchRoute
  '/api/migramar/$areaId': typeof ApiMigramarAreaIdRoute
  '/api/migramar/options': typeof ApiMigramarOptionsRoute
  '/api/ocean-areas/name': typeof ApiOceanAreasNameRoute
  '/api/ocean-areas/search': typeof ApiOceanAreasSearchRoute
  '/api/ocean-areas': typeof ApiOceanAreasIndexRoute
  '/map/user': typeof PlatformMapMapUserRoute
  '/map/vessel-search': typeof PlatformMapMapVesselSearchRoute
  '/report/$reportId': typeof PlatformMapReportReportIdRoute
  '/vessel/$vesselId': typeof PlatformMapVesselVesselIdRoute
  '/api/track-corrections/$workspaceId/$issueId': typeof ApiTrackCorrectionsWorkspaceIdIssueIdRoute
  '/help-and-resources': typeof PlatformContentHelpAndResourcesIndexRoute
  '/map': typeof PlatformMapMapIndexRoute
  '/api/track-corrections/$workspaceId': typeof ApiTrackCorrectionsWorkspaceIdIndexRoute
  '/help-and-resources/$sectionSlug/{-$topicSlug}': typeof PlatformContentHelpAndResourcesSectionSlugChar123TopicSlugChar125Route
  '/map/report/$reportId': typeof PlatformMapMapReportReportIdRoute
  '/map/vessel/$vesselId': typeof PlatformMapMapVesselVesselIdRoute
  '/map/$category': typeof PlatformMapMapCategoryIndexRoute
  '/map/$category/$workspaceId/vessel-search': typeof PlatformMapMapCategoryWorkspaceIdVesselSearchRoute
  '/map/$category/$workspaceId': typeof PlatformMapMapCategoryWorkspaceIdIndexRoute
  '/map/$category/$workspaceId/ports-report/$portId': typeof PlatformMapMapCategoryWorkspaceIdPortsReportPortIdRoute
  '/map/$category/$workspaceId/vessel-group-report/$vesselGroupId': typeof PlatformMapMapCategoryWorkspaceIdVesselGroupReportVesselGroupIdRoute
  '/map/$category/$workspaceId/vessel/$vesselId': typeof PlatformMapMapCategoryWorkspaceIdVesselVesselIdRoute
  '/map/$category/$workspaceId/report/{-$datasetId}/{-$areaId}': typeof PlatformMapMapCategoryWorkspaceIdReportChar123DatasetIdChar125Char123AreaIdChar125Route
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_platform': typeof PlatformRouteWithChildren
  '/login': typeof LoginRoute
  '/_platform/_content': typeof PlatformContentRouteWithChildren
  '/_platform/_map': typeof PlatformMapRouteWithChildren
  '/api/corrections': typeof ApiCorrectionsRoute
  '/api/downloadSurvey': typeof ApiDownloadSurveyRoute
  '/api/feedback': typeof ApiFeedbackRoute
  '/_platform/': typeof PlatformIndexRoute
  '/_platform/_content/user': typeof PlatformContentUserRoute
  '/_platform/_content/vessel-search': typeof PlatformContentVesselSearchRoute
  '/_platform/_map/map': typeof PlatformMapMapRouteWithChildren
  '/api/migramar/$areaId': typeof ApiMigramarAreaIdRoute
  '/api/migramar/options': typeof ApiMigramarOptionsRoute
  '/api/ocean-areas/name': typeof ApiOceanAreasNameRoute
  '/api/ocean-areas/search': typeof ApiOceanAreasSearchRoute
  '/api/ocean-areas/': typeof ApiOceanAreasIndexRoute
  '/_platform/_map/map/user': typeof PlatformMapMapUserRoute
  '/_platform/_map/map/vessel-search': typeof PlatformMapMapVesselSearchRoute
  '/_platform/_map/report/$reportId': typeof PlatformMapReportReportIdRoute
  '/_platform/_map/vessel/$vesselId': typeof PlatformMapVesselVesselIdRoute
  '/api/track-corrections/$workspaceId/$issueId': typeof ApiTrackCorrectionsWorkspaceIdIssueIdRoute
  '/_platform/_content/help-and-resources/': typeof PlatformContentHelpAndResourcesIndexRoute
  '/_platform/_map/map/': typeof PlatformMapMapIndexRoute
  '/api/track-corrections/$workspaceId/': typeof ApiTrackCorrectionsWorkspaceIdIndexRoute
  '/_platform/_content/help-and-resources/$sectionSlug/{-$topicSlug}': typeof PlatformContentHelpAndResourcesSectionSlugChar123TopicSlugChar125Route
  '/_platform/_map/map/$category/$workspaceId': typeof PlatformMapMapCategoryWorkspaceIdRouteWithChildren
  '/_platform/_map/map/report/$reportId': typeof PlatformMapMapReportReportIdRoute
  '/_platform/_map/map/vessel/$vesselId': typeof PlatformMapMapVesselVesselIdRoute
  '/_platform/_map/map/$category/': typeof PlatformMapMapCategoryIndexRoute
  '/_platform/_map/map/$category/$workspaceId/vessel-search': typeof PlatformMapMapCategoryWorkspaceIdVesselSearchRoute
  '/_platform/_map/map/$category/$workspaceId/': typeof PlatformMapMapCategoryWorkspaceIdIndexRoute
  '/_platform/_map/map/$category/$workspaceId/ports-report/$portId': typeof PlatformMapMapCategoryWorkspaceIdPortsReportPortIdRoute
  '/_platform/_map/map/$category/$workspaceId/vessel-group-report/$vesselGroupId': typeof PlatformMapMapCategoryWorkspaceIdVesselGroupReportVesselGroupIdRoute
  '/_platform/_map/map/$category/$workspaceId/vessel/$vesselId': typeof PlatformMapMapCategoryWorkspaceIdVesselVesselIdRoute
  '/_platform/_map/map/$category/$workspaceId/report/{-$datasetId}/{-$areaId}': typeof PlatformMapMapCategoryWorkspaceIdReportChar123DatasetIdChar125Char123AreaIdChar125Route
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/api/corrections'
    | '/api/downloadSurvey'
    | '/api/feedback'
    | '/user'
    | '/vessel-search'
    | '/map'
    | '/api/migramar/$areaId'
    | '/api/migramar/options'
    | '/api/ocean-areas/name'
    | '/api/ocean-areas/search'
    | '/api/ocean-areas/'
    | '/map/user'
    | '/map/vessel-search'
    | '/report/$reportId'
    | '/vessel/$vesselId'
    | '/api/track-corrections/$workspaceId/$issueId'
    | '/help-and-resources/'
    | '/map/'
    | '/api/track-corrections/$workspaceId/'
    | '/help-and-resources/$sectionSlug/{-$topicSlug}'
    | '/map/$category/$workspaceId'
    | '/map/report/$reportId'
    | '/map/vessel/$vesselId'
    | '/map/$category/'
    | '/map/$category/$workspaceId/vessel-search'
    | '/map/$category/$workspaceId/'
    | '/map/$category/$workspaceId/ports-report/$portId'
    | '/map/$category/$workspaceId/vessel-group-report/$vesselGroupId'
    | '/map/$category/$workspaceId/vessel/$vesselId'
    | '/map/$category/$workspaceId/report/{-$datasetId}/{-$areaId}'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/'
    | '/api/corrections'
    | '/api/downloadSurvey'
    | '/api/feedback'
    | '/user'
    | '/vessel-search'
    | '/api/migramar/$areaId'
    | '/api/migramar/options'
    | '/api/ocean-areas/name'
    | '/api/ocean-areas/search'
    | '/api/ocean-areas'
    | '/map/user'
    | '/map/vessel-search'
    | '/report/$reportId'
    | '/vessel/$vesselId'
    | '/api/track-corrections/$workspaceId/$issueId'
    | '/help-and-resources'
    | '/map'
    | '/api/track-corrections/$workspaceId'
    | '/help-and-resources/$sectionSlug/{-$topicSlug}'
    | '/map/report/$reportId'
    | '/map/vessel/$vesselId'
    | '/map/$category'
    | '/map/$category/$workspaceId/vessel-search'
    | '/map/$category/$workspaceId'
    | '/map/$category/$workspaceId/ports-report/$portId'
    | '/map/$category/$workspaceId/vessel-group-report/$vesselGroupId'
    | '/map/$category/$workspaceId/vessel/$vesselId'
    | '/map/$category/$workspaceId/report/{-$datasetId}/{-$areaId}'
  id:
    | '__root__'
    | '/_platform'
    | '/login'
    | '/_platform/_content'
    | '/_platform/_map'
    | '/api/corrections'
    | '/api/downloadSurvey'
    | '/api/feedback'
    | '/_platform/'
    | '/_platform/_content/user'
    | '/_platform/_content/vessel-search'
    | '/_platform/_map/map'
    | '/api/migramar/$areaId'
    | '/api/migramar/options'
    | '/api/ocean-areas/name'
    | '/api/ocean-areas/search'
    | '/api/ocean-areas/'
    | '/_platform/_map/map/user'
    | '/_platform/_map/map/vessel-search'
    | '/_platform/_map/report/$reportId'
    | '/_platform/_map/vessel/$vesselId'
    | '/api/track-corrections/$workspaceId/$issueId'
    | '/_platform/_content/help-and-resources/'
    | '/_platform/_map/map/'
    | '/api/track-corrections/$workspaceId/'
    | '/_platform/_content/help-and-resources/$sectionSlug/{-$topicSlug}'
    | '/_platform/_map/map/$category/$workspaceId'
    | '/_platform/_map/map/report/$reportId'
    | '/_platform/_map/map/vessel/$vesselId'
    | '/_platform/_map/map/$category/'
    | '/_platform/_map/map/$category/$workspaceId/vessel-search'
    | '/_platform/_map/map/$category/$workspaceId/'
    | '/_platform/_map/map/$category/$workspaceId/ports-report/$portId'
    | '/_platform/_map/map/$category/$workspaceId/vessel-group-report/$vesselGroupId'
    | '/_platform/_map/map/$category/$workspaceId/vessel/$vesselId'
    | '/_platform/_map/map/$category/$workspaceId/report/{-$datasetId}/{-$areaId}'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PlatformRoute: typeof PlatformRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiCorrectionsRoute: typeof ApiCorrectionsRoute
  ApiDownloadSurveyRoute: typeof ApiDownloadSurveyRoute
  ApiFeedbackRoute: typeof ApiFeedbackRoute
  ApiMigramarAreaIdRoute: typeof ApiMigramarAreaIdRoute
  ApiMigramarOptionsRoute: typeof ApiMigramarOptionsRoute
  ApiOceanAreasNameRoute: typeof ApiOceanAreasNameRoute
  ApiOceanAreasSearchRoute: typeof ApiOceanAreasSearchRoute
  ApiOceanAreasIndexRoute: typeof ApiOceanAreasIndexRoute
  ApiTrackCorrectionsWorkspaceIdIssueIdRoute: typeof ApiTrackCorrectionsWorkspaceIdIssueIdRoute
  ApiTrackCorrectionsWorkspaceIdIndexRoute: typeof ApiTrackCorrectionsWorkspaceIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_platform': {
      id: '/_platform'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PlatformRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_platform/': {
      id: '/_platform/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PlatformIndexRouteImport
      parentRoute: typeof PlatformRoute
    }
    '/_platform/_content': {
      id: '/_platform/_content'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PlatformContentRouteImport
      parentRoute: typeof PlatformRoute
    }
    '/_platform/_map': {
      id: '/_platform/_map'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PlatformMapRouteImport
      parentRoute: typeof PlatformRoute
    }
    '/api/corrections': {
      id: '/api/corrections'
      path: '/api/corrections'
      fullPath: '/api/corrections'
      preLoaderRoute: typeof ApiCorrectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/downloadSurvey': {
      id: '/api/downloadSurvey'
      path: '/api/downloadSurvey'
      fullPath: '/api/downloadSurvey'
      preLoaderRoute: typeof ApiDownloadSurveyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/feedback': {
      id: '/api/feedback'
      path: '/api/feedback'
      fullPath: '/api/feedback'
      preLoaderRoute: typeof ApiFeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_platform/_content/user': {
      id: '/_platform/_content/user'
      path: '/user'
      fullPath: '/user'
      preLoaderRoute: typeof PlatformContentUserRouteImport
      parentRoute: typeof PlatformContentRoute
    }
    '/_platform/_content/vessel-search': {
      id: '/_platform/_content/vessel-search'
      path: '/vessel-search'
      fullPath: '/vessel-search'
      preLoaderRoute: typeof PlatformContentVesselSearchRouteImport
      parentRoute: typeof PlatformContentRoute
    }
    '/_platform/_map/map': {
      id: '/_platform/_map/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof PlatformMapMapRouteImport
      parentRoute: typeof PlatformMapRoute
    }
    '/api/migramar/$areaId': {
      id: '/api/migramar/$areaId'
      path: '/api/migramar/$areaId'
      fullPath: '/api/migramar/$areaId'
      preLoaderRoute: typeof ApiMigramarAreaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/migramar/options': {
      id: '/api/migramar/options'
      path: '/api/migramar/options'
      fullPath: '/api/migramar/options'
      preLoaderRoute: typeof ApiMigramarOptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ocean-areas/': {
      id: '/api/ocean-areas/'
      path: '/api/ocean-areas'
      fullPath: '/api/ocean-areas/'
      preLoaderRoute: typeof ApiOceanAreasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ocean-areas/name': {
      id: '/api/ocean-areas/name'
      path: '/api/ocean-areas/name'
      fullPath: '/api/ocean-areas/name'
      preLoaderRoute: typeof ApiOceanAreasNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ocean-areas/search': {
      id: '/api/ocean-areas/search'
      path: '/api/ocean-areas/search'
      fullPath: '/api/ocean-areas/search'
      preLoaderRoute: typeof ApiOceanAreasSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_platform/_content/help-and-resources/': {
      id: '/_platform/_content/help-and-resources/'
      path: '/help-and-resources'
      fullPath: '/help-and-resources/'
      preLoaderRoute: typeof PlatformContentHelpAndResourcesIndexRouteImport
      parentRoute: typeof PlatformContentRoute
    }
    '/_platform/_map/map/': {
      id: '/_platform/_map/map/'
      path: '/'
      fullPath: '/map/'
      preLoaderRoute: typeof PlatformMapMapIndexRouteImport
      parentRoute: typeof PlatformMapMapRoute
    }
    '/_platform/_map/map/user': {
      id: '/_platform/_map/map/user'
      path: '/user'
      fullPath: '/map/user'
      preLoaderRoute: typeof PlatformMapMapUserRouteImport
      parentRoute: typeof PlatformMapMapRoute
    }
    '/_platform/_map/map/vessel-search': {
      id: '/_platform/_map/map/vessel-search'
      path: '/vessel-search'
      fullPath: '/map/vessel-search'
      preLoaderRoute: typeof PlatformMapMapVesselSearchRouteImport
      parentRoute: typeof PlatformMapMapRoute
    }
    '/_platform/_map/report/$reportId': {
      id: '/_platform/_map/report/$reportId'
      path: '/report/$reportId'
      fullPath: '/report/$reportId'
      preLoaderRoute: typeof PlatformMapReportReportIdRouteImport
      parentRoute: typeof PlatformMapRoute
    }
    '/_platform/_map/vessel/$vesselId': {
      id: '/_platform/_map/vessel/$vesselId'
      path: '/vessel/$vesselId'
      fullPath: '/vessel/$vesselId'
      preLoaderRoute: typeof PlatformMapVesselVesselIdRouteImport
      parentRoute: typeof PlatformMapRoute
    }
    '/api/track-corrections/$workspaceId/': {
      id: '/api/track-corrections/$workspaceId/'
      path: '/api/track-corrections/$workspaceId'
      fullPath: '/api/track-corrections/$workspaceId/'
      preLoaderRoute: typeof ApiTrackCorrectionsWorkspaceIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/track-corrections/$workspaceId/$issueId': {
      id: '/api/track-corrections/$workspaceId/$issueId'
      path: '/api/track-corrections/$workspaceId/$issueId'
      fullPath: '/api/track-corrections/$workspaceId/$issueId'
      preLoaderRoute: typeof ApiTrackCorrectionsWorkspaceIdIssueIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_platform/_content/help-and-resources/$sectionSlug/{-$topicSlug}': {
      id: '/_platform/_content/help-and-resources/$sectionSlug/{-$topicSlug}'
      path: '/help-and-resources/$sectionSlug/{-$topicSlug}'
      fullPath: '/help-and-resources/$sectionSlug/{-$topicSlug}'
      preLoaderRoute: typeof PlatformContentHelpAndResourcesSectionSlugChar123TopicSlugChar125RouteImport
      parentRoute: typeof PlatformContentRoute
    }
    '/_platform/_map/map/$category/': {
      id: '/_platform/_map/map/$category/'
      path: '/$category'
      fullPath: '/map/$category/'
      preLoaderRoute: typeof PlatformMapMapCategoryIndexRouteImport
      parentRoute: typeof PlatformMapMapRoute
    }
    '/_platform/_map/map/$category/$workspaceId': {
      id: '/_platform/_map/map/$category/$workspaceId'
      path: '/$category/$workspaceId'
      fullPath: '/map/$category/$workspaceId'
      preLoaderRoute: typeof PlatformMapMapCategoryWorkspaceIdRouteImport
      parentRoute: typeof PlatformMapMapRoute
    }
    '/_platform/_map/map/report/$reportId': {
      id: '/_platform/_map/map/report/$reportId'
      path: '/report/$reportId'
      fullPath: '/map/report/$reportId'
      preLoaderRoute: typeof PlatformMapMapReportReportIdRouteImport
      parentRoute: typeof PlatformMapMapRoute
    }
    '/_platform/_map/map/vessel/$vesselId': {
      id: '/_platform/_map/map/vessel/$vesselId'
      path: '/vessel/$vesselId'
      fullPath: '/map/vessel/$vesselId'
      preLoaderRoute: typeof PlatformMapMapVesselVesselIdRouteImport
      parentRoute: typeof PlatformMapMapRoute
    }
    '/_platform/_map/map/$category/$workspaceId/': {
      id: '/_platform/_map/map/$category/$workspaceId/'
      path: '/'
      fullPath: '/map/$category/$workspaceId/'
      preLoaderRoute: typeof PlatformMapMapCategoryWorkspaceIdIndexRouteImport
      parentRoute: typeof PlatformMapMapCategoryWorkspaceIdRoute
    }
    '/_platform/_map/map/$category/$workspaceId/vessel-search': {
      id: '/_platform/_map/map/$category/$workspaceId/vessel-search'
      path: '/vessel-search'
      fullPath: '/map/$category/$workspaceId/vessel-search'
      preLoaderRoute: typeof PlatformMapMapCategoryWorkspaceIdVesselSearchRouteImport
      parentRoute: typeof PlatformMapMapCategoryWorkspaceIdRoute
    }
    '/_platform/_map/map/$category/$workspaceId/ports-report/$portId': {
      id: '/_platform/_map/map/$category/$workspaceId/ports-report/$portId'
      path: '/ports-report/$portId'
      fullPath: '/map/$category/$workspaceId/ports-report/$portId'
      preLoaderRoute: typeof PlatformMapMapCategoryWorkspaceIdPortsReportPortIdRouteImport
      parentRoute: typeof PlatformMapMapCategoryWorkspaceIdRoute
    }
    '/_platform/_map/map/$category/$workspaceId/vessel-group-report/$vesselGroupId': {
      id: '/_platform/_map/map/$category/$workspaceId/vessel-group-report/$vesselGroupId'
      path: '/vessel-group-report/$vesselGroupId'
      fullPath: '/map/$category/$workspaceId/vessel-group-report/$vesselGroupId'
      preLoaderRoute: typeof PlatformMapMapCategoryWorkspaceIdVesselGroupReportVesselGroupIdRouteImport
      parentRoute: typeof PlatformMapMapCategoryWorkspaceIdRoute
    }
    '/_platform/_map/map/$category/$workspaceId/vessel/$vesselId': {
      id: '/_platform/_map/map/$category/$workspaceId/vessel/$vesselId'
      path: '/vessel/$vesselId'
      fullPath: '/map/$category/$workspaceId/vessel/$vesselId'
      preLoaderRoute: typeof PlatformMapMapCategoryWorkspaceIdVesselVesselIdRouteImport
      parentRoute: typeof PlatformMapMapCategoryWorkspaceIdRoute
    }
    '/_platform/_map/map/$category/$workspaceId/report/{-$datasetId}/{-$areaId}': {
      id: '/_platform/_map/map/$category/$workspaceId/report/{-$datasetId}/{-$areaId}'
      path: '/report/{-$datasetId}/{-$areaId}'
      fullPath: '/map/$category/$workspaceId/report/{-$datasetId}/{-$areaId}'
      preLoaderRoute: typeof PlatformMapMapCategoryWorkspaceIdReportChar123DatasetIdChar125Char123AreaIdChar125RouteImport
      parentRoute: typeof PlatformMapMapCategoryWorkspaceIdRoute
    }
  }
}

interface PlatformContentRouteChildren {
  PlatformContentUserRoute: typeof PlatformContentUserRoute
  PlatformContentVesselSearchRoute: typeof PlatformContentVesselSearchRoute
  PlatformContentHelpAndResourcesIndexRoute: typeof PlatformContentHelpAndResourcesIndexRoute
  PlatformContentHelpAndResourcesSectionSlugChar123TopicSlugChar125Route: typeof PlatformContentHelpAndResourcesSectionSlugChar123TopicSlugChar125Route
}

const PlatformContentRouteChildren: PlatformContentRouteChildren = {
  PlatformContentUserRoute: PlatformContentUserRoute,
  PlatformContentVesselSearchRoute: PlatformContentVesselSearchRoute,
  PlatformContentHelpAndResourcesIndexRoute: PlatformContentHelpAndResourcesIndexRoute,
  PlatformContentHelpAndResourcesSectionSlugChar123TopicSlugChar125Route:
    PlatformContentHelpAndResourcesSectionSlugChar123TopicSlugChar125Route,
}

const PlatformContentRouteWithChildren = PlatformContentRoute._addFileChildren(
  PlatformContentRouteChildren
)

interface PlatformMapMapCategoryWorkspaceIdRouteChildren {
  PlatformMapMapCategoryWorkspaceIdVesselSearchRoute: typeof PlatformMapMapCategoryWorkspaceIdVesselSearchRoute
  PlatformMapMapCategoryWorkspaceIdIndexRoute: typeof PlatformMapMapCategoryWorkspaceIdIndexRoute
  PlatformMapMapCategoryWorkspaceIdPortsReportPortIdRoute: typeof PlatformMapMapCategoryWorkspaceIdPortsReportPortIdRoute
  PlatformMapMapCategoryWorkspaceIdVesselGroupReportVesselGroupIdRoute: typeof PlatformMapMapCategoryWorkspaceIdVesselGroupReportVesselGroupIdRoute
  PlatformMapMapCategoryWorkspaceIdVesselVesselIdRoute: typeof PlatformMapMapCategoryWorkspaceIdVesselVesselIdRoute
  PlatformMapMapCategoryWorkspaceIdReportChar123DatasetIdChar125Char123AreaIdChar125Route: typeof PlatformMapMapCategoryWorkspaceIdReportChar123DatasetIdChar125Char123AreaIdChar125Route
}

const PlatformMapMapCategoryWorkspaceIdRouteChildren: PlatformMapMapCategoryWorkspaceIdRouteChildren =
  {
    PlatformMapMapCategoryWorkspaceIdVesselSearchRoute:
      PlatformMapMapCategoryWorkspaceIdVesselSearchRoute,
    PlatformMapMapCategoryWorkspaceIdIndexRoute: PlatformMapMapCategoryWorkspaceIdIndexRoute,
    PlatformMapMapCategoryWorkspaceIdPortsReportPortIdRoute:
      PlatformMapMapCategoryWorkspaceIdPortsReportPortIdRoute,
    PlatformMapMapCategoryWorkspaceIdVesselGroupReportVesselGroupIdRoute:
      PlatformMapMapCategoryWorkspaceIdVesselGroupReportVesselGroupIdRoute,
    PlatformMapMapCategoryWorkspaceIdVesselVesselIdRoute:
      PlatformMapMapCategoryWorkspaceIdVesselVesselIdRoute,
    PlatformMapMapCategoryWorkspaceIdReportChar123DatasetIdChar125Char123AreaIdChar125Route:
      PlatformMapMapCategoryWorkspaceIdReportChar123DatasetIdChar125Char123AreaIdChar125Route,
  }

const PlatformMapMapCategoryWorkspaceIdRouteWithChildren =
  PlatformMapMapCategoryWorkspaceIdRoute._addFileChildren(
    PlatformMapMapCategoryWorkspaceIdRouteChildren
  )

interface PlatformMapMapRouteChildren {
  PlatformMapMapUserRoute: typeof PlatformMapMapUserRoute
  PlatformMapMapVesselSearchRoute: typeof PlatformMapMapVesselSearchRoute
  PlatformMapMapIndexRoute: typeof PlatformMapMapIndexRoute
  PlatformMapMapCategoryWorkspaceIdRoute: typeof PlatformMapMapCategoryWorkspaceIdRouteWithChildren
  PlatformMapMapReportReportIdRoute: typeof PlatformMapMapReportReportIdRoute
  PlatformMapMapVesselVesselIdRoute: typeof PlatformMapMapVesselVesselIdRoute
  PlatformMapMapCategoryIndexRoute: typeof PlatformMapMapCategoryIndexRoute
}

const PlatformMapMapRouteChildren: PlatformMapMapRouteChildren = {
  PlatformMapMapUserRoute: PlatformMapMapUserRoute,
  PlatformMapMapVesselSearchRoute: PlatformMapMapVesselSearchRoute,
  PlatformMapMapIndexRoute: PlatformMapMapIndexRoute,
  PlatformMapMapCategoryWorkspaceIdRoute: PlatformMapMapCategoryWorkspaceIdRouteWithChildren,
  PlatformMapMapReportReportIdRoute: PlatformMapMapReportReportIdRoute,
  PlatformMapMapVesselVesselIdRoute: PlatformMapMapVesselVesselIdRoute,
  PlatformMapMapCategoryIndexRoute: PlatformMapMapCategoryIndexRoute,
}

const PlatformMapMapRouteWithChildren = PlatformMapMapRoute._addFileChildren(
  PlatformMapMapRouteChildren
)

interface PlatformMapRouteChildren {
  PlatformMapMapRoute: typeof PlatformMapMapRouteWithChildren
  PlatformMapReportReportIdRoute: typeof PlatformMapReportReportIdRoute
  PlatformMapVesselVesselIdRoute: typeof PlatformMapVesselVesselIdRoute
}

const PlatformMapRouteChildren: PlatformMapRouteChildren = {
  PlatformMapMapRoute: PlatformMapMapRouteWithChildren,
  PlatformMapReportReportIdRoute: PlatformMapReportReportIdRoute,
  PlatformMapVesselVesselIdRoute: PlatformMapVesselVesselIdRoute,
}

const PlatformMapRouteWithChildren = PlatformMapRoute._addFileChildren(PlatformMapRouteChildren)

interface PlatformRouteChildren {
  PlatformContentRoute: typeof PlatformContentRouteWithChildren
  PlatformMapRoute: typeof PlatformMapRouteWithChildren
  PlatformIndexRoute: typeof PlatformIndexRoute
}

const PlatformRouteChildren: PlatformRouteChildren = {
  PlatformContentRoute: PlatformContentRouteWithChildren,
  PlatformMapRoute: PlatformMapRouteWithChildren,
  PlatformIndexRoute: PlatformIndexRoute,
}

const PlatformRouteWithChildren = PlatformRoute._addFileChildren(PlatformRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  PlatformRoute: PlatformRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiCorrectionsRoute: ApiCorrectionsRoute,
  ApiDownloadSurveyRoute: ApiDownloadSurveyRoute,
  ApiFeedbackRoute: ApiFeedbackRoute,
  ApiMigramarAreaIdRoute: ApiMigramarAreaIdRoute,
  ApiMigramarOptionsRoute: ApiMigramarOptionsRoute,
  ApiOceanAreasNameRoute: ApiOceanAreasNameRoute,
  ApiOceanAreasSearchRoute: ApiOceanAreasSearchRoute,
  ApiOceanAreasIndexRoute: ApiOceanAreasIndexRoute,
  ApiTrackCorrectionsWorkspaceIdIssueIdRoute: ApiTrackCorrectionsWorkspaceIdIssueIdRoute,
  ApiTrackCorrectionsWorkspaceIdIndexRoute: ApiTrackCorrectionsWorkspaceIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from '../router.tsx'
import type { startInstance } from '../start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
