/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LogoutRouteImport } from './routes/logout'
import { Route as LoginErrorRouteImport } from './routes/login-error'
import { Route as AuthedIndexRouteImport } from './routes/_authed/index'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as AuthedSourceRouteImport } from './routes/_authed/$source'
import { Route as ApiVesselsFileNameRouteImport } from './routes/api/vessels/$fileName'
import { Route as ApiIccatSourceRouteImport } from './routes/api/iccat/$source'

const LogoutRoute = LogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginErrorRoute = LoginErrorRouteImport.update({
  id: '/login-error',
  path: '/login-error',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedIndexRoute = AuthedIndexRouteImport.update({
  id: '/_authed/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedSourceRoute = AuthedSourceRouteImport.update({
  id: '/_authed/$source',
  path: '/$source',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVesselsFileNameRoute = ApiVesselsFileNameRouteImport.update({
  id: '/api/vessels/$fileName',
  path: '/api/vessels/$fileName',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIccatSourceRoute = ApiIccatSourceRouteImport.update({
  id: '/api/iccat/$source',
  path: '/api/iccat/$source',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/login-error': typeof LoginErrorRoute
  '/logout': typeof LogoutRoute
  '/$source': typeof AuthedSourceRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/': typeof AuthedIndexRoute
  '/api/iccat/$source': typeof ApiIccatSourceRoute
  '/api/vessels/$fileName': typeof ApiVesselsFileNameRoute
}
export interface FileRoutesByTo {
  '/login-error': typeof LoginErrorRoute
  '/logout': typeof LogoutRoute
  '/$source': typeof AuthedSourceRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/': typeof AuthedIndexRoute
  '/api/iccat/$source': typeof ApiIccatSourceRoute
  '/api/vessels/$fileName': typeof ApiVesselsFileNameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/login-error': typeof LoginErrorRoute
  '/logout': typeof LogoutRoute
  '/_authed/$source': typeof AuthedSourceRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/_authed/': typeof AuthedIndexRoute
  '/api/iccat/$source': typeof ApiIccatSourceRoute
  '/api/vessels/$fileName': typeof ApiVesselsFileNameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login-error'
    | '/logout'
    | '/$source'
    | '/auth/callback'
    | '/'
    | '/api/iccat/$source'
    | '/api/vessels/$fileName'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login-error'
    | '/logout'
    | '/$source'
    | '/auth/callback'
    | '/'
    | '/api/iccat/$source'
    | '/api/vessels/$fileName'
  id:
    | '__root__'
    | '/login-error'
    | '/logout'
    | '/_authed/$source'
    | '/auth/callback'
    | '/_authed/'
    | '/api/iccat/$source'
    | '/api/vessels/$fileName'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LoginErrorRoute: typeof LoginErrorRoute
  LogoutRoute: typeof LogoutRoute
  AuthedSourceRoute: typeof AuthedSourceRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthedIndexRoute: typeof AuthedIndexRoute
  ApiIccatSourceRoute: typeof ApiIccatSourceRoute
  ApiVesselsFileNameRoute: typeof ApiVesselsFileNameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login-error': {
      id: '/login-error'
      path: '/login-error'
      fullPath: '/login-error'
      preLoaderRoute: typeof LoginErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/': {
      id: '/_authed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/$source': {
      id: '/_authed/$source'
      path: '/$source'
      fullPath: '/$source'
      preLoaderRoute: typeof AuthedSourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/vessels/$fileName': {
      id: '/api/vessels/$fileName'
      path: '/api/vessels/$fileName'
      fullPath: '/api/vessels/$fileName'
      preLoaderRoute: typeof ApiVesselsFileNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/iccat/$source': {
      id: '/api/iccat/$source'
      path: '/api/iccat/$source'
      fullPath: '/api/iccat/$source'
      preLoaderRoute: typeof ApiIccatSourceRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  LoginErrorRoute: LoginErrorRoute,
  LogoutRoute: LogoutRoute,
  AuthedSourceRoute: AuthedSourceRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  AuthedIndexRoute: AuthedIndexRoute,
  ApiIccatSourceRoute: ApiIccatSourceRoute,
  ApiVesselsFileNameRoute: ApiVesselsFileNameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
