/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AuthSourceRouteImport } from './routes/_auth/$source'
import { Route as ApiVesselsFileNameRouteImport } from './routes/api/vessels/$fileName'
import { Route as ApiIccatSourceRouteImport } from './routes/api/iccat/$source'

const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSourceRoute = AuthSourceRouteImport.update({
  id: '/$source',
  path: '/$source',
  getParentRoute: () => AuthRoute,
} as any)
const ApiVesselsFileNameRoute = ApiVesselsFileNameRouteImport.update({
  id: '/api/vessels/$fileName',
  path: '/api/vessels/$fileName',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIccatSourceRoute = ApiIccatSourceRouteImport.update({
  id: '/api/iccat/$source',
  path: '/api/iccat/$source',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/$source': typeof AuthSourceRoute
  '/api/iccat/$source': typeof ApiIccatSourceRoute
  '/api/vessels/$fileName': typeof ApiVesselsFileNameRoute
}
export interface FileRoutesByTo {
  '/$source': typeof AuthSourceRoute
  '/api/iccat/$source': typeof ApiIccatSourceRoute
  '/api/vessels/$fileName': typeof ApiVesselsFileNameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/_auth/$source': typeof AuthSourceRoute
  '/api/iccat/$source': typeof ApiIccatSourceRoute
  '/api/vessels/$fileName': typeof ApiVesselsFileNameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/$source' | '/api/iccat/$source' | '/api/vessels/$fileName'
  fileRoutesByTo: FileRoutesByTo
  to: '/$source' | '/api/iccat/$source' | '/api/vessels/$fileName'
  id:
    | '__root__'
    | '/_auth'
    | '/_auth/$source'
    | '/api/iccat/$source'
    | '/api/vessels/$fileName'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  ApiIccatSourceRoute: typeof ApiIccatSourceRoute
  ApiVesselsFileNameRoute: typeof ApiVesselsFileNameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/$source': {
      id: '/_auth/$source'
      path: '/$source'
      fullPath: '/$source'
      preLoaderRoute: typeof AuthSourceRouteImport
      parentRoute: typeof AuthRoute
    }
    '/api/vessels/$fileName': {
      id: '/api/vessels/$fileName'
      path: '/api/vessels/$fileName'
      fullPath: '/api/vessels/$fileName'
      preLoaderRoute: typeof ApiVesselsFileNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/iccat/$source': {
      id: '/api/iccat/$source'
      path: '/api/iccat/$source'
      fullPath: '/api/iccat/$source'
      preLoaderRoute: typeof ApiIccatSourceRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthRouteChildren {
  AuthSourceRoute: typeof AuthSourceRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthSourceRoute: AuthSourceRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  ApiIccatSourceRoute: ApiIccatSourceRoute,
  ApiVesselsFileNameRoute: ApiVesselsFileNameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
