export const MIN_YEAR = 2017
export const INSIGHTS_NON_FISHING = [
  'COVERAGE',
  'GAP',
  'VESSEL-IDENTITY-FLAG-CHANGES',
  'VESSEL-IDENTITY-MOU-LIST',
]
export const INSIGHTS_FISHING = [
  'COVERAGE',
  'GAP',
  'FISHING',
  'VESSEL-IDENTITY-IUU-VESSEL-LIST',
  'VESSEL-IDENTITY-FLAG-CHANGES',
  'VESSEL-IDENTITY-MOU-LIST',
]
