steps:
  # Push production image to GCR
  - name: 'gcr.io/kaniko-project/executor:latest'
    args:
      [
        '--destination=gcr.io/world-fishing-827/github.com/globalfishingwatch/fishing-map:$COMMIT_SHA',
        '--cache=true',
        '--build-arg',
        'REACT_APP_GOOGLE_API_KEY=$_REACT_APP_GOOGLE_API_KEY',
        '--build-arg',
        'REACT_APP_GOOGLE_SHEETS_ID=$_REACT_APP_GOOGLE_SHEETS_ID',
        '--build-arg',
        'REACT_APP_GOOGLE_TAG_MANAGER_KEY=$_REACT_APP_GOOGLE_TAG_MANAGER_KEY',
        '--build-arg',
        'REACT_APP_API_GATEWAY=$_REACT_APP_API_GATEWAY',
        '--build-arg',
        'REACT_APP_WORKSPACE_ENV=$_REACT_APP_WORKSPACE_ENV',
        '--build-arg',
        'BASIC_AUTH_USER=$_BASIC_AUTH_USER',
        '--build-arg',
        'BASIC_AUTH_PASS=$_BASIC_AUTH_PASS',
        '--target',
        'build',
        '-f',
        './applications/fishing-map/Dockerfile',
        '-c',
        './applications/fishing-map',
      ]

  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'run',
        'gcr.io/world-fishing-827/github.com/globalfishingwatch/fishing-map:$COMMIT_SHA',
        'npm',
        'test',
      ]

  - name: 'gcr.io/kaniko-project/executor:latest'
    args:
      [
        '--destination=gcr.io/world-fishing-827/github.com/globalfishingwatch/fishing-map:$COMMIT_SHA',
        '--cache=true',
        '--build-arg',
        'REACT_APP_GOOGLE_API_KEY=$_REACT_APP_GOOGLE_API_KEY',
        '--build-arg',
        'REACT_APP_GOOGLE_SHEETS_ID=$_REACT_APP_GOOGLE_SHEETS_ID',
        '--build-arg',
        'REACT_APP_GOOGLE_TAG_MANAGER_KEY=$_REACT_APP_GOOGLE_TAG_MANAGER_KEY',
        '--build-arg',
        'REACT_APP_API_GATEWAY=$_REACT_APP_API_GATEWAY',
        '--build-arg',
        'REACT_APP_WORKSPACE_ENV=$_REACT_APP_WORKSPACE_ENV',
        '--build-arg',
        'BASIC_AUTH_USER=$_BASIC_AUTH_USER',
        '--build-arg',
        'BASIC_AUTH_PASS=$_BASIC_AUTH_PASS',
        '--target',
        'production',
        '-f',
        './applications/fishing-map/Dockerfile',
        '-c',
        './applications/fishing-map',
      ]

  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-eEuo'
      - 'pipefail'
      - '-c'
      - |-
        gcloud beta run deploy fishing-map-`echo $BRANCH_NAME | sed -r 's,/,-,g'` --project $_RUN_PROJECT --image gcr.io/world-fishing-827/github.com/globalfishingwatch/fishing-map:$COMMIT_SHA \
        --region $_RUN_REGION --platform managed --set-env-vars BASIC_AUTH=$_BASIC_AUTH --allow-unauthenticated

images:
  - 'gcr.io/world-fishing-827/github.com/globalfishingwatch/fishing-map:$COMMIT_SHA'

timeout: 1800s
