steps:
  - name: 'gcr.io/kaniko-project/executor:latest'
    id: 'build'
    args:
      [
        '--no-push',
        '--cache-repo=gcr.io/world-fishing-827/github.com/globalfishingwatch/fishing-map',
        '--cache=true',
        '--build-arg',
        'REACT_APP_SPREADSHEET_CLIENT_EMAIL=$_REACT_APP_SPREADSHEET_CLIENT_EMAIL',
        '--build-arg',
        'REACT_APP_SPREADSHEET_PRIVATE_KEY=$_REACT_APP_SPREADSHEET_PRIVATE_KEY',
        '--build-arg',
        'REACT_APP_FEEDBACK_SPREADSHEET_ID=$_REACT_APP_FEEDBACK_SPREADSHEET_ID',
        '--build-arg',
        'REACT_APP_GOOGLE_TAG_MANAGER_KEY=$_REACT_APP_GOOGLE_TAG_MANAGER_KEY',
        '--build-arg',
        'REACT_APP_GOOGLE_UNIVERSAL_ANALYTICS_ID=$_REACT_APP_GOOGLE_UNIVERSAL_ANALYTICS_ID',
        '--build-arg',
        'REACT_APP_GOOGLE_MEASUREMENT_ID=$_REACT_APP_GOOGLE_MEASUREMENT_ID',
        '--build-arg',
        'REACT_APP_USE_LOCAL_DATAVIEWS=$_REACT_APP_USE_LOCAL_DATAVIEWS',
        '--build-arg',
        'REACT_APP_USE_LOCAL_DATASETS=$_REACT_APP_USE_LOCAL_DATASETS',
        '--build-arg',
        'REACT_APP_API_GATEWAY=$_REACT_APP_API_GATEWAY',
        '--build-arg',
        'REACT_APP_CARRIER_PORTAL_URL=$_REACT_APP_CARRIER_PORTAL_URL',
        '--build-arg',
        'REACT_APP_WORKSPACE_ENV=$_REACT_APP_WORKSPACE_ENV',
        '--build-arg',
        'BASIC_AUTH_USER=$_BASIC_AUTH_USER',
        '--build-arg',
        'BASIC_AUTH_PASS=$_BASIC_AUTH_PASS',
        '--target',
        'base',
        '-f',
        './applications/fishing-map/Dockerfile',
        '-c',
        './applications/fishing-map',
      ]

  - name: 'gcr.io/kaniko-project/executor:latest'
    id: 'test'
    args:
      [
        '--no-push',
        '--cache-repo=gcr.io/world-fishing-827/github.com/globalfishingwatch/fishing-map',
        '--cache=true',
        '--build-arg',
        'REACT_APP_SPREADSHEET_CLIENT_EMAIL=$_REACT_APP_SPREADSHEET_CLIENT_EMAIL',
        '--build-arg',
        'REACT_APP_SPREADSHEET_PRIVATE_KEY=$_REACT_APP_SPREADSHEET_PRIVATE_KEY',
        '--build-arg',
        'REACT_APP_FEEDBACK_SPREADSHEET_ID=$_REACT_APP_FEEDBACK_SPREADSHEET_ID',
        '--build-arg',
        'REACT_APP_GOOGLE_TAG_MANAGER_KEY=$_REACT_APP_GOOGLE_TAG_MANAGER_KEY',
        '--build-arg',
        'REACT_APP_GOOGLE_UNIVERSAL_ANALYTICS_ID=$_REACT_APP_GOOGLE_UNIVERSAL_ANALYTICS_ID',
        '--build-arg',
        'REACT_APP_GOOGLE_MEASUREMENT_ID=$_REACT_APP_GOOGLE_MEASUREMENT_ID',
        '--build-arg',
        'REACT_APP_USE_LOCAL_DATAVIEWS=$_REACT_APP_USE_LOCAL_DATAVIEWS',
        '--build-arg',
        'REACT_APP_USE_LOCAL_DATASETS=$_REACT_APP_USE_LOCAL_DATASETS',
        '--build-arg',
        'REACT_APP_API_GATEWAY=$_REACT_APP_API_GATEWAY',
        '--build-arg',
        'REACT_APP_CARRIER_PORTAL_URL=$_REACT_APP_CARRIER_PORTAL_URL',
        '--build-arg',
        'REACT_APP_WORKSPACE_ENV=$_REACT_APP_WORKSPACE_ENV',
        '--build-arg',
        'BASIC_AUTH_USER=$_BASIC_AUTH_USER',
        '--build-arg',
        'BASIC_AUTH_PASS=$_BASIC_AUTH_PASS',
        '--target',
        'test',
        '-f',
        './applications/fishing-map/Dockerfile',
        '-c',
        './applications/fishing-map',
      ]
    waitFor:
      - 'build'

  - name: 'gcr.io/kaniko-project/executor:latest'
    id: 'build-server'
    args:
      [
        '--destination=gcr.io/world-fishing-827/github.com/globalfishingwatch/fishing-map:$COMMIT_SHA',
        '--cache=true',
        '--build-arg',
        'REACT_APP_SPREADSHEET_CLIENT_EMAIL=$_REACT_APP_SPREADSHEET_CLIENT_EMAIL',
        '--build-arg',
        'REACT_APP_SPREADSHEET_PRIVATE_KEY=$_REACT_APP_SPREADSHEET_PRIVATE_KEY',
        '--build-arg',
        'REACT_APP_FEEDBACK_SPREADSHEET_ID=$_REACT_APP_FEEDBACK_SPREADSHEET_ID',
        '--build-arg',
        'REACT_APP_GOOGLE_TAG_MANAGER_KEY=$_REACT_APP_GOOGLE_TAG_MANAGER_KEY',
        '--build-arg',
        'REACT_APP_GOOGLE_UNIVERSAL_ANALYTICS_ID=$_REACT_APP_GOOGLE_UNIVERSAL_ANALYTICS_ID',
        '--build-arg',
        'REACT_APP_GOOGLE_MEASUREMENT_ID=$_REACT_APP_GOOGLE_MEASUREMENT_ID',
        '--build-arg',
        'REACT_APP_USE_LOCAL_DATAVIEWS=$_REACT_APP_USE_LOCAL_DATAVIEWS',
        '--build-arg',
        'REACT_APP_USE_LOCAL_DATASETS=$_REACT_APP_USE_LOCAL_DATASETS',
        '--build-arg',
        'REACT_APP_API_GATEWAY=$_REACT_APP_API_GATEWAY',
        '--build-arg',
        'REACT_APP_CARRIER_PORTAL_URL=$_REACT_APP_CARRIER_PORTAL_URL',
        '--build-arg',
        'REACT_APP_WORKSPACE_ENV=$_REACT_APP_WORKSPACE_ENV',
        '--build-arg',
        'BASIC_AUTH_USER=$_BASIC_AUTH_USER',
        '--build-arg',
        'BASIC_AUTH_PASS=$_BASIC_AUTH_PASS',
        '--target',
        'production',
        '-f',
        './applications/fishing-map/Dockerfile',
        '-c',
        './applications/fishing-map',
      ]
    waitFor:
      - 'build'

  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-eEuo'
      - 'pipefail'
      - '-c'
      - |-
        gcloud beta run deploy fishing-map-`echo $BRANCH_NAME | sed -r 's,/,-,g' | awk '{print tolower($0)}'` --project $_RUN_PROJECT --image gcr.io/world-fishing-827/github.com/globalfishingwatch/fishing-map:$COMMIT_SHA \
        --region $_RUN_REGION --platform managed --set-env-vars BASIC_AUTH=$_BASIC_AUTH --allow-unauthenticated
    waitFor:
      - 'build-server'

images:
  - 'gcr.io/world-fishing-827/github.com/globalfishingwatch/fishing-map:$COMMIT_SHA'

timeout: 1800s
