steps:
  - name: 'gcr.io/$PROJECT_ID/restore_cache'
    id: restore_cache
    waitFor: ['-']
    args:
      - '--bucket=gs://frontend-cache-dependencies'
      - '--key=yarn-$( checksum yarn.lock )'

  - id: 'install-yarn'
    waitFor: ['-']
    name: node:14
    entrypoint: bash
    args:
      - '-c'
      # if dependencies cache is not found then install all deps
      - |
        if [ ! -d "node_modules" ]; then
          yarn install --frozen-lockfile
        fi

  - id: 'save_cache'
    waitFor: ['install-yarn']
    name: 'gcr.io/$PROJECT_ID/save_cache'
    args:
      - '--bucket=gs://frontend-cache-dependencies'
      - '--key=yarn-$( checksum yarn.lock )'
      - '--path=./node_modules'

  - id: 'test'
    waitFor: ['install-yarn']
    name: node:14
    entrypoint: yarn
    args: ['nx', 'test', 'vessel-history']

timeout: 600s
