steps:
  - name: 'gcr.io/$PROJECT_ID/restore_cache'
    id: restore_cache
    waitFor: ['-']
    args:
    - '--bucket=gs://frontend-cache-dependencies/'
    - '--key=yarn-$( checksum yarn.lock )'

  - id: 'install-yarn'
    waitFor: ['-']
    name: node:14
    entrypoint: yarn
    args: ['install', '--frozen-lockfile']

  - id: 'save_cache'
    waitFor: ['install-yarn']
    name: 'gcr.io/$PROJECT_ID/save_cache'
    args:
    - '--bucket=gs://frontend-cache-dependencies'
    - '--key=yarn-$( checksum yarn.lock )'
    - '--path=./node_modules'
    waitFor:
    - build

  - id: 'test'
    waitFor: ['install-yarn']
    name: node:14
    entrypoint: yarn
    args: ['nx', 'test', 'vessel-history']

timeout: 600s
