steps:
  - id: 'download-cached-yarn-dependencies'
    name: gcr.io/cloud-builders/gsutil
    entrypoint: bash
    args:
      - '-c'
      - |
        gsutil cp gs://frontend-cache-dependencies/cache/yarn-dependencies.tgz yarn-dependencies.tgz || exit 0
        tar -zxf yarn-dependencies.tgz || exit 0

  - id: 'install-yarn'
    waitFor: ['download-cached-yarn-dependencies']
    name: node:14-alpine
    entrypoint: sh
    args:
      - '-c'
      - |
        apk add --no-cache git
        yarn install --frozen-lockfile

  - id: 'upload-cached-yarn-dependencies'
    waitFor: ['install-yarn']
    name: gcr.io/cloud-builders/gsutil
    entrypoint: bash
    args:
      - '-c'
      - |
        tar -zcf yarn-dependencies.tgz ./node_modules
        gsutil cp yarn-dependencies.tgz gs://frontend-cache-dependencies/cache/yarn-dependencies.tgz

  - id: 'test'
    waitFor: ['install-yarn']
    name: node:14-alpine
    entrypoint: yarn
    args: ['nx', 'test', 'vessel-history']

timeout: 600s
