import {
  DatasetCategory,
  DatasetStatus,
  DatasetTypes,
  DataviewCategory,
  DataviewType,
  EndpointId,
} from '@globalfishingwatch/api-types'
import type { UrlDataviewInstance } from '@globalfishingwatch/dataviews-client'

import { CONTEXT_LAYERS_IDS } from '../../data/config'

const dataviews: UrlDataviewInstance[] = [
  {
    id: CONTEXT_LAYERS_IDS.basemap,
    name: 'basemap',
    slug: 'basemap',
    app: 'fishing-map',
    config: {
      type: DataviewType.Basemap,
      color: '#6b67e5',
      layers: [
        {
          id: 'basemap_default',
          dataset: '',
        },
      ],
      visible: true,
    },
    datasetsConfig: [],
    description: 'basemap',
    dataviewId: 'basemap',
    datasets: [{ name: 'Landmass' } as any],
  },
  {
    id: CONTEXT_LAYERS_IDS.eez,
    name: 'EEZ',
    slug: 'eez',
    app: 'fishing-map',
    config: {
      type: DataviewType.Context,
      color: '#93c96c',
      layers: [
        {
          id: 'eez-areas',
          dataset: 'public-eez-areas',
        },
        {
          id: 'eez-boundaries',
          dataset: 'public-eez-boundaries',
        },
      ],
      visible: true,
    },
    datasetsConfig: [
      {
        query: [],
        params: [],
        endpoint: EndpointId.ContextTiles,
        datasetId: 'public-eez-areas',
      },
      {
        query: [],
        params: [],
        endpoint: EndpointId.ContextTiles,
        datasetId: 'public-eez-boundaries',
      },
    ],
    description:
      'Flanders Marine Institute (2019). Maritime Boundaries Geodatabase: Maritime Boundaries and Exclusive Economic Zones (200NM), version 11.',
    category: DataviewCategory.Context,
    dataviewId: 'eez',
    datasets: [
      {
        alias: null,
        id: 'public-eez-areas',
        name: 'EEZs',
        type: DatasetTypes.Context,
        description:
          "Exclusive economic zones (EEZs) extend up to 200 nautical miles from a country's coast. Flanders Marine Institute (2019). Maritime Boundaries Geodatabase: Maritime Boundaries and Exclusive Economic Zones (200NM), version 11. Source: marineregions.org.",
        endDate: '2023-05-01T00:00:00.000Z',
        unit: undefined,
        status: DatasetStatus.Done,
        importLogs: '',
        category: DatasetCategory.Context,
        subcategory: 'user',
        source:
          "<a href='https://www.marineregions.org' target='_blank' rel='noopener noreferrer'>Marine Regions</a>",
        ownerId: 0,
        ownerType: 'super-user',
        configuration: {
          id: '',
          max: 0,
          min: 0,
          ttl: 0,
          band: '',
          srid: 3857,
          scale: 0,
          table: 'eez-areas',
          translate: true,
          idProperty: 'MRGID_EEZ',
          tileOffset: 0,
          valueProperties: ['GEONAME'],
          propertyToInclude: '',
          disableInteraction: false,
          apiSupportedVersions: ['v2', 'v3'],
        },
        relatedDatasets: [],
        schema: {},
        fieldsAllowed: [],
        createdAt: '2023-01-16T15:58:52.698Z',
        endpoints: [
          {
            id: EndpointId.ContextTiles,
            description: 'Endpoint to retrieve tiles from context layers',
            downloadable: true,
            method: 'GET',
            pathTemplate: '/v3/datasets/public-eez-areas/context-layers/{{z}}/{{x}}/{{y}}',
            params: [
              {
                label: 'Z',
                id: 'z',
                type: 'number',
              },
              {
                label: 'X',
                id: 'x',
                type: 'number',
              },
              {
                label: 'Y',
                id: 'y',
                type: 'number',
              },
            ],
            query: [],
          },
          {
            id: EndpointId.ContextFeature,
            description: 'Endpoint to retrieve a feature from a context layer',
            downloadable: true,
            method: 'GET',
            pathTemplate: '/v3/datasets/public-eez-areas/context-layers/{{id}}',
            params: [
              {
                label: 'ID',
                id: 'id',
                type: 'number',
              },
            ],
            query: [
              {
                label: 'Simplify',
                id: 'id',
                type: 'number',
                required: false,
              },
            ],
          },
        ],
      },
      {
        alias: null,
        id: 'public-eez-boundaries',
        name: 'Areas boundaries for eez',
        type: DatasetTypes.Context,
        description:
          "EEZs boundaries are shown as solid lines for '200 NM', 'Treaty', 'Median line', 'Joint regime', 'Connection Line', 'Unilateral claim (undisputed)' and dashed lines for 'Joint regime', 'Unsettled', 'Unsettled median line' based on the 'LINE_TYPE' field. Flanders Marine Institute (2019). Maritime Boundaries Geodatabase: Maritime Boundaries and Exclusive Economic Zones (200NM), version 11. Source: marineregions.org",
        endDate: '2023-05-01T00:00:00.000Z',
        unit: undefined,
        status: DatasetStatus.Done,
        importLogs: '',
        category: DatasetCategory.Context,
        subcategory: 'user',
        source:
          "<a href='https://www.marineregions.org' target='_blank' rel='noopener noreferrer'>Marine Regions</a>",
        ownerId: 0,
        ownerType: 'super-user',
        configuration: {
          id: '',
          max: 0,
          min: 0,
          ttl: 0,
          band: '',
          srid: 3857,
          scale: 0,
          table: 'eez-boundaries',
          translate: true,
          idProperty: 'LINE_TYPE',
          valueProperties: ['LINE_TYPE'],
          disableInteraction: false,
          apiSupportedVersions: ['v2', 'v3'],
        },
        relatedDatasets: [],
        schema: {},
        fieldsAllowed: [],
        createdAt: '2023-01-16T15:58:51.214Z',
        endpoints: [
          {
            id: EndpointId.ContextTiles,
            description: 'Endpoint to retrieve tiles from context layers',
            downloadable: true,
            method: 'GET',
            pathTemplate: '/v3/datasets/public-eez-boundaries/context-layers/{{z}}/{{x}}/{{y}}',
            params: [
              {
                label: 'Z',
                id: 'z',
                type: 'number',
              },
              {
                label: 'X',
                id: 'x',
                type: 'number',
              },
              {
                label: 'Y',
                id: 'y',
                type: 'number',
              },
            ],
            query: [],
          },
          {
            id: EndpointId.ContextFeature,
            description: 'Endpoint to retrieve a feature from a context layer',
            downloadable: true,
            method: 'GET',
            pathTemplate: '/v3/datasets/public-eez-boundaries/context-layers/{{id}}',
            params: [
              {
                label: 'ID',
                id: 'id',
                type: 'number',
              },
            ],
            query: [
              {
                label: 'Simplify',
                id: 'id',
                type: 'number',
                required: false,
              },
            ],
          },
        ],
      },
    ],
  },
  {
    id: CONTEXT_LAYERS_IDS.mpa,
    name: 'MPA',
    slug: 'mpa',
    app: 'fishing-map',
    config: {
      type: DataviewType.Context,
      color: '#e5777c',
      layers: [
        {
          id: 'mpa',
          dataset: 'public-mpa-all',
        },
      ],
      visible: true,
    },
    datasetsConfig: [
      {
        query: [],
        params: [],
        endpoint: 'context-tiles',
        datasetId: 'public-mpa-all',
      },
    ],
    description: 'Marine Protected Areas',
    createdAt: '2023-01-16T15:35:15.939Z',
    updatedAt: '2023-02-21T10:18:14.627Z',
    category: DataviewCategory.Context,
    dataviewId: 'mpa',
    datasets: [
      {
        alias: null,
        id: 'public-mpa-all',
        name: 'MPAs',
        type: DatasetTypes.Context,
        description:
          "Marine protected areas (MPAs) are areas of the ocean set aside for long-term conservation. These can have different levels of protection, and the range of activities allowed or prohibited within their boundaries varies considerably. Source: World Database on Protected Areas. Last updated: November 2022. See more detailed <a href='https://globalfishingwatch.org/faqs/reference-layer-sources/' target='_blank' rel=noopener'>metadata information</a> for this layer.",
        endDate: '2025-04-01T00:00:00.000Z',
        status: DatasetStatus.Done,
        importLogs: '',
        category: DatasetCategory.Context,
        subcategory: 'user',
        source:
          "<a href='https://www.protectedplanet.net/' target='_blank' rel='noopener noreferrer'>Protected Planet WDPA</a>",
        ownerId: 0,
        ownerType: 'super-user',
        configuration: {
          id: '',
          max: 0,
          min: 0,
          ttl: 0,
          band: '',
          srid: 3857,
          scale: 0,
          table: 'mpa-all',
          filePath: 'dataset-upload-tmp-prod/865baed0-cd2f-44ee-99ba-f74fc4a1417a',
          translate: true,
          idProperty: 'WDPA_PID',
          valueProperties: ['NAME', 'DESIG'],
          disableInteraction: false,
          apiSupportedVersions: ['v2', 'v3'],
        },
        relatedDatasets: [],
        schema: {},
        fieldsAllowed: [],
        createdAt: '2023-01-16T15:58:52.451Z',
        endpoints: [
          {
            id: EndpointId.ContextTiles,
            description: 'Endpoint to retrieve tiles from context layers',
            downloadable: true,
            method: 'GET',
            pathTemplate: '/v3/datasets/public-mpa-all/context-layers/{{z}}/{{x}}/{{y}}',
            params: [
              {
                label: 'Z',
                id: 'z',
                type: 'number',
              },
              {
                label: 'X',
                id: 'x',
                type: 'number',
              },
              {
                label: 'Y',
                id: 'y',
                type: 'number',
              },
            ],
            query: [],
          },
          {
            id: EndpointId.ContextFeature,
            description: 'Endpoint to retrieve a feature from a context layer',
            downloadable: true,
            method: 'GET',
            pathTemplate: '/v3/datasets/public-mpa-all/context-layers/{{id}}',
            params: [
              {
                label: 'ID',
                id: 'id',
                type: 'number',
              },
            ],
            query: [
              {
                label: 'Simplify',
                id: 'id',
                type: 'number',
                required: false,
              },
            ],
          },
        ],
      },
    ],
  },
  {
    id: CONTEXT_LAYERS_IDS.rfmo,
    name: 'Tuna RFMO areas',
    slug: 'tuna-rfmo-areas',
    app: 'fishing-map',
    config: {
      type: DataviewType.Context,
      color: '#6b67e5',
      layers: [
        {
          id: 'tuna-rfmo',
          dataset: 'public-rfmo',
        },
      ],
      visible: true,
    },
    datasetsConfig: [
      {
        query: [],
        params: [],
        endpoint: 'context-tiles',
        datasetId: 'public-rfmo',
      },
    ],
    description:
      'RFMO stands for Regional Fishery Management Organization. These organizations are international organizations formed by countries with a shared interest in managing or conserving an area’s fish stock. Some RFMOs manage all the fish stocks found in a specific area, while others focus on particular highly migratory species, notably tuna, throughout vast geographical areas. The RFMO Layer on the Global Fishing Watch map currently includes the five tuna RFMOs.',
    createdAt: '2023-01-16T15:17:31.827Z',
    updatedAt: '2023-02-17T13:06:43.388Z',
    category: DataviewCategory.Context,
    dataviewId: 'tuna-rfmo-areas',
    datasets: [
      {
        alias: null,
        id: 'public-rfmo',
        name: 'RFMO',
        type: DatasetTypes.Context,
        description:
          "Regional fisheries management organizations (RFMOs) are international bodies formed by countries with a shared interest in managing or conserving fish stocks in a particular region. Some manage all the fish stocks found in a given area, while others focus on specific highly migratory species, notably tuna. The regional fisheries management organization on the Global Fishing Watch map currently includes the five tuna regional fisheries management organizations. See more detailed <a href='https://globalfishingwatch.org/faqs/reference-layer-sources/' target='_blank' rel=noopener'>metadata information</a> for this layer.",
        endDate: '2023-05-01T00:00:00.000Z',
        status: DatasetStatus.Done,
        importLogs: '',
        category: DatasetCategory.Context,
        subcategory: 'user',
        source: 'GFW',
        ownerId: 0,
        ownerType: 'super-user',
        configuration: {
          id: '',
          max: 0,
          min: 0,
          ttl: 0,
          band: '',
          srid: 3857,
          scale: 0,
          table: 'rfmo-areas',
          translate: true,
          idProperty: 'ID',
          geometryType: undefined,
          valueProperties: ['ID'],
          propertyToInclude: '',
          disableInteraction: false,
          apiSupportedVersions: ['v2'],
        },
        relatedDatasets: [],
        schema: {
          ID: {
            enum: [
              'APFIC',
              'BOBP-IGO',
              'CCAMLR',
              'CCBSP',
              'CCSBT',
              'CCSBT Primary Area',
              'COREP',
              'CPPS',
              'CRFM',
              'CTMFM',
              'FCWC',
              'FFA',
              'GFCM',
              'IATTC',
              'ICCAT',
              'ICES',
              'IOTC',
              'IPHC',
              'LTA',
              'NAFO',
              'NAMMCO',
              'NASCO',
              'NEAFC',
              'NPAFC',
              'NPFC',
              'OSPESCA',
              'PERSGA',
              'PICES',
              'RECOFI',
              'SEAFDEC',
              'SIOFA',
              'SPC',
              'SPRFMO',
              'SRFC',
              'SWIOFC',
              'WCPFC',
            ],
            type: 'string',
          },
        },
        fieldsAllowed: ['ID'],
        createdAt: '2023-01-16T15:58:52.580Z',
        endpoints: [
          {
            id: EndpointId.ContextTiles,
            description: 'Endpoint to retrieve tiles from context layers',
            downloadable: true,
            method: 'GET',
            pathTemplate: '/v3/datasets/public-rfmo/context-layers/{{z}}/{{x}}/{{y}}',
            params: [
              {
                label: 'Z',
                id: 'z',
                type: 'number',
              },
              {
                label: 'X',
                id: 'x',
                type: 'number',
              },
              {
                label: 'Y',
                id: 'y',
                type: 'number',
              },
            ],
            query: [],
          },
          {
            id: EndpointId.ContextFeature,
            description: 'Endpoint to retrieve a feature from a context layer',
            downloadable: true,
            method: 'GET',
            pathTemplate: '/v3/datasets/public-rfmo/context-layers/{{id}}',
            params: [
              {
                label: 'ID',
                id: 'id',
                type: 'number',
              },
            ],
            query: [
              {
                label: 'Simplify',
                id: 'id',
                type: 'number',
                required: false,
              },
            ],
          },
        ],
      },
    ],
  },
]

export default dataviews
