// Workaround to hardcode layers using mapbox-syle directly instead of layer-composer resolvers

const API_GATEWAY =
  process.env.REACT_APP_API_GATEWAY || `https://gateway.api.dev.globalfishingwatch.org`

export const contextSourceStyle = {
  'context-layer-rfmo__cp_rfmo': {
    type: 'vector',
    promoteId: 'ID',
    tiles: [`${API_GATEWAY}/v2/datasets/public-rfmo/context-layer-v1/{z}/{x}/{y}?`],
    maxzoom: 9,
    attribution: 'GFW',
  },
  'context-layer-mpa__mpant': {
    type: 'vector',
    promoteId: 'WDPA_PID',
    tiles: [`${API_GATEWAY}/v2/datasets/public-mpa-all/context-layer-v1/{z}/{x}/{y}?`],
    maxzoom: 9,
    attribution:
      "<a href='https://www.protectedplanet.net/' target='_blank' rel='noopener noreferrer'>Protected Planet WDPA</a>",
  },
  'context-layer-eez__eez-boundaries': {
    type: 'vector',
    promoteId: 'LINE_TYPE',
    tiles: [`${API_GATEWAY}/v2/datasets/public-eez-boundaries/context-layer-v1/{z}/{x}/{y}?`],
    maxzoom: 9,
    attribution:
      "<a href='https://www.marineregions.org' target='_blank' rel='noopener noreferrer'>Marine Regions</a>",
  },
  'context-layer-eez__eez-areas': {
    type: 'vector',
    promoteId: 'MRGID_EEZ',
    tiles: [`${API_GATEWAY}/v2/datasets/public-eez-areas/context-layer-v1/{z}/{x}/{y}?`],
    maxzoom: 9,
    attribution:
      "<a href='https://www.marineregions.org' target='_blank' rel='noopener noreferrer'>Marine Regions</a>",
  },
}

export const contextLayersStyle = [
  {
    id: 'context-layer-rfmo__cp_rfmo',
    type: 'fill',
    paint: {
      'fill-color': [
        'case',
        ['boolean', ['feature-state', 'click'], false],
        'rgba(0, 0, 0, 0.3)',
        ['boolean', ['feature-state', 'highlight'], false],
        'rgba(0, 0, 0, 0.3)',
        'transparent',
      ],
      'fill-outline-color': 'transparent',
      'fill-opacity': 1,
    },
    layout: {
      visibility: 'visible',
    },
    metadata: {
      interactive: false,
      group: 'outlinePolygonsBackground',
      sourceLayer: 'main',
      color: '#6b67e5',
      layer: 'cp_rfmo',
      generatorId: 'context-layer-rfmo__cp_rfmo',
      datasetId: 'public-rfmo',
      promoteId: 'ID',
      valueProperties: ['ID'],
      generatorType: 'CONTEXT',
    },
    source: 'context-layer-rfmo__cp_rfmo',
    'source-layer': 'main',
  },
  {
    id: 'context-layer-mpa__mpant',
    type: 'fill',
    paint: {
      'fill-color': [
        'case',
        ['boolean', ['feature-state', 'click'], false],
        'rgba(0, 0, 0, 0.3)',
        ['boolean', ['feature-state', 'highlight'], false],
        'rgba(0, 0, 0, 0.3)',
        'transparent',
      ],
      'fill-outline-color': 'transparent',
      'fill-opacity': 1,
    },
    layout: {
      visibility: 'visible',
    },
    metadata: {
      interactive: false,
      group: 'outlinePolygonsBackground',
      sourceLayer: 'main',
      color: '#e5777c',
      layer: 'mpa',
      generatorId: 'context-layer-mpa__mpant',
      datasetId: 'public-mpa-all',
      promoteId: 'WDPA_PID',
      valueProperties: ['NAME', 'DESIG'],
      generatorType: 'CONTEXT',
    },
    source: 'context-layer-mpa__mpant',
    'source-layer': 'main',
  },
  {
    id: 'context-layer-eez__eez-areas',
    type: 'fill',
    paint: {
      'fill-color': [
        'case',
        ['boolean', ['feature-state', 'click'], false],
        'rgba(0, 0, 0, 0.3)',
        ['boolean', ['feature-state', 'highlight'], false],
        'rgba(0, 0, 0, 0.3)',
        'transparent',
      ],
      'fill-outline-color': 'transparent',
      'fill-opacity': 1,
    },
    layout: {
      visibility: 'visible',
    },
    metadata: {
      interactive: false,
      group: 'outlinePolygonsBackground',
      sourceLayer: 'main',
      color: '#069688',
      layer: 'eez-areas',
      generatorId: 'context-layer-eez__eez-areas',
      datasetId: 'public-eez-areas',
      promoteId: 'MRGID_EEZ',
      valueProperties: ['GEONAME'],
      generatorType: 'CONTEXT',
    },
    source: 'context-layer-eez__eez-areas',
    'source-layer': 'main',
  },
  {
    id: 'cp_rfmo_linecontext-layer-rfmo__cp_rfmo',
    type: 'line',
    paint: {
      'line-color': [
        'case',
        ['boolean', ['feature-state', 'hover'], false],
        'white',
        ['boolean', ['feature-state', 'click'], false],
        'white',
        ['boolean', ['feature-state', 'highlight'], false],
        'white',
        '#6b67e5',
      ],
      'line-opacity': 1,
    },
    layout: {
      'line-cap': 'round',
      'line-join': 'round',
      visibility: 'visible',
    },
    metadata: {
      interactive: false,
      group: 'outlinePolygons',
      sourceLayer: 'main',
      color: '#6b67e5',
      layer: 'cp_rfmo',
      generatorId: 'context-layer-rfmo__cp_rfmo',
      datasetId: 'public-rfmo',
      promoteId: 'ID',
      valueProperties: ['ID'],
      generatorType: 'CONTEXT',
    },
    source: 'context-layer-rfmo__cp_rfmo',
    'source-layer': 'main',
  },
  {
    id: 'mpa_linecontext-layer-mpa__mpant',
    type: 'line',
    paint: {
      'line-color': [
        'case',
        ['boolean', ['feature-state', 'hover'], false],
        'white',
        ['boolean', ['feature-state', 'click'], false],
        'white',
        ['boolean', ['feature-state', 'highlight'], false],
        'white',
        '#e5777c',
      ],
      'line-opacity': 1,
    },
    layout: {
      'line-cap': 'round',
      'line-join': 'round',
      visibility: 'visible',
    },
    metadata: {
      interactive: false,
      group: 'outlinePolygons',
      sourceLayer: 'main',
      color: '#e5777c',
      layer: 'mpa',
      generatorId: 'context-layer-mpa__mpant',
      datasetId: 'public-mpa-all',
      promoteId: 'WDPA_PID',
      valueProperties: ['NAME', 'DESIG'],
      generatorType: 'CONTEXT',
    },
    source: 'context-layer-mpa__mpant',
    'source-layer': 'main',
  },
  {
    id: 'eez-boundaries_rest_linescontext-layer-eez__eez-boundaries',
    type: 'line',
    paint: {
      'line-color': [
        'case',
        ['boolean', ['feature-state', 'hover'], false],
        'white',
        ['boolean', ['feature-state', 'click'], false],
        'white',
        ['boolean', ['feature-state', 'highlight'], false],
        'white',
        '#069688',
      ],
      'line-opacity': 1,
    },
    layout: {
      'line-cap': 'round',
      'line-join': 'round',
      visibility: 'visible',
    },
    metadata: {
      interactive: false,
      group: 'outlinePolygons',
      sourceLayer: 'main',
      color: '#069688',
      layer: 'eez-boundaries',
      generatorId: 'context-layer-eez__eez-boundaries',
      datasetId: 'public-eez-boundaries',
      promoteId: 'LINE_TYPE',
      valueProperties: ['LINE_TYPE'],
      generatorType: 'CONTEXT',
    },
    filter: [
      'match',
      ['get', 'LINE_TYPE'],
      [
        '200 NM',
        'Treaty',
        'Median line',
        'Joint regime',
        'Connection Line',
        'Unilateral claim (undisputed)',
      ],
      true,
      false,
    ],
    source: 'context-layer-eez__eez-boundaries',
    'source-layer': 'main',
  },
  {
    id: 'eez-boundaries_special_linescontext-layer-eez__eez-boundaries',
    type: 'line',
    paint: {
      'line-color': [
        'case',
        ['boolean', ['feature-state', 'hover'], false],
        'white',
        ['boolean', ['feature-state', 'click'], false],
        'white',
        ['boolean', ['feature-state', 'highlight'], false],
        'white',
        '#069688',
      ],
      'line-dasharray': [2, 4],
      'line-opacity': 1,
    },
    layout: {
      'line-cap': 'round',
      'line-join': 'round',
      visibility: 'visible',
    },
    metadata: {
      interactive: false,
      group: 'outlinePolygons',
      sourceLayer: 'main',
      color: '#069688',
      layer: 'eez-boundaries',
      generatorId: 'context-layer-eez__eez-boundaries',
      datasetId: 'public-eez-boundaries',
      promoteId: 'LINE_TYPE',
      valueProperties: ['LINE_TYPE'],
      generatorType: 'CONTEXT',
    },
    filter: [
      'match',
      ['get', 'LINE_TYPE'],
      [
        '200 NM',
        'Treaty',
        'Median line',
        'Joint regime',
        'Connection Line',
        'Unilateral claim (undisputed)',
      ],
      false,
      true,
    ],
    source: 'context-layer-eez__eez-boundaries',
    'source-layer': 'main',
  },
  {
    id: 'cp_rfmo_highlightcontext-layer-rfmo__cp_rfmo',
    type: 'line',
    paint: {
      'line-color': [
        'case',
        ['boolean', ['feature-state', 'hover'], false],
        'white',
        ['boolean', ['feature-state', 'click'], false],
        'white',
        ['boolean', ['feature-state', 'highlight'], false],
        'white',
        'transparent',
      ],
      'line-opacity': 1,
    },
    layout: {
      'line-cap': 'round',
      'line-join': 'round',
      visibility: 'visible',
    },
    metadata: {
      interactive: false,
      group: 'outlinePolygonsHighlighted',
      sourceLayer: 'main',
      color: '#6b67e5',
      layer: 'cp_rfmo',
      generatorId: 'context-layer-rfmo__cp_rfmo',
      datasetId: 'public-rfmo',
      promoteId: 'ID',
      valueProperties: ['ID'],
      generatorType: 'CONTEXT',
    },
    source: 'context-layer-rfmo__cp_rfmo',
    'source-layer': 'main',
  },
  {
    id: 'mpa_highlightcontext-layer-mpa__mpant',
    type: 'line',
    paint: {
      'line-color': [
        'case',
        ['boolean', ['feature-state', 'hover'], false],
        'white',
        ['boolean', ['feature-state', 'click'], false],
        'white',
        ['boolean', ['feature-state', 'highlight'], false],
        'white',
        'transparent',
      ],
      'line-opacity': 1,
    },
    layout: {
      'line-cap': 'round',
      'line-join': 'round',
      visibility: 'visible',
    },
    metadata: {
      interactive: false,
      group: 'outlinePolygonsHighlighted',
      sourceLayer: 'main',
      color: '#e5777c',
      layer: 'mpa',
      generatorId: 'context-layer-mpa__mpant',
      datasetId: 'public-mpa-all',
      promoteId: 'WDPA_PID',
      valueProperties: ['NAME', 'DESIG'],
      generatorType: 'CONTEXT',
    },
    source: 'context-layer-mpa__mpant',
    'source-layer': 'main',
  },
  {
    id: 'eez-areas_highlightcontext-layer-eez__eez-areas',
    type: 'line',
    paint: {
      'line-color': [
        'case',
        ['boolean', ['feature-state', 'hover'], false],
        'white',
        ['boolean', ['feature-state', 'click'], false],
        'white',
        ['boolean', ['feature-state', 'highlight'], false],
        'white',
        'transparent',
      ],
      'line-opacity': 1,
    },
    layout: {
      'line-cap': 'round',
      'line-join': 'round',
      visibility: 'visible',
    },
    metadata: {
      interactive: false,
      group: 'outlinePolygonsHighlighted',
      sourceLayer: 'main',
      color: '#069688',
      layer: 'eez-areas',
      generatorId: 'context-layer-eez__eez-areas',
      datasetId: 'public-eez-areas',
      promoteId: 'MRGID_EEZ',
      valueProperties: ['GEONAME'],
      generatorType: 'CONTEXT',
    },
    source: 'context-layer-eez__eez-areas',
    'source-layer': 'main',
  },
]

export function getVisibleContextLayers(hiddenLayers = [] as string[]) {
  if (!hiddenLayers.filter(Boolean).length) return contextLayersStyle
  return contextLayersStyle.filter(
    (layer) => !hiddenLayers.some((hiddenLayer) => layer.id.includes(hiddenLayer))
  )
}
