import { initReactI18next } from 'react-i18next'
import i18n, { type Resource } from 'i18next'
import LanguageDetector from 'i18next-browser-languagedetector'
import Backend from 'i18next-http-backend'

import { PATH_BASENAME } from 'data/config'
import { WORKSPACE_ENV } from 'data/workspaces'
import {
  DEFAULT_NAMESPACE,
  FALLBACK_LNG,
  IS_I18N_DEV_ENV,
  normalizeI18nLanguage,
  SUPPORTED_LANGUAGES,
} from 'features/i18n/i18n.config'
import { getDehydratedRootI18nState } from 'features/i18n/i18n.dehydrated-state'
import type { I18nServerState } from 'features/i18n/i18n.server'
import { Locale } from 'types'

export { CROWDIN_IN_CONTEXT_LANG, DEFAULT_NAMESPACE, FALLBACK_LNG } from 'features/i18n/i18n.config'
export { IS_I18N_TEST_ENV as IS_TEST_ENV } from 'features/i18n/i18n.config'

export const LocaleLabels = [
  { id: Locale.en, label: 'English' },
  { id: Locale.es, label: 'Español' },
  { id: Locale.fr, label: 'Français' },
  // { id: Locale.id, label: 'Bahasa Indonesia' },
  { id: Locale.pt, label: 'Português' },
]

const USE_LOCAL_SHARED_LABELS = IS_I18N_DEV_ENV

const NPM_SCOPE = WORKSPACE_ENV === 'production' ? 'stable' : 'latest'
// Injected by Vite `define` at build time — stable across page loads, changes per deploy
// so locale JSON can be cached by the browser/CDN. Undefined when define isn't applied (vitest).
const UNIQUE_BUILD_ID = typeof __BUILD_ID__ !== 'undefined' ? __BUILD_ID__ : 'dev'

const SHARED_LABELS_PATH = USE_LOCAL_SHARED_LABELS
  ? 'http://localhost:8000'
  : `https://cdn.jsdelivr.net/npm/@globalfishingwatch/i18n-labels@${NPM_SCOPE}`

const PACKAGE_NAMESPACES = ['flags', 'timebar']

// Read TanStack Router's dehydrated root-loader data before React hydrates.
const ssrState: I18nServerState | undefined = getDehydratedRootI18nState()

export function getLoadedI18nState(): I18nServerState | undefined {
  if (!i18n.isInitialized) {
    return undefined
  }

  const initialLanguage = normalizeI18nLanguage(i18n.resolvedLanguage || i18n.language)
  const initialI18nStore = i18n.services.resourceStore.data as I18nServerState['initialI18nStore']

  if (!initialLanguage || !initialI18nStore?.[initialLanguage]) {
    return undefined
  }

  return {
    initialI18nStore,
    initialLanguage,
  }
}

if (typeof window !== 'undefined') {
  i18n
    // load translation using http -> see /public/locales
    // learn more: https://github.com/i18next/i18next-http-backend
    .use(Backend)
    // detect user language
    // learn more: https://github.com/i18next/i18next-browser-languageDetector
    .use(LanguageDetector)
    // pass the i18n instance to react-i18next.
    .use(initReactI18next)
    // init i18next
    // for all options read: https://www.i18next.com/overview/configuration-options
    .init({
      load: 'languageOnly',
      nonExplicitSupportedLngs: true,
      ...(ssrState && {
        resources: ssrState.initialI18nStore as Resource,
        lng: ssrState.initialLanguage,
        // Resources only contain the SSR language — let the backend load others on demand
        partialBundledLanguages: true,
        // Finish init before React hydrates; SSR already picked the language.
        initAsync: false,
      }),
      backend: {
        loadPath: (lngs: string[], namespaces: string[]) => {
          if (namespaces.some((namespace: string) => PACKAGE_NAMESPACES.includes(namespace))) {
            // For datasets we can't use the source file as it's autogenerated by the API so we use the english source
            return `${SHARED_LABELS_PATH}/{{lng}}/{{ns}}.json?v=${UNIQUE_BUILD_ID}`
          }
          return `${PATH_BASENAME}/locales/{{lng}}/{{ns}}.json?v=${UNIQUE_BUILD_ID}`
        },
      },
      detection: {
        // With SSR state, `lng` is set explicitly so the detection order is never consulted
        // (keeps the SSR language during hydration — navigator can be en-IN while SSR used en).
        order: ssrState ? [] : ['cookie', 'localStorage', 'navigator', 'htmlTag'],
        // Caches must stay on regardless: i18n.changeLanguage persists the choice here,
        // and the server reads the `i18next` cookie to pick the SSR language on reload.
        caches: ['cookie', 'localStorage'],
        cookieOptions: { path: '/', sameSite: 'lax' },
      },
      ns: ['translations', 'flags', 'timebar', 'workspaces'],
      defaultNS: DEFAULT_NAMESPACE,
      fallbackLng: FALLBACK_LNG,
      supportedLngs: SUPPORTED_LANGUAGES,
      debug: import.meta.env.VITE_I18N_DEBUG === 'true',
      interpolation: {
        escapeValue: false, // not needed for react as it escapes by default,
      },
      react: {
        useSuspense: false,
        bindI18n: 'languageChanged loaded',
      },
    })
} else {
  // Server: React rendering uses the per-request instance from I18nSSRProvider, but
  // module-level `t` consumers (slices/selectors evaluated during SSR) still need this
  // global instance initialized. Sync init, no plugins — avoids the LanguageDetector and
  // http-backend doing wasted work (failed relative-URL fetches) in the Node bundle.
  i18n.init({
    lng: FALLBACK_LNG,
    fallbackLng: FALLBACK_LNG,
    supportedLngs: SUPPORTED_LANGUAGES,
    ns: [DEFAULT_NAMESPACE],
    defaultNS: DEFAULT_NAMESPACE,
    resources: {},
    initAsync: false,
    interpolation: { escapeValue: false },
  })
}

const t = i18n.t.bind(i18n)

export { t }

export default i18n
