import { initReactI18next } from 'react-i18next'
import i18n, { type Resource } from 'i18next'
import LanguageDetector from 'i18next-browser-languagedetector'
import Backend from 'i18next-http-backend'

import { IS_DEVELOPMENT_ENV, PATH_BASENAME } from 'data/config'
import { WORKSPACE_ENV } from 'data/workspaces'
import { Locale } from 'types'

export const CROWDIN_IN_CONTEXT_LANG = 'val'

export const LocaleLabels = [
  { id: Locale.en, label: 'English' },
  { id: Locale.es, label: 'Español' },
  { id: Locale.fr, label: 'Français' },
  { id: Locale.id, label: 'Bahasa Indonesia' },
  { id: Locale.pt, label: 'Portuguese' },
]

export const DEFAULT_NAMESPACE = 'translations'
export const FALLBACK_LNG = IS_DEVELOPMENT_ENV ? 'source' : Locale.en

const NPM_SCOPE = WORKSPACE_ENV === 'production' ? 'stable' : 'latest'
const UNIQUE_BUILD_ID = Date.now()

const SHARED_LABELS_PATH = IS_DEVELOPMENT_ENV
  ? 'http://localhost:8000'
  : `https://cdn.jsdelivr.net/npm/@globalfishingwatch/i18n-labels@${NPM_SCOPE}`

const PACKAGE_NAMESPACES = ['flags', 'datasets', 'timebar']
const SUPPORTED_LANGUAGES = [...Object.values(Locale), CROWDIN_IN_CONTEXT_LANG]
if (IS_DEVELOPMENT_ENV) {
  SUPPORTED_LANGUAGES.push('source')
}

// TODO:RR clean this up and get client working to be able to change language on the fly
/**
 * SSR i18n state - read from TanStack Router's dehydrated loader data.
 * The root route loader returns i18nState, which is available at $_TSR.router.matches
 * before the app hydrates. We find the root match (id starts with __root__) and use its loader data.
 */
function getSsrI18nState():
  | {
      initialI18nStore: Record<string, Record<string, Record<string, unknown>>>
      initialLanguage: string
    }
  | undefined {
  if (typeof window === 'undefined') return undefined
  const router = (
    window as { $_TSR?: { router?: { matches?: { i?: string; l?: { i18nState?: unknown } }[] } } }
  ).$_TSR?.router
  const rootMatch = router?.matches?.find((m) => m.i?.startsWith?.('__root__'))
  return rootMatch?.l?.i18nState as
    | {
        initialI18nStore: Record<string, Record<string, Record<string, unknown>>>
        initialLanguage: string
      }
    | undefined
}
const ssrState = getSsrI18nState()

i18n
  // load translation using http -> see /public/locales
  // learn more: https://github.com/i18next/i18next-http-backend
  .use(Backend)
  // detect user language
  // learn more: https://github.com/i18next/i18next-browser-languageDetector
  .use(LanguageDetector)
  // pass the i18n instance to react-i18next.
  .use(initReactI18next)
  // init i18next
  // for all options read: https://www.i18next.com/overview/configuration-options
  .init({
    ...(ssrState && {
      resources: ssrState.initialI18nStore as Resource,
      lng: ssrState.initialLanguage,
    }),
    backend: {
      loadPath: (lngs: string[], namespaces: string[]) => {
        if (namespaces.some((namespace: string) => PACKAGE_NAMESPACES.includes(namespace))) {
          // For datasets we can't use the source file as it's autogenerated by the API so we use the english source
          const lng = namespaces.includes('datasets') && lngs.includes('source') ? 'en' : '{{lng}}'
          return `${SHARED_LABELS_PATH}/${lng}/{{ns}}.json?v=${UNIQUE_BUILD_ID}`
        }
        return `${PATH_BASENAME}/locales/{{lng}}/{{ns}}.json?v=${UNIQUE_BUILD_ID}`
      },
    },
    ns: ['translations', 'flags', 'datasets', 'timebar', 'workspaces'],
    defaultNS: DEFAULT_NAMESPACE,
    fallbackLng: FALLBACK_LNG,
    supportedLngs: SUPPORTED_LANGUAGES,
    debug: import.meta.env.VITE_I18N_DEBUG === 'true',
    interpolation: {
      escapeValue: false, // not needed for react as it escapes by default,
      // format: (value, format, lng) => {
      //   if (format === 'intlDate') {
      //     return new Intl.DateTimeFormat(lng).format(value)
      //   }
      //   return value
      // },
    },
    react: {
      // wait: true,
      useSuspense: false,
    },
  })

// @ts-ignore - avoids loop error
const t = i18n.t.bind(i18n)

export { t }

export default i18n
