/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as ApiFeedbackRouteImport } from './routes/api/feedback'
import { Route as ApiDownloadSurveyRouteImport } from './routes/api/downloadSurvey'
import { Route as ApiCorrectionsRouteImport } from './routes/api/corrections'
import { Route as ApiAuthRouteImport } from './routes/api/auth'
import { Route as AppVesselSearchRouteImport } from './routes/_app/vessel-search'
import { Route as AppUserRouteImport } from './routes/_app/user'
import { Route as ApiWorkspacesGeneratorIndexRouteImport } from './routes/api/workspaces-generator/index'
import { Route as ApiOceanAreasIndexRouteImport } from './routes/api/ocean-areas/index'
import { Route as AppCategoryIndexRouteImport } from './routes/_app/$category/index'
import { Route as ApiOceanAreasSearchRouteImport } from './routes/api/ocean-areas/search'
import { Route as ApiOceanAreasNameRouteImport } from './routes/api/ocean-areas/name'
import { Route as AppVesselVesselIdRouteImport } from './routes/_app/vessel.$vesselId'
import { Route as AppReportReportIdRouteImport } from './routes/_app/report.$reportId'
import { Route as AppCategoryWorkspaceIdRouteImport } from './routes/_app/$category/$workspaceId'
import { Route as ApiTrackCorrectionsWorkspaceIdIndexRouteImport } from './routes/api/track-corrections/$workspaceId/index'
import { Route as AppCategoryWorkspaceIdIndexRouteImport } from './routes/_app/$category/$workspaceId/index'
import { Route as ApiTrackCorrectionsWorkspaceIdIssueIdRouteImport } from './routes/api/track-corrections/$workspaceId/$issueId'
import { Route as AppCategoryWorkspaceIdVesselSearchRouteImport } from './routes/_app/$category/$workspaceId/vessel-search'
import { Route as AppCategoryWorkspaceIdReportIndexRouteImport } from './routes/_app/$category/$workspaceId/report/index'
import { Route as AppCategoryWorkspaceIdVesselVesselIdRouteImport } from './routes/_app/$category/$workspaceId/vessel.$vesselId'
import { Route as AppCategoryWorkspaceIdVesselGroupReportVesselGroupIdRouteImport } from './routes/_app/$category/$workspaceId/vessel-group-report.$vesselGroupId'
import { Route as AppCategoryWorkspaceIdPortsReportPortIdRouteImport } from './routes/_app/$category/$workspaceId/ports-report.$portId'
import { Route as AppCategoryWorkspaceIdReportDatasetIdIndexRouteImport } from './routes/_app/$category/$workspaceId/report/$datasetId/index'
import { Route as AppCategoryWorkspaceIdReportDatasetIdAreaIdRouteImport } from './routes/_app/$category/$workspaceId/report/$datasetId/$areaId'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const ApiFeedbackRoute = ApiFeedbackRouteImport.update({
  id: '/api/feedback',
  path: '/api/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDownloadSurveyRoute = ApiDownloadSurveyRouteImport.update({
  id: '/api/downloadSurvey',
  path: '/api/downloadSurvey',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCorrectionsRoute = ApiCorrectionsRouteImport.update({
  id: '/api/corrections',
  path: '/api/corrections',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthRoute = ApiAuthRouteImport.update({
  id: '/api/auth',
  path: '/api/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppVesselSearchRoute = AppVesselSearchRouteImport.update({
  id: '/vessel-search',
  path: '/vessel-search',
  getParentRoute: () => AppRoute,
} as any)
const AppUserRoute = AppUserRouteImport.update({
  id: '/user',
  path: '/user',
  getParentRoute: () => AppRoute,
} as any)
const ApiWorkspacesGeneratorIndexRoute =
  ApiWorkspacesGeneratorIndexRouteImport.update({
    id: '/api/workspaces-generator/',
    path: '/api/workspaces-generator/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiOceanAreasIndexRoute = ApiOceanAreasIndexRouteImport.update({
  id: '/api/ocean-areas/',
  path: '/api/ocean-areas/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppCategoryIndexRoute = AppCategoryIndexRouteImport.update({
  id: '/$category/',
  path: '/$category/',
  getParentRoute: () => AppRoute,
} as any)
const ApiOceanAreasSearchRoute = ApiOceanAreasSearchRouteImport.update({
  id: '/api/ocean-areas/search',
  path: '/api/ocean-areas/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOceanAreasNameRoute = ApiOceanAreasNameRouteImport.update({
  id: '/api/ocean-areas/name',
  path: '/api/ocean-areas/name',
  getParentRoute: () => rootRouteImport,
} as any)
const AppVesselVesselIdRoute = AppVesselVesselIdRouteImport.update({
  id: '/vessel/$vesselId',
  path: '/vessel/$vesselId',
  getParentRoute: () => AppRoute,
} as any)
const AppReportReportIdRoute = AppReportReportIdRouteImport.update({
  id: '/report/$reportId',
  path: '/report/$reportId',
  getParentRoute: () => AppRoute,
} as any)
const AppCategoryWorkspaceIdRoute = AppCategoryWorkspaceIdRouteImport.update({
  id: '/$category/$workspaceId',
  path: '/$category/$workspaceId',
  getParentRoute: () => AppRoute,
} as any)
const ApiTrackCorrectionsWorkspaceIdIndexRoute =
  ApiTrackCorrectionsWorkspaceIdIndexRouteImport.update({
    id: '/api/track-corrections/$workspaceId/',
    path: '/api/track-corrections/$workspaceId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppCategoryWorkspaceIdIndexRoute =
  AppCategoryWorkspaceIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppCategoryWorkspaceIdRoute,
  } as any)
const ApiTrackCorrectionsWorkspaceIdIssueIdRoute =
  ApiTrackCorrectionsWorkspaceIdIssueIdRouteImport.update({
    id: '/api/track-corrections/$workspaceId/$issueId',
    path: '/api/track-corrections/$workspaceId/$issueId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppCategoryWorkspaceIdVesselSearchRoute =
  AppCategoryWorkspaceIdVesselSearchRouteImport.update({
    id: '/vessel-search',
    path: '/vessel-search',
    getParentRoute: () => AppCategoryWorkspaceIdRoute,
  } as any)
const AppCategoryWorkspaceIdReportIndexRoute =
  AppCategoryWorkspaceIdReportIndexRouteImport.update({
    id: '/report/',
    path: '/report/',
    getParentRoute: () => AppCategoryWorkspaceIdRoute,
  } as any)
const AppCategoryWorkspaceIdVesselVesselIdRoute =
  AppCategoryWorkspaceIdVesselVesselIdRouteImport.update({
    id: '/vessel/$vesselId',
    path: '/vessel/$vesselId',
    getParentRoute: () => AppCategoryWorkspaceIdRoute,
  } as any)
const AppCategoryWorkspaceIdVesselGroupReportVesselGroupIdRoute =
  AppCategoryWorkspaceIdVesselGroupReportVesselGroupIdRouteImport.update({
    id: '/vessel-group-report/$vesselGroupId',
    path: '/vessel-group-report/$vesselGroupId',
    getParentRoute: () => AppCategoryWorkspaceIdRoute,
  } as any)
const AppCategoryWorkspaceIdPortsReportPortIdRoute =
  AppCategoryWorkspaceIdPortsReportPortIdRouteImport.update({
    id: '/ports-report/$portId',
    path: '/ports-report/$portId',
    getParentRoute: () => AppCategoryWorkspaceIdRoute,
  } as any)
const AppCategoryWorkspaceIdReportDatasetIdIndexRoute =
  AppCategoryWorkspaceIdReportDatasetIdIndexRouteImport.update({
    id: '/report/$datasetId/',
    path: '/report/$datasetId/',
    getParentRoute: () => AppCategoryWorkspaceIdRoute,
  } as any)
const AppCategoryWorkspaceIdReportDatasetIdAreaIdRoute =
  AppCategoryWorkspaceIdReportDatasetIdAreaIdRouteImport.update({
    id: '/report/$datasetId/$areaId',
    path: '/report/$datasetId/$areaId',
    getParentRoute: () => AppCategoryWorkspaceIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/user': typeof AppUserRoute
  '/vessel-search': typeof AppVesselSearchRoute
  '/api/auth': typeof ApiAuthRoute
  '/api/corrections': typeof ApiCorrectionsRoute
  '/api/downloadSurvey': typeof ApiDownloadSurveyRoute
  '/api/feedback': typeof ApiFeedbackRoute
  '/$category/$workspaceId': typeof AppCategoryWorkspaceIdRouteWithChildren
  '/report/$reportId': typeof AppReportReportIdRoute
  '/vessel/$vesselId': typeof AppVesselVesselIdRoute
  '/api/ocean-areas/name': typeof ApiOceanAreasNameRoute
  '/api/ocean-areas/search': typeof ApiOceanAreasSearchRoute
  '/$category/': typeof AppCategoryIndexRoute
  '/api/ocean-areas/': typeof ApiOceanAreasIndexRoute
  '/api/workspaces-generator/': typeof ApiWorkspacesGeneratorIndexRoute
  '/$category/$workspaceId/vessel-search': typeof AppCategoryWorkspaceIdVesselSearchRoute
  '/api/track-corrections/$workspaceId/$issueId': typeof ApiTrackCorrectionsWorkspaceIdIssueIdRoute
  '/$category/$workspaceId/': typeof AppCategoryWorkspaceIdIndexRoute
  '/api/track-corrections/$workspaceId/': typeof ApiTrackCorrectionsWorkspaceIdIndexRoute
  '/$category/$workspaceId/ports-report/$portId': typeof AppCategoryWorkspaceIdPortsReportPortIdRoute
  '/$category/$workspaceId/vessel-group-report/$vesselGroupId': typeof AppCategoryWorkspaceIdVesselGroupReportVesselGroupIdRoute
  '/$category/$workspaceId/vessel/$vesselId': typeof AppCategoryWorkspaceIdVesselVesselIdRoute
  '/$category/$workspaceId/report/': typeof AppCategoryWorkspaceIdReportIndexRoute
  '/$category/$workspaceId/report/$datasetId/$areaId': typeof AppCategoryWorkspaceIdReportDatasetIdAreaIdRoute
  '/$category/$workspaceId/report/$datasetId/': typeof AppCategoryWorkspaceIdReportDatasetIdIndexRoute
}
export interface FileRoutesByTo {
  '/user': typeof AppUserRoute
  '/vessel-search': typeof AppVesselSearchRoute
  '/api/auth': typeof ApiAuthRoute
  '/api/corrections': typeof ApiCorrectionsRoute
  '/api/downloadSurvey': typeof ApiDownloadSurveyRoute
  '/api/feedback': typeof ApiFeedbackRoute
  '/': typeof AppIndexRoute
  '/report/$reportId': typeof AppReportReportIdRoute
  '/vessel/$vesselId': typeof AppVesselVesselIdRoute
  '/api/ocean-areas/name': typeof ApiOceanAreasNameRoute
  '/api/ocean-areas/search': typeof ApiOceanAreasSearchRoute
  '/$category': typeof AppCategoryIndexRoute
  '/api/ocean-areas': typeof ApiOceanAreasIndexRoute
  '/api/workspaces-generator': typeof ApiWorkspacesGeneratorIndexRoute
  '/$category/$workspaceId/vessel-search': typeof AppCategoryWorkspaceIdVesselSearchRoute
  '/api/track-corrections/$workspaceId/$issueId': typeof ApiTrackCorrectionsWorkspaceIdIssueIdRoute
  '/$category/$workspaceId': typeof AppCategoryWorkspaceIdIndexRoute
  '/api/track-corrections/$workspaceId': typeof ApiTrackCorrectionsWorkspaceIdIndexRoute
  '/$category/$workspaceId/ports-report/$portId': typeof AppCategoryWorkspaceIdPortsReportPortIdRoute
  '/$category/$workspaceId/vessel-group-report/$vesselGroupId': typeof AppCategoryWorkspaceIdVesselGroupReportVesselGroupIdRoute
  '/$category/$workspaceId/vessel/$vesselId': typeof AppCategoryWorkspaceIdVesselVesselIdRoute
  '/$category/$workspaceId/report': typeof AppCategoryWorkspaceIdReportIndexRoute
  '/$category/$workspaceId/report/$datasetId/$areaId': typeof AppCategoryWorkspaceIdReportDatasetIdAreaIdRoute
  '/$category/$workspaceId/report/$datasetId': typeof AppCategoryWorkspaceIdReportDatasetIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/user': typeof AppUserRoute
  '/_app/vessel-search': typeof AppVesselSearchRoute
  '/api/auth': typeof ApiAuthRoute
  '/api/corrections': typeof ApiCorrectionsRoute
  '/api/downloadSurvey': typeof ApiDownloadSurveyRoute
  '/api/feedback': typeof ApiFeedbackRoute
  '/_app/': typeof AppIndexRoute
  '/_app/$category/$workspaceId': typeof AppCategoryWorkspaceIdRouteWithChildren
  '/_app/report/$reportId': typeof AppReportReportIdRoute
  '/_app/vessel/$vesselId': typeof AppVesselVesselIdRoute
  '/api/ocean-areas/name': typeof ApiOceanAreasNameRoute
  '/api/ocean-areas/search': typeof ApiOceanAreasSearchRoute
  '/_app/$category/': typeof AppCategoryIndexRoute
  '/api/ocean-areas/': typeof ApiOceanAreasIndexRoute
  '/api/workspaces-generator/': typeof ApiWorkspacesGeneratorIndexRoute
  '/_app/$category/$workspaceId/vessel-search': typeof AppCategoryWorkspaceIdVesselSearchRoute
  '/api/track-corrections/$workspaceId/$issueId': typeof ApiTrackCorrectionsWorkspaceIdIssueIdRoute
  '/_app/$category/$workspaceId/': typeof AppCategoryWorkspaceIdIndexRoute
  '/api/track-corrections/$workspaceId/': typeof ApiTrackCorrectionsWorkspaceIdIndexRoute
  '/_app/$category/$workspaceId/ports-report/$portId': typeof AppCategoryWorkspaceIdPortsReportPortIdRoute
  '/_app/$category/$workspaceId/vessel-group-report/$vesselGroupId': typeof AppCategoryWorkspaceIdVesselGroupReportVesselGroupIdRoute
  '/_app/$category/$workspaceId/vessel/$vesselId': typeof AppCategoryWorkspaceIdVesselVesselIdRoute
  '/_app/$category/$workspaceId/report/': typeof AppCategoryWorkspaceIdReportIndexRoute
  '/_app/$category/$workspaceId/report/$datasetId/$areaId': typeof AppCategoryWorkspaceIdReportDatasetIdAreaIdRoute
  '/_app/$category/$workspaceId/report/$datasetId/': typeof AppCategoryWorkspaceIdReportDatasetIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/user'
    | '/vessel-search'
    | '/api/auth'
    | '/api/corrections'
    | '/api/downloadSurvey'
    | '/api/feedback'
    | '/$category/$workspaceId'
    | '/report/$reportId'
    | '/vessel/$vesselId'
    | '/api/ocean-areas/name'
    | '/api/ocean-areas/search'
    | '/$category/'
    | '/api/ocean-areas/'
    | '/api/workspaces-generator/'
    | '/$category/$workspaceId/vessel-search'
    | '/api/track-corrections/$workspaceId/$issueId'
    | '/$category/$workspaceId/'
    | '/api/track-corrections/$workspaceId/'
    | '/$category/$workspaceId/ports-report/$portId'
    | '/$category/$workspaceId/vessel-group-report/$vesselGroupId'
    | '/$category/$workspaceId/vessel/$vesselId'
    | '/$category/$workspaceId/report/'
    | '/$category/$workspaceId/report/$datasetId/$areaId'
    | '/$category/$workspaceId/report/$datasetId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/user'
    | '/vessel-search'
    | '/api/auth'
    | '/api/corrections'
    | '/api/downloadSurvey'
    | '/api/feedback'
    | '/'
    | '/report/$reportId'
    | '/vessel/$vesselId'
    | '/api/ocean-areas/name'
    | '/api/ocean-areas/search'
    | '/$category'
    | '/api/ocean-areas'
    | '/api/workspaces-generator'
    | '/$category/$workspaceId/vessel-search'
    | '/api/track-corrections/$workspaceId/$issueId'
    | '/$category/$workspaceId'
    | '/api/track-corrections/$workspaceId'
    | '/$category/$workspaceId/ports-report/$portId'
    | '/$category/$workspaceId/vessel-group-report/$vesselGroupId'
    | '/$category/$workspaceId/vessel/$vesselId'
    | '/$category/$workspaceId/report'
    | '/$category/$workspaceId/report/$datasetId/$areaId'
    | '/$category/$workspaceId/report/$datasetId'
  id:
    | '__root__'
    | '/_app'
    | '/_app/user'
    | '/_app/vessel-search'
    | '/api/auth'
    | '/api/corrections'
    | '/api/downloadSurvey'
    | '/api/feedback'
    | '/_app/'
    | '/_app/$category/$workspaceId'
    | '/_app/report/$reportId'
    | '/_app/vessel/$vesselId'
    | '/api/ocean-areas/name'
    | '/api/ocean-areas/search'
    | '/_app/$category/'
    | '/api/ocean-areas/'
    | '/api/workspaces-generator/'
    | '/_app/$category/$workspaceId/vessel-search'
    | '/api/track-corrections/$workspaceId/$issueId'
    | '/_app/$category/$workspaceId/'
    | '/api/track-corrections/$workspaceId/'
    | '/_app/$category/$workspaceId/ports-report/$portId'
    | '/_app/$category/$workspaceId/vessel-group-report/$vesselGroupId'
    | '/_app/$category/$workspaceId/vessel/$vesselId'
    | '/_app/$category/$workspaceId/report/'
    | '/_app/$category/$workspaceId/report/$datasetId/$areaId'
    | '/_app/$category/$workspaceId/report/$datasetId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  ApiAuthRoute: typeof ApiAuthRoute
  ApiCorrectionsRoute: typeof ApiCorrectionsRoute
  ApiDownloadSurveyRoute: typeof ApiDownloadSurveyRoute
  ApiFeedbackRoute: typeof ApiFeedbackRoute
  ApiOceanAreasNameRoute: typeof ApiOceanAreasNameRoute
  ApiOceanAreasSearchRoute: typeof ApiOceanAreasSearchRoute
  ApiOceanAreasIndexRoute: typeof ApiOceanAreasIndexRoute
  ApiWorkspacesGeneratorIndexRoute: typeof ApiWorkspacesGeneratorIndexRoute
  ApiTrackCorrectionsWorkspaceIdIssueIdRoute: typeof ApiTrackCorrectionsWorkspaceIdIssueIdRoute
  ApiTrackCorrectionsWorkspaceIdIndexRoute: typeof ApiTrackCorrectionsWorkspaceIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/feedback': {
      id: '/api/feedback'
      path: '/api/feedback'
      fullPath: '/api/feedback'
      preLoaderRoute: typeof ApiFeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/downloadSurvey': {
      id: '/api/downloadSurvey'
      path: '/api/downloadSurvey'
      fullPath: '/api/downloadSurvey'
      preLoaderRoute: typeof ApiDownloadSurveyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/corrections': {
      id: '/api/corrections'
      path: '/api/corrections'
      fullPath: '/api/corrections'
      preLoaderRoute: typeof ApiCorrectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth': {
      id: '/api/auth'
      path: '/api/auth'
      fullPath: '/api/auth'
      preLoaderRoute: typeof ApiAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/vessel-search': {
      id: '/_app/vessel-search'
      path: '/vessel-search'
      fullPath: '/vessel-search'
      preLoaderRoute: typeof AppVesselSearchRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/user': {
      id: '/_app/user'
      path: '/user'
      fullPath: '/user'
      preLoaderRoute: typeof AppUserRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/workspaces-generator/': {
      id: '/api/workspaces-generator/'
      path: '/api/workspaces-generator'
      fullPath: '/api/workspaces-generator/'
      preLoaderRoute: typeof ApiWorkspacesGeneratorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ocean-areas/': {
      id: '/api/ocean-areas/'
      path: '/api/ocean-areas'
      fullPath: '/api/ocean-areas/'
      preLoaderRoute: typeof ApiOceanAreasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/$category/': {
      id: '/_app/$category/'
      path: '/$category'
      fullPath: '/$category/'
      preLoaderRoute: typeof AppCategoryIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/ocean-areas/search': {
      id: '/api/ocean-areas/search'
      path: '/api/ocean-areas/search'
      fullPath: '/api/ocean-areas/search'
      preLoaderRoute: typeof ApiOceanAreasSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ocean-areas/name': {
      id: '/api/ocean-areas/name'
      path: '/api/ocean-areas/name'
      fullPath: '/api/ocean-areas/name'
      preLoaderRoute: typeof ApiOceanAreasNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/vessel/$vesselId': {
      id: '/_app/vessel/$vesselId'
      path: '/vessel/$vesselId'
      fullPath: '/vessel/$vesselId'
      preLoaderRoute: typeof AppVesselVesselIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/report/$reportId': {
      id: '/_app/report/$reportId'
      path: '/report/$reportId'
      fullPath: '/report/$reportId'
      preLoaderRoute: typeof AppReportReportIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/$category/$workspaceId': {
      id: '/_app/$category/$workspaceId'
      path: '/$category/$workspaceId'
      fullPath: '/$category/$workspaceId'
      preLoaderRoute: typeof AppCategoryWorkspaceIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/track-corrections/$workspaceId/': {
      id: '/api/track-corrections/$workspaceId/'
      path: '/api/track-corrections/$workspaceId'
      fullPath: '/api/track-corrections/$workspaceId/'
      preLoaderRoute: typeof ApiTrackCorrectionsWorkspaceIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/$category/$workspaceId/': {
      id: '/_app/$category/$workspaceId/'
      path: '/'
      fullPath: '/$category/$workspaceId/'
      preLoaderRoute: typeof AppCategoryWorkspaceIdIndexRouteImport
      parentRoute: typeof AppCategoryWorkspaceIdRoute
    }
    '/api/track-corrections/$workspaceId/$issueId': {
      id: '/api/track-corrections/$workspaceId/$issueId'
      path: '/api/track-corrections/$workspaceId/$issueId'
      fullPath: '/api/track-corrections/$workspaceId/$issueId'
      preLoaderRoute: typeof ApiTrackCorrectionsWorkspaceIdIssueIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/$category/$workspaceId/vessel-search': {
      id: '/_app/$category/$workspaceId/vessel-search'
      path: '/vessel-search'
      fullPath: '/$category/$workspaceId/vessel-search'
      preLoaderRoute: typeof AppCategoryWorkspaceIdVesselSearchRouteImport
      parentRoute: typeof AppCategoryWorkspaceIdRoute
    }
    '/_app/$category/$workspaceId/report/': {
      id: '/_app/$category/$workspaceId/report/'
      path: '/report'
      fullPath: '/$category/$workspaceId/report/'
      preLoaderRoute: typeof AppCategoryWorkspaceIdReportIndexRouteImport
      parentRoute: typeof AppCategoryWorkspaceIdRoute
    }
    '/_app/$category/$workspaceId/vessel/$vesselId': {
      id: '/_app/$category/$workspaceId/vessel/$vesselId'
      path: '/vessel/$vesselId'
      fullPath: '/$category/$workspaceId/vessel/$vesselId'
      preLoaderRoute: typeof AppCategoryWorkspaceIdVesselVesselIdRouteImport
      parentRoute: typeof AppCategoryWorkspaceIdRoute
    }
    '/_app/$category/$workspaceId/vessel-group-report/$vesselGroupId': {
      id: '/_app/$category/$workspaceId/vessel-group-report/$vesselGroupId'
      path: '/vessel-group-report/$vesselGroupId'
      fullPath: '/$category/$workspaceId/vessel-group-report/$vesselGroupId'
      preLoaderRoute: typeof AppCategoryWorkspaceIdVesselGroupReportVesselGroupIdRouteImport
      parentRoute: typeof AppCategoryWorkspaceIdRoute
    }
    '/_app/$category/$workspaceId/ports-report/$portId': {
      id: '/_app/$category/$workspaceId/ports-report/$portId'
      path: '/ports-report/$portId'
      fullPath: '/$category/$workspaceId/ports-report/$portId'
      preLoaderRoute: typeof AppCategoryWorkspaceIdPortsReportPortIdRouteImport
      parentRoute: typeof AppCategoryWorkspaceIdRoute
    }
    '/_app/$category/$workspaceId/report/$datasetId/': {
      id: '/_app/$category/$workspaceId/report/$datasetId/'
      path: '/report/$datasetId'
      fullPath: '/$category/$workspaceId/report/$datasetId/'
      preLoaderRoute: typeof AppCategoryWorkspaceIdReportDatasetIdIndexRouteImport
      parentRoute: typeof AppCategoryWorkspaceIdRoute
    }
    '/_app/$category/$workspaceId/report/$datasetId/$areaId': {
      id: '/_app/$category/$workspaceId/report/$datasetId/$areaId'
      path: '/report/$datasetId/$areaId'
      fullPath: '/$category/$workspaceId/report/$datasetId/$areaId'
      preLoaderRoute: typeof AppCategoryWorkspaceIdReportDatasetIdAreaIdRouteImport
      parentRoute: typeof AppCategoryWorkspaceIdRoute
    }
  }
}

interface AppCategoryWorkspaceIdRouteChildren {
  AppCategoryWorkspaceIdVesselSearchRoute: typeof AppCategoryWorkspaceIdVesselSearchRoute
  AppCategoryWorkspaceIdIndexRoute: typeof AppCategoryWorkspaceIdIndexRoute
  AppCategoryWorkspaceIdPortsReportPortIdRoute: typeof AppCategoryWorkspaceIdPortsReportPortIdRoute
  AppCategoryWorkspaceIdVesselGroupReportVesselGroupIdRoute: typeof AppCategoryWorkspaceIdVesselGroupReportVesselGroupIdRoute
  AppCategoryWorkspaceIdVesselVesselIdRoute: typeof AppCategoryWorkspaceIdVesselVesselIdRoute
  AppCategoryWorkspaceIdReportIndexRoute: typeof AppCategoryWorkspaceIdReportIndexRoute
  AppCategoryWorkspaceIdReportDatasetIdAreaIdRoute: typeof AppCategoryWorkspaceIdReportDatasetIdAreaIdRoute
  AppCategoryWorkspaceIdReportDatasetIdIndexRoute: typeof AppCategoryWorkspaceIdReportDatasetIdIndexRoute
}

const AppCategoryWorkspaceIdRouteChildren: AppCategoryWorkspaceIdRouteChildren =
  {
    AppCategoryWorkspaceIdVesselSearchRoute:
      AppCategoryWorkspaceIdVesselSearchRoute,
    AppCategoryWorkspaceIdIndexRoute: AppCategoryWorkspaceIdIndexRoute,
    AppCategoryWorkspaceIdPortsReportPortIdRoute:
      AppCategoryWorkspaceIdPortsReportPortIdRoute,
    AppCategoryWorkspaceIdVesselGroupReportVesselGroupIdRoute:
      AppCategoryWorkspaceIdVesselGroupReportVesselGroupIdRoute,
    AppCategoryWorkspaceIdVesselVesselIdRoute:
      AppCategoryWorkspaceIdVesselVesselIdRoute,
    AppCategoryWorkspaceIdReportIndexRoute:
      AppCategoryWorkspaceIdReportIndexRoute,
    AppCategoryWorkspaceIdReportDatasetIdAreaIdRoute:
      AppCategoryWorkspaceIdReportDatasetIdAreaIdRoute,
    AppCategoryWorkspaceIdReportDatasetIdIndexRoute:
      AppCategoryWorkspaceIdReportDatasetIdIndexRoute,
  }

const AppCategoryWorkspaceIdRouteWithChildren =
  AppCategoryWorkspaceIdRoute._addFileChildren(
    AppCategoryWorkspaceIdRouteChildren,
  )

interface AppRouteChildren {
  AppUserRoute: typeof AppUserRoute
  AppVesselSearchRoute: typeof AppVesselSearchRoute
  AppIndexRoute: typeof AppIndexRoute
  AppCategoryWorkspaceIdRoute: typeof AppCategoryWorkspaceIdRouteWithChildren
  AppReportReportIdRoute: typeof AppReportReportIdRoute
  AppVesselVesselIdRoute: typeof AppVesselVesselIdRoute
  AppCategoryIndexRoute: typeof AppCategoryIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppUserRoute: AppUserRoute,
  AppVesselSearchRoute: AppVesselSearchRoute,
  AppIndexRoute: AppIndexRoute,
  AppCategoryWorkspaceIdRoute: AppCategoryWorkspaceIdRouteWithChildren,
  AppReportReportIdRoute: AppReportReportIdRoute,
  AppVesselVesselIdRoute: AppVesselVesselIdRoute,
  AppCategoryIndexRoute: AppCategoryIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  ApiAuthRoute: ApiAuthRoute,
  ApiCorrectionsRoute: ApiCorrectionsRoute,
  ApiDownloadSurveyRoute: ApiDownloadSurveyRoute,
  ApiFeedbackRoute: ApiFeedbackRoute,
  ApiOceanAreasNameRoute: ApiOceanAreasNameRoute,
  ApiOceanAreasSearchRoute: ApiOceanAreasSearchRoute,
  ApiOceanAreasIndexRoute: ApiOceanAreasIndexRoute,
  ApiWorkspacesGeneratorIndexRoute: ApiWorkspacesGeneratorIndexRoute,
  ApiTrackCorrectionsWorkspaceIdIssueIdRoute:
    ApiTrackCorrectionsWorkspaceIdIssueIdRoute,
  ApiTrackCorrectionsWorkspaceIdIndexRoute:
    ApiTrackCorrectionsWorkspaceIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
