const translations = 'used_to_get_dynamic_translations_autogenerated'

// Translations by feature.temporalgrid?.unit static keys
// t('common.hour', 'Hour')
// t('common.days', 'Day')
// t('common.days_other', 'Days')

// t('common.detection', 'Detection')
// t(['common.detection'], 'detections', { count: parseInt(value) })
// t('event.encounterAction', 'had an encounter with')

// t('event.fishing', 'Fishing event')
// t('event.fishing_other', 'Fishing events')
// t('event.encounter', 'Encounter event')
// t('event.encounter_other', 'Encounter events')
// t('event.port' 'Port')
// t('event.port_visit', 'Port visit')
// t('event.port_visit_other', 'Port visits')
// t('event.loitering', 'Loitering event')
// t('event.loitering_other', 'Loitering events')

export default translations
