export const DEFAULT_CSS_TRANSITION = '.35s'
export const DEFAULT_DATE_FORMAT = 'MMM D YYYY'
export const DEFAULT_FULL_DATE_FORMAT = 'MMM D YYYY HH:mm'

export const EVENT_SOURCE = {
  SEEK_MOVE: 'SEEK_MOVE',
  SEEK_RELEASE: 'SEEK_RELEASE',
  ZOOM_OUT_MOVE: 'ZOOM_OUT_MOVE',
  ZOOM_OUT_RELEASE: 'ZOOM_OUT_RELEASE',
  ZOOM_IN_RELEASE: 'ZOOM_IN_RELEASE',
  MOUNT: 'MOUNT',
  TIME_RANGE_SELECTOR: 'TIME_RANGE_SELECTOR',
  ZOOM_IN_BUTTON: 'ZOOM_IN_BUTTON',
  ZOOM_OUT_BUTTON: 'ZOOM_OUT_BUTTON',
  PLAYBACK_FRAME: 'PLAYBACK_FRAME',
}
