const TEMPLATE_SPREADSHEET_ID = process.env.NEXT_TURNING_TIDES_TEMPLATE_SPREADSHEET_ID || ''

export const SPREADSHEET_ID_BY_WORKSPACE = {
  'turning_tides_testing-user-public': TEMPLATE_SPREADSHEET_ID,
}
