steps:
  - name: 'alpine'
    id: 'Setup empty packages dir'
    args: ['ash', '-c', 'mkdir -p ./applications/vessel-history/node_modules/@globalfishingwatch']

  # Push production image to GCR
  - name: 'gcr.io/kaniko-project/executor:v1.6.0'
    id: 'Build production image'
    args:
      [
        '--destination=gcr.io/world-fishing-827/github.com/globalfishingwatch/vessel-history:$COMMIT_SHA',
        '--cache=$_USE_DOCKER_CACHE',
        '--build-arg',
        'REACT_APP_API_GATEWAY=$_REACT_APP_API_GATEWAY',
        '--build-arg',
        'REACT_APP_WORKSPACE_ENV=$_REACT_APP_WORKSPACE_ENV',
        '--build-arg',
        'REACT_APP_LIMITED_ACCESS_USER=$_REACT_APP_LIMITED_ACCESS_USER',
        '--build-arg',
        'REACT_APP_GOOGLE_UNIVERSAL_ANALYTICS_ID=$_REACT_APP_GOOGLE_UNIVERSAL_ANALYTICS_ID',
        '--build-arg',
        'BASIC_AUTH_USER=$_BASIC_AUTH_USER',
        '--build-arg',
        'BASIC_AUTH_PASS=$_BASIC_AUTH_PASS',
        '--build-arg',
        'REACT_APP_PUBLIC_URL=$_REACT_APP_PUBLIC_URL',
        '--target',
        'build',
        '-f',
        './applications/vessel-history/Dockerfile',
        '-c',
        './applications/vessel-history',
      ]

  - name: 'gcr.io/cloud-builders/docker'
    id: 'Run tests'
    args:
      [
        'run',
        'gcr.io/world-fishing-827/github.com/globalfishingwatch/vessel-history:$COMMIT_SHA',
        'npm',
        'test',
      ]

  - name: 'gcr.io/kaniko-project/executor:v1.6.0'
    id: 'Build nginx server image'
    args:
      [
        '--destination=gcr.io/world-fishing-827/github.com/globalfishingwatch/vessel-history:$COMMIT_SHA',
        '--cache=$_USE_DOCKER_CACHE',
        '--build-arg',
        'REACT_APP_API_GATEWAY=$_REACT_APP_API_GATEWAY',
        '--build-arg',
        'REACT_APP_WORKSPACE_ENV=$_REACT_APP_WORKSPACE_ENV',
        '--build-arg',
        'REACT_APP_LIMITED_ACCESS_USER=$_REACT_APP_LIMITED_ACCESS_USER',
        '--build-arg',
        'REACT_APP_GOOGLE_UNIVERSAL_ANALYTICS_ID=$_REACT_APP_GOOGLE_UNIVERSAL_ANALYTICS_ID',
        '--build-arg',
        'BASIC_AUTH_USER=$_BASIC_AUTH_USER',
        '--build-arg',
        'BASIC_AUTH_PASS=$_BASIC_AUTH_PASS',
        '--build-arg',
        'REACT_APP_PUBLIC_URL=$_REACT_APP_PUBLIC_URL',
        '--target',
        'production',
        '-f',
        './applications/vessel-history/Dockerfile',
        '-c',
        './applications/vessel-history',
      ]

  # Deploy to the appropriate environment
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'Deploy to cloud run'
    args: [
        'beta',
        'run',
        'deploy',
        '$_RUN_SERVICE_NAME',
        '--project',
        '$_RUN_PROJECT',
        '--image',
        'gcr.io/world-fishing-827/github.com/globalfishingwatch/vessel-history:$COMMIT_SHA',
        '--region',
        '$_RUN_REGION',
        '--platform',
        'managed',
        '--set-env-vars',
        'BASIC_AUTH=$_BASIC_AUTH,
        NODE_ENV=$_NODE_ENV',
        '--allow-unauthenticated',
      ]

images:
  - 'gcr.io/world-fishing-827/github.com/globalfishingwatch/vessel-history:$COMMIT_SHA'

timeout: 1800s
