version: '3.9'
services:
  real-time-prototype:
    build:
      context: ../../dist/apps/real-time-prototype
      dockerfile: ../../../apps/real-time-prototype/Dockerfile
      target: production
    container_name: real-time-prototype
    ports:
      - 3000:80
    env_file:
      - .env
    environment:
      - PORT=80
      - BASIC_AUTH=off
