export const SIDEBAR_LOGIN_LINK_TESTID = 'sidebar-login-link'
export const SIDEBAR_USER_LINK_TESTID = 'sidebar-user-link'
export const LOGOUT_BUTTON_TESTID = 'logout-button'
export const SETTINGS_BUTTON_TESTID = 'settings-button'
export const USER_WORKSPACES_TAB_TESTID = 'user-workspace'
export const REMOVE_WORKSPACE_BUTTON_TESTID = 'remove-workspace-button'
