const translations = 'used_to_get_dynamic_translations_autogenerated'

// Translations by feature.temporalgrid?.unit static keys
// t('common.hour')
// t('common.days')
// t('common.days_other')

// t('common.detection')
// t(['common.detection'], 'detections', { count: parseInt(value) })
// t('event.encounterAction')

// t('event.fishing')
// t('event.fishing_other')
// t('event.encounter')
// t('event.encounter_other')
// t('event.port' 'Port')
// t('event.port_visit')
// t('event.port_visit_other')
// t('event.loitering')
// t('event.loitering_other')

export default translations
