const translations = 'used_to_get_dynamic_translations_autogenerated'

// t('feedback.roles.watch', 'Watch officer')
// t('feedback.roles.analyst', 'Analyst')
// t('feedback.roles.navy', 'Navy or coast guard')
// t('feedback.roles.fisheries', 'Fisheries enforcement or compliance officer')
// t('feedback.roles.ngo', 'Non-governmental organization')
// t('feedback.roles.scientist', 'Scientist')
// t('feedback.roles.journalist', 'Journalist')
// t('feedback.roles.student', 'Student')
// t('feedback.roles.general', 'General public')
// t('feedback.roles.GFW', 'Global Fishing Watch staff')
// t('feedback.roles.other', 'Other')

// t('feedback.features.vesselSearch', 'Vessel Search')
// t('feedback.features.infoTab', 'Info Tab')
// t('feedback.features.activityTab', 'Activity Tab')
// t('feedback.features.mapTab', 'Map Tab')
// t('feedback.features.offlineAccess', 'Offline Access')
// t('feedback.features.highlightsEvents', 'Highlights Events')


export default translations
