name: Build and Deploy (Production)

on:
  push:
    tags:
      - '@gfw/*@*'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  deploy:
    uses: ./.github/workflows/_build-and-deploy.yml
    permissions:
      contents: read
      id-token: write
    with:
      env-suffix: pro
      config: .github/apps/production.yml
      service-prefix: ui
      cloudrun-project: gfw-production
      environment: production
    secrets: inherit
