name: i18n-labels stable

on:
  push:
    tags:
      - "@gfw/fishing-map@*"
  workflow_dispatch:

concurrency:
  group: i18n-labels-stable
  cancel-in-progress: false

permissions:
  id-token: write # Required for OIDC
  contents: read

jobs:
  stable:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: pnpm/action-setup@v6

      - uses: actions/setup-node@v6
        with:
          node-version: "24"
          registry-url: "https://registry.npmjs.org"
          cache: pnpm

      - run: pnpm install --frozen-lockfile

      - name: Tag latest as stable
        run: |
          npm whoami
          LATEST=$(npm dist-tag ls @globalfishingwatch/i18n-labels | grep -Ew 'latest: (.*)' | sed 's/latest: //')
          npm dist-tag add @globalfishingwatch/i18n-labels@$LATEST stable
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Purge jsdelivr cache
        run: pnpm nx run i18n-labels:purge:stable
