name: i18n-labels stable

on:
  push:
    tags:
      - "@gfw/fishing-map@*"
  workflow_dispatch:

concurrency:
  group: i18n-labels-stable
  cancel-in-progress: false

permissions:
  id-token: write # Required for OIDC
  contents: read

jobs:
  stable:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          token: ${{ secrets.GH_PA_TOKEN }}

      - uses: pnpm/action-setup@v6

      - uses: actions/setup-node@v6
        with:
          node-version: "24"
          cache: pnpm

      - run: pnpm install --frozen-lockfile

      - name: Authenticate pnpm with npm registry
        run: pnpm config set //registry.npmjs.org/:_authToken ${{ secrets.NPM_TOKEN }}

      - name: Publish stable to NPM
        run: pnpm nx run i18n-labels:publish:stable

      - name: Purge jsdelivr cache
        run: pnpm nx run i18n-labels:purge:stable
