name: i18n-labels stable

on:
  push:
    tags:
      - "@gfw/fishing-map@*"
  workflow_dispatch:

concurrency:
  group: i18n-labels-stable
  cancel-in-progress: false

permissions:
  id-token: write # Required for OIDC
  contents: read

jobs:
  stable:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          token: ${{ secrets.GH_PA_TOKEN }}

      - uses: pnpm/action-setup@v6

      - uses: actions/setup-node@v6
        with:
          node-version: "24"
          registry-url: "https://registry.npmjs.org"
          cache: pnpm

      - name: Setup Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GH_PA_TOKEN }}@github.com/${{ github.repository }}.git

      - run: pnpm install --frozen-lockfile

      - name: Authenticate pnpm with npm registry
        run: pnpm config set //registry.npmjs.org/:_authToken ${{ secrets.NPM_TOKEN }}

      - name: Publish stable to NPM
        run: pnpm nx run i18n-labels:publish:stable
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Purge jsdelivr cache
        run: pnpm nx run i18n-labels:purge:stable
